### ISSUE TITLE
`make unit` intermittently fails with kafka / topic issues. Consider eliminating Kafka.

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#10]
make unit should run all unit tests across open-kilda.

Unit tests should ideally be just that - testing a unit of software - without the need for other subsystems like kafka. This would require refactoring the code and the tests to enable tests without the need for kafka.

- [x] Day 1. Research.
- [x] Day 2. evaluate org.openkilda.wfm.topology.stats.StatsTopologyTest .. it occasionally causes unit tests to fail
- [ ] Day 3. CacheTopoloy, OpenTSDBTopology. FlowTopology

Move to separate ticket
- Cover IslStatsTopology with tests  
- Cover OFEventWFMTopology, EFEventSplitterTopology

**Comment by carmine** [comment]
Sachin to deliver

**Comment by carmine** [comment]
I updated the description to include evaluation of StatsTopologyTest .. just witnessed a case where it causes `mvn test` to fail. Re-run it and it passes.  The message in the output .. ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl - Background retry gave up

**Comment by nikitacherevko** [comment]
I guess it will take up to 5days to rewrite those test, 
but I think it is good idea to test storm topologies with integration tests, because we should be sure that our topologies interact as expected with all tolls and external services we depend on

**Comment by nikitamarchenko** [comment]
We need to separate test on unit, integration, and acceptance, and don't mix theirs. That issue is very similar to #24. 5d
