### ISSUE TITLE
Fix/reinvent health check monitoring

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1000]
We have health check endpoint in NB HealthCheckController. It's goal to report each component actual health check.

The problem in current implementation - in case of problem in any compoment(no response), the duration of health check call become extremely high... i.e. caller side give up to wait and drop connection with 'timeout error'.

GOAL: NB must report health check state in reasonable time 5-10 seconds.

Make obsolete #197, #50

**Comment by IlyaMoiseev** [comment]
Prepared [architecture proposition](https://github.com/telstra/open-kilda/blob/c7a287b6efaa4b8879b6ba755a757d913486c845/docs/design/solutions/health-check/health-checks.md) for this. 
In general, monitoring software calls REST health endpoints for each module.
If module doesn't have REST facade (eg. TE) - it may be done by monitoring kafka topic consumer lags, or via beats through kafka to NB.

**Comment by IlyaMoiseev** [comment]
Updates [architecture proposition](https://github.com/telstra/open-kilda/blob/5c94a97b23561dcc5c09c0c8cbdc558c277f283b/docs/design/solutions/health-check/health-checks.md). 
All "proposing" monitorings are already works, @PinGwynn check me if I'm not right.
We need approve this decision to remove old obsolete code from NB and Storm.
@jonvestal @carmine @nikitamarchenko What do you think?

**Comment by IlyaMoiseev** [comment]
Fixed in #1357
