### ISSUE TITLE
Floodlight might stop processing messages

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#1008]
org.openkilda.floodlight.kafka.Consumer polls messages from kafka and passes those messages to executor service. There is a possibility that FL may receive too many messages and stop consume messages at all. 

Possible reason: 
Since Consumer creates RecordHandler objects for every message received and puts them into tasks queue. Because of that we might face out of memory error and Consumer will stop working.

Possible solution:
We can put consumer in scheduled thread pool and even if some error occur we still will have Consumer running, because it will be re-run.
```Executors.newScheduledThreadPool(1).scheduleWithFixedDelay(consumer, 0, 0, TimeUnit.MICROSECONDS);```

**Comment by sergii-iakovenko** [comment]
org.openkilda.floodlight.kafka.Consumer has been refactored and doesn't keep queued messages in the memory anymore. However it's still technically possible to have Consumer being terminated and FL not processing Kafka messages.
We need to develop a way to monitor the health of FL modules.
