### ISSUE TITLE
Floodlight's 'get meters' returns maximum 100 meters for Novi switches.

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1022]
*Steps:*
1. Create 100+ flows on a Noviflow switch. Lets say we have 150 flows.
2. Call floodlight's endpoint `/wm/kilda/meters/switch_id/${switchId}`
**Expected:** 150 meters returned.
**Actual:** 100 meters returned: 50 first meters and 50 last meters (with 50 meters in the middle missing)
Note1: All meters are correctly installed on switches, only the returned results are incorrect.
Note2: The issue does not appear for Centec switches.

**Comment by nikitamarchenko** [comment]
FL endpoint "/wm/core/switch/{sw_id}/meter-config/json" has limitation of 100, so bug in FL not in our FL-module.
