### ISSUE TITLE
atdd-staging: add switch manufacturer/model to the topology model

### ISSUE THREAD

**Issue by npliashechnikov** [telstra/open-kilda#1027]
In order to test flow management reliably, we need to run tests on all models of the networking equipment present in the testing environment. Previously, reliability was achieved by selecting switches in a random fashion, but at the cost of the reproduceability. To achieve both, test should be aware of the equipment in the environment.

**Comment by rtretyak** [comment]
For now decided to go with the switch description, since it usually has the manufacturer and even the firmware version
