### ISSUE TITLE
Unable to create flow on port, which is busy with 'moved' ISL

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1041]
Related to #1024.
Steps:
1. Adjust the system so that you have at least one MOVED isl
2. Create a flow with src or dst switch-port matching the non-connected switch-port of the MOVED ISL.
**Expected:** Flow successfully created
**Actual:** Could not create flow because port is busy with an ISL

**Comment by surabujin** [comment]
The flow vs ISL collision was reveted/removed (https://github.com/telstra/open-kilda/commit/8bd677d9e7f42676feb8077faf2b753d979d9e3b). It make this issue "invalid", until https://github.com/telstra/open-kilda/issues/1060 is not implemented.

**Comment by rtretyak** [comment]
No longer valid. as discussed in #2192 we now forbid new flows on ISLs in any state
