### ISSUE TITLE
False positive missing OF rules detection

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1042]
If switch will disconnect during switch `/switches/{switch_id}/rules/validate` call, all rules related to this switch will be reported as "missing".

```
July 24th 2018, 06:47:03.735	kilda-floodlight	ERROR	Could not get flow stats for ff:fe:00:00:00:00:00:01.
July 24th 2018, 06:47:03.734	kilda-floodlight	ERROR	Disconnecting switch [ff:fe:00:00:00:00:00:01(0x0) from 127.1.0.2/127.1.0.2:48634] due to IO Error: Connection reset by peer
July 24th 2018, 06:47:03.734	kilda-floodlight	INFO	[[ff:fe:00:00:00:00:00:01(0x0) from 127.1.0.2/127.1.0.2:48634]] Disconnected connection
July 24th 2018, 06:47:03.379	kilda-floodlight	DEBUG	Loading installed rules for switch ff:fe:00:00:00:00:00:01
```

The problem is in `org.openkilda.floodlight.switchmanager.SwitchManager#dumpFlowTable` it silently return emty list if `future.get()` raise an exception.

We need to distinguish "missing rules" and errors during report preparation. We should report that switch is unmanaged and the set of affected flows, and not report all OF rules as missing.

**Comment by abochkarev** [comment]
This issue will require:
investigation - 2d;
collecting requirements - 3d;
implementation - 3d;
testing - 2d;
