### ISSUE TITLE
Deny creation of self-looped ISL

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1059]
Customer equipment attached to our ports can return our discovery packet back to our switch... It can be a loop on:
- different port on same switch
- same port (i.e. port used to send discovery package)
- different switch

We can easily detect first 2 cases. The last case should be covered into https://github.com/telstra/open-kilda/issues/579.

So we must prevent creation of self-looped ISLs.

**Comment by IlyaMoiseev** [comment]
@nikitamarchenko @carmine Do we need to visualize this incorrect links on UI?

**Comment by nikitamarchenko** [comment]
Roman, could you cover that with functional test please
