### ISSUE TITLE
Remove the checkstyle rule for "finalizing" method's signature/local variables.

### ISSUE THREAD

**Issue by abochkarev** [telstra/open-kilda#1069]
It's required to get rid of the checkstyle rule (rules) which obligates developers to mark method's signature/local variables as final.

**Comment by sergii-iakovenko** [comment]
@abochkarev OpenKilda checkstyle configuration has neither FinalLocalVariable nor FinalParameters modules enabled. Could you clarify what rule enforces you to use the final keyword?

**Comment by abochkarev** [comment]
@sergii-iakovenko Let me check, please.

**Comment by abochkarev** [comment]
@sergii-iakovenko Re-checked the checktyle configuration - VariableDeclarationUsageDistance. This module is used with default properties, like:
A distance between the declaration of the variable and its first usage == 3
Allow ignoring variables with a 'final' modifier == true
More details here: http://checkstyle.sourceforge.net/config_coding.html#VariableDeclarationUsageDistance
We could omit this checkstyle configuration at all or make it a bit softer. What do you think?

**Comment by sergii-iakovenko** [comment]
I'd prefer to remove VariableDeclarationUsageDistance only for test code where violations caused by variables declared upfront in order to define preconditions, expected results, etc. 

In production code the check encourages developers to limit the variable scope and improves code readability.

**Comment by abochkarev** [comment]
Final options:
- don't apply "VariableDeclarationUsageDistance" checkstyle for tests. As it was suggested by @sergii-iakovenko we could use the regexp approach to it: https://github.com/palantir/docker-compose-rule/blob/master/.baseline/checkstyle/checkstyle-suppressions.xml#L12 ;
- fix all suppresses: make the required changes in code/"suppress" xml files;
