### ISSUE TITLE
Topology Engine has no safe fallback mechanism if receive bad response from Neo

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1079]
**Steps:**
1. Create a flow with `'` sign in flow description. This will reveal the #1051 issue and create an invalid DB request
1.1. Alternative way: use steps described in #1076
**Expected:** eventhough tpe ended up in error, it should be able to continue operating instead of infinitely trying to fail-retry.
**Actual:** TPE is 'dead' and requires manual healing.

**Comment by pzakatov** [comment]
@surabujin , please verify this ticket

**Comment by npliashechnikov** [comment]
Verified - the issue can no longer be reproduced on current develop branch
