### ISSUE TITLE
handle IOException in stats CacheBolt method initFlowCache

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#1088]
Handle java.io.IOException: Message too long in org.openkilda.wfm.topology.stats.bolts.CacheBolt#initFlowCache

Problem: cookieToFlow very big to write in logger
Move `logger.info("initFlowCache: {}", cookieToFlow);` to debug and add message like `Stats Cache: Initialized`

**Comment by abochkarev** [comment]
@nikitamarchenko Am I correct that idea just to change the logger level and don't put to log cookieToFlow?

**Comment by nikitamarchenko** [comment]
@abochkarev 
1. decrease logger.info("initFlowCache: {}", cookieToFlow) to debug
2. add new log info message `Stats Cache: Initialized`

**Comment by abochkarev** [comment]
@nikitamarchenko Thank you, Nikita!
