### ISSUE TITLE
Get rid of checkstyle-suppress-known-issues.xml files

### ISSUE THREAD

**Issue by abochkarev** [telstra/open-kilda#1095]
It's required to get rid of checkstyle-suppress-known-issues.xml files because engineers must waste much time just for changing line numbers of suppressions.

**Comment by pzakatov** [comment]
Could be related to #788

**Comment by surabujin** [comment]
Are we going to relax some style rules?

PS Why for we change line numbers if we can just fix violation in affected files?

**Comment by abochkarev** [comment]
@surabujin Some of them, like: </p> in javadocs, must be relaxed. The idea not to change line numbers, just fix them and get rid of checkstyle-suppress-known-issues.xml.

**Comment by nikitamarchenko** [comment]
@abochkarev main idea to fix checkstyle and remove old suppress from suppress-known-issues.xml

**Comment by abochkarev** [comment]
@nikitamarchenko We don't need to have suppress-known-issues.xml files at all. I don't know who decided to use them, but the idea is terrible. There are cases when we really need to suppress warnings - @SuppressWarning looks more convenient.

**Comment by sergii-iakovenko** [comment]
@abochkarev The idea was to start enforcing checkstyle rules for newly introduced or updated code. And suppress-known-issues.xml is just a way to ignore existing violations as we couldn't afford to fix them in one shot.
I agree that @SuppressWarning is what we should use in the future, but not for the existing violations. Instead, we agreed to fix them class-by-class during the development process.
