### ISSUE TITLE
[Kilda-Gui] [Backend] Fix all checkstyle issues on the GUI Backend

### ISSUE THREAD

**Issue by hiteshgupta1** [telstra/open-kilda#1108]

**Comment by pzakatov** [comment]
@hiteshgupta1 , what is the purpose of refactoring?

**Comment by hiteshgupta1** [comment]
Under this refactoring task we are targeting to follow the same check-style pattern for whole application that we are following in other services.

**Comment by pzakatov** [comment]
@hiteshgupta1 , renamed the task so it reflects your actual goal
