### ISSUE TITLE
Value passed as path variable (`@PathVariable`) is truncated it if contain '.'

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1110]
If the value is the last segment (splitted by '/' characters) in the url path, and it contain '.' character, everything after dot(last dot) including dot are truncated.

https://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated

Affected API endpoints:
```
GET {NB}/api/v1/flows/{flow-id}
PUT {NB}/api/v1/flows/{flow-id}
DELETE {NB}/api/v1/flows/{flow-id}
GET {NB}/api/v1/flows/status/{flow-id}
```

**Comment by abochkarev** [comment]
Yes, there is a problem with such a group of params. As an example:
1) Create a flow with the id "c3.none-1"
2) Try to execute a simple curl request:
`curl "http://localhost:8088/api/v1/flows/c3.none-1" -H "accept: application/json;charset=UTF-8" --user kilda:kilda`
**Actual:**
`{"correlation_id":"2350af52-cc2f-43a9-a248-03984321709f","timestamp":1533649124315,"error-type":"Object was not found","error-message":"Can not get flow: Flow c3 not found","error-description":"splitter_bolt"}`
**Expected:**
`The body of the created flow`

**Comment by rtretyak** [comment]
Verified that the problem is no longer reproducible. The only left place is `@DeleteMapping(path = "/switches/{switch_id}/meter/{meter_id}")` but this barely affects the functionality, as this param is always integer
