### ISSUE TITLE
[Kilda-Gui] [Frontend] Refactoring kilda gui frontend 

### ISSUE THREAD

**Issue by neeraj890kumar** [telstra/open-kilda#1111]

**Comment by pzakatov** [comment]
@neeraj890kumar , what is the purpose of refactoring?

**Comment by neeraj890kumar** [comment]
Under this refactoring  task, target is to remove unused code, create common function to generate graphs and reuse this for isl, flow and port graph  and extract code to get data for  isl, flow, port graph from API and moved in separate files.
