### ISSUE TITLE
Change code on "Port/Vlan occupied by another flow" error to "409 Conflict" (Create Flow case)

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1119]
in case of [this](https://github.com/telstra/open-kilda/blob/develop/services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java#L86) and similar errors during Flow create request, HTTP code should be 409 Conflict

**Comment by npliashechnikov** [comment]
Verified - currently Kilda returns HTTP 409 on "Create Flow" call if port/vlan combination is already occupied, though VLAN ID is not returned in the response.
