### ISSUE TITLE
Update test cases for switch Port Up/Down Request

### ISSUE THREAD

**Issue by ashishaggarwalCS** [telstra/open-kilda#1121]
Scope:
1. [As per comment](https://github.com/telstra/open-kilda/pull/1080/files#diff-53f9c28ec1c6d5bd9178f26ed06b6ce8R315) change behavior depending on "is null check" for this field
2. [As per comment](https://github.com/telstra/open-kilda/pull/1080/files#diff-84f372a6ac93cb002f8a7a61bd1ce24cR29) fix typo, regex, add checks.
3. [As per comment](https://github.com/telstra/open-kilda/pull/1080/files#diff-84f372a6ac93cb002f8a7a61bd1ce24cR31) remove try/catch
4. [As per comment](https://github.com/telstra/open-kilda/pull/1080/files#diff-3f8cc86ad5755af5260e1cf80e149519R8) change swithces in topology to 1

**Comment by pzakatov** [comment]
Referrence: https://github.com/telstra/open-kilda/pull/1080/files#diff-84f372a6ac93cb002f8a7a61bd1ce24cR29

**Comment by ashishaggarwalCS** [comment]
Pull request is closed and not merge, so this task in not required.
New pull request with this feature already have the required changes in it.
