### ISSUE TITLE
Implement the LabService to enable testing on both virtual and physical environments

### ISSUE THREAD

**Issue by npliashechnikov** [telstra/open-kilda#1133]
In order to create the automated test cases which will run seamlessly on either physical or virtual OpenKilda deployments using the same code paths, we are going to need a common interface for accessing them.

So far, there is a design document describing the LabService API here: https://github.com/telstra/open-kilda/tree/develop/docs/design/test-lab. The implementation of such service would be extremely useful for the test cases development and debugging, as the QA engineers wouldn't have to use the physical environment in the process of debugging.

**Comment by carmine** [comment]
Related to #917
