### ISSUE TITLE
Deduplicate ISL properties locations

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1135]
At this moment we use 2 separate entity keeps ISL properties - first ISL itself (2 neo4j relations), second link_props (neo4j node).

Because it is 2 completely different entity, we had to support 2 separate management layers (object life cycle). There is no common/shared code used by this entities. Also there is a separate layer to "sync" data between link_props and ISL `objects`.

The reason why link_props was created is the ability to define ISL properties when the ISL is not discovered yet. And to keep "persistent" link props if ISL is removed from DB (we do not allow to remove ISL from DB now, so this link_props `feature` is not required any more).

There is a way to significantly simplify whole ISL(link_props) management. We can completely eliminate link_props entity and all related management and synchronization logic.

When we want to define/manipulate any ISL property we can put it on ISL object(relation) itself. There is 2 cases - when ISL exist and when ISL don't exist in DB.

When ISL exist we just update property on it (same as it done now, but without synchronization with link_props). When there is no ISL we should create new ISL relation(pair of relations) with special status - `template` (`ghost` or any other name that is no `active` and `inactive`). On the ISL discovery time all "missing" properties will placed on this `template` object and it's status will be switched on `active`.

NB API will "filter out" all ISL with status `template` from link operation. Link prop NB API will operation on ISL in `template` state. In other word - we keep current API for external callers(if we want to keep it) and decrement amount of entries inside our system.

**Comment by carmine** [comment]
In general, I agree.  One of the minor issues is that you'll have stuff in the database - ie switches and isls .. that may not exist yet. This affects UI, etc.

**Comment by carmine** [comment]
Need proposal
