### ISSUE TITLE
There is a possibility to make available bandwidth for a link negative

### ISSUE THREAD

**Issue by ylobankov** [telstra/open-kilda#1150]
**Environment:**
Linear topology with two switches (switch A and switch B). There should be one link at least between switches.

**Steps to reproduce:**
1. Create a flow from switch A to switch B. The 'ignore_bandwidth' flag should be set to **True** in the request body. It is important!
2. Update the flow. The value for maximum bandwidth for flow should be more than available bandwidth for the link. For example, the available bandwidth for the link is 1000. So we should set the value for maximum bandwidth for the flow to 1100. The 'ignore_bandwidth' flag should be set to **False** in the request body. It is important!
**Expected:** System returns an error that it is not able to do such update (not enough bandwidth on the link)
**Actual**: Available bandwidth for the link between switch A and switch B became negative, though flow is 'ignore_bandwidth=false'

**Comment by rtretyak** [comment]
The issue is still reproducible in V2
