### ISSUE TITLE
Strange kilda-floodlight errors in logs when updating a flow

### ISSUE THREAD

**Issue by ylobankov** [telstra/open-kilda#1151]
**Environment:**
Linear topology with two switches (switch A and switch B). There should be one link at least between switches.

**Steps to reproduce:**
Create a flow from switch A to switch B. The value for maximum bandwidth in the request body should be equal to 1.

**Expected result:**
There are no errors in logs.

**Actual result:**
**ERROR**  OFMeterModFailedErrorMsgVer13(xid=481919, code=UNKNOWN_METER, data=OFFlowAddVer13(xid=481919, cookie=0x4000000000000043, cookieMask=0x0000000000000000, tableId=0x0, idleTimeout=0, hardTimeout=0, priority=24576, bufferId=4294967295, outPort=any, outGroup=any, flags=[], match=OFMatchV3Ver13(in_port=6), instructions=[OFInstructionMeterVer13(meterId=77), OFInstructionApplyActionsVer13(actions=[OFActionPushVlanVer13(ethertype=0x8100), OFActionSetFieldVer13(field=OFOxmVlanVidVer13(value=0x1086)), OFActionOutputVer13(port=6, maxLen=65535)])])) from switch OFSwitch DPID[00:00:00:22:3d:6c:00:b8] in state net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$MasterState@5b4aa155

**ERROR**  OFMeterModFailedErrorMsgVer13(xid=481910, code=BAD_RATE, data=OFMeterModVer13(xid=481910, command=ADD, flags=[KBPS, BURST], meterId=77, meters=[OFMeterBandDropVer13(rate=1, burstSize=1024)])) from switch OFSwitch DPID[00:00:00:22:3d:6c:00:b8] in state net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$MasterState@5b4aa155

**Comment by surabujin** [comment]
Looks like switche's meter have minimum allowed bandwidth.

So you don'y need first step to reproduce this issue. Just create flow with bandwidth 1.

**Comment by ylobankov** [comment]
@surabujin Yes, you are right. The first test is really not mandatory.

**Comment by surabujin** [comment]
@ylobankov update topic and description... Or create new issue with fixed bug definition.

**Comment by ylobankov** [comment]
@surabujin Description is fixed.

**Comment by rtretyak** [comment]
related to #1697
