### ISSUE TITLE
Evolve ATDD test stages - atdd-sim (simulator), and move/add ATs

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#116]
Key outcomes:

- [x] we've identified the ATs that can run in simulator mode
- [ ] we've added logic that allows some ATs to run in multiple modes (simulated, virtual)
- [ ] we've identified ATs that can be limited to simulated only (ie no need to run in virtual mode)

**Comment by nikitacherevko** [comment]
So the main idea of this task is:
- define the list of ATs that may be rewritten to use simulator mode
- define the list of ATs that have to be rewritten for this mode, so we can reduce the use of mininet for them
- add some logic/utils/helpers for our ATs to create possibility run is both/separate modes
@carmine Please correct me if I missed something. And should ATs be rewritten to use newly created helpers or I have to create just two lists of ATs? Thanks in advance

**Comment by carmine** [comment]
That sounds about right. For ATs that a fundamentally about testing / confirming the logic in the Storm Topologies, those should be re-written to use the simulator.

If there are tests that exercise functionality in the speaker, then those should be done in the virtual (mininet) tests.

There are probably some tests that test both sides .. those can probably remain as virtual atdd. However, consider separating the storm part of the test into another test so that the simulator can test it.

The more we can leverage the simulator to test the topologies, the more we can get quicker feedback.

**Comment by ylobankov** [comment]
It looks like this is a stale issue for now. ATDD module is being removed from the project (#1817 ). So the issue will not be resolved and can be closed.
