### ISSUE TITLE
Logging issue: port down event won't be properly logged if port has no link attached

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1164]
1. Bring down a port that has no ISL attached to it
**Expected:** Kibana reads "DISCO: Port Event: switch=$switch port=$port state=**DOWN**"
**Actual:** Kibana reads "DISCO: Port Event: switch=$switch port=$port state=**OTHER_UPDATE**"
Note1: The same behavior for Port Up operation 
Note2: works as expected if target port has an ISL

@nikitamarchenko please confirm whether this defect is valid or this was made intentionally.

**Comment by Levitan** [comment]
as designed
