### ISSUE TITLE
Unhandled NPE in Floodlight if trying to configure '-1' port

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1165]
1. Call `/api/v1/switches/$switch/port/$port/config` with port=-1 and valid payload
**Expected:** Kilda is able to properly handle invalid input
**Actual:** Kilda returns no response (timeout) and FL throws unhandled NPE Error in logs

**Comment by npliashechnikov** [comment]
Verified - fixed, now NB returns correct error message immediately.
