### ISSUE TITLE
Add AT - Resilience Test - speaker outage (network partition) - light load, heavy load (document bugs)

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#117]
We'd like to understand what happens if there is a network partition between the speaker (ie floodlight) and the rest of the system (eg Storm Topologies). 

A series of tests should be created that will create the partition (ie make it so that the speaker and storm don't talk to each other) for a minute .. maybe for 5 minutes as well .. and then:
1) create a request per 10 seconds .. to create flows or delete flows
2) create a request per second .. same as above

Then reconnect the speaker and see if things recover.  For this test, we should expect to see ISLs disappear of the health checks fail, as per the ISL health check policy. So, this may need to be adjusted.

**Comment by surabujin** [comment]
@carmine please put more details into ticket body. Just to be sure what exactly result we should have at the end.

**Comment by carmine** [comment]
Description updated on 12/18

**Comment by pzakatov** [comment]
@rtretyak , please validate this ticket for possible test cases. close once done.

**Comment by rtretyak** [comment]
Decided that this can be implemented in ATDD-Staging suite by 
1. Creating a simple rest server that is able to block certain connections
2. deploy it on floodlight's machine
3. On demand cut the floodlight's connection to kafka
4. verify the system behavior under certain load
