### ISSUE TITLE
Add AT - Resilience Test - speaker bounce (restart) - light load, heavy load (document bugs)

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#118]
This issue is to explore the scenarios around the floodlight speaker going through a lifecycle event. This would cause an outage wrt kafka message processing, and causes issues for network topology health checks.

Light load / heavy load is related to the amount of traffic on the control plane .. what happens as things back up? What happens when the speaker comes back online?

**Comment by pzakatov** [comment]
@rtretyak , please validate this ticket for possible test cases. close once done.

**Comment by rtretyak** [comment]
Decided that we can add a test to ATDD-Staging suite that will send a restart command to the floodlight's docker daemon and verify the system behavior in this situation. 
Before we proceed with actual implementation, I'm really interested to first try this manually to see what we can really verify in this scenario.
Leaving this assigned to myself, will get back after investigation.
