### ISSUE TITLE
Do not reissue same reroute for a flow for some time

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#1192]
Multiple reroutes on a flow within a short time period cause race condition in installation of switch rules. As the result the flow ends up in non-operation condition and a number of missing / excessive rules are left on switches.

In order to prevent the race condition, we need to combine reroute commands issued within the configured time window, so they're never performed concurrently:
- FlowRerouteRequest which going to CrudBolt from NB or CacheBolt must pass a new step - reduction of repeat requests.
- Regardless of the origin and cause of FlowRerouteRequest, we combine all commands for the same flowId into a one and hold on unless the configured time is passed from the previous reroute command.

#### The solution based on tick tuples and StatefulBolt ####
- A new bolt is introduced in Flow topology. The bolt intercepts requests coming to CrudBolt.
- The bolt checks whether another FlowRerouteRequest for the same ID passed within the reduction time window (just an in-memory map of flowId to timestamp). And if it's so then the bolt schedules the command to be sent at the end of the time window. Scheduled commands are kept in memory (the bolt state).
-  The bolt checks the scheduled commands periodically (E.g. on a tick tuple) and sends them if it's time.

#### The solution based on Storm's  [IWindowedBolt](http://storm.apache.org/releases/2.0.0-SNAPSHOT/Windowing.html) ####
- A new bolt (extends BaseStatefulWindowedBolt) is introduced in Flow topology. The bolt intercepts requests coming to CrudBolt.
- The bolt is configured to slide the window every 1 second (or less), and the length of window equals to the reduction time window.
- The bolt process only tuples with FlowRerouteRequest partitioned by flowId. 
- The bolt checks whether the window contains FlowRerouteRequest with correlationId equals to saved in memory (a map of flowId to correlationId). And doesn't emit any tuple until the FlowRerouteRequest with saved correlationId is out of the window.
- The bolt emits FlowRerouteRequest when the previous one goes off the window. And saves the correlationId of the last FlowRerouteRequest seen in the window.

**Comment by pzakatov** [comment]
Approved by @carmine

**Comment by pzakatov** [comment]
in addition to that, add throttling to reflows, so we do not do more than Z reroutes in Y seconds.

**Comment by rtretyak** [comment]
Flow diagram described here: #1191 
https://user-images.githubusercontent.com/6116378/44568827-0f0e1100-a781-11e8-88ad-306e284f3050.png
@pzakatov in this issue we are not restricting the amount of reroutes that will happen at the end of the time window. We will init a reflow for each unique flow.id (if it was requested).
Please create a separate issue for 
> add throttling to reflows, so we do not do more than Z reroutes in Y seconds

**Comment by Settis** [comment]
Please note that `FlowThrottlingBolt` has parallelism = 2 by default. For test purpose it must be reduced to 1, by changing `parallelism.new` parameter.
