### ISSUE TITLE
Associate flows and make them diverse (ie Anti-Affinity)

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1231]
example: 
Customer wants to have reduncancy on the 2 flows so they reside on different switches and/or ISLs

amount of associated flows could be more than 2

Key Use Cases:

1. Give me a path B that has no overlap with path A.
2. Give me a path B that has minimal overlap with path A (ie zero overlap preferred, followed by fewest intersection)
3. Allow grooming to take place in order to satisfy use case 1 or 2 (ie what if we moved some paths around, could that allow use case 1, or have a better story for 2)

**Comment by shusyaM** [comment]
- related flows (need to define how the relation would be calculated) should reside on different inital and reroute paths: isl and switches

**Comment by timofei-durakov** [comment]
- [ ] define model updates to build flow groups
- [ ] define API changes
- [ ] update domain model objects and DTOs, including converters
- [ ] introduce changes in WFM Flow topology(create, update, reroute)

**Comment by carmine** [comment]
I've updated the Description with the following:

Key Use Cases:

1. Give me a path B that has no overlap with path A.
2. Give me a path B that has minimal overlap with path A (ie zero overlap preferred, followed by fewest intersection)
3. Allow grooming to take place in order to satisfy use case 1 or 2 (ie what if we moved some paths around, could that allow use case 1, or have a better story for 2)

**Comment by pzakatov** [comment]
Path response example for if a flow marked as diverse
```
{
  "flowid": "flow",
  "flowpath_forward": [
    {"input_port": 12,"output_port": 1,"switch_id": "00:00:00:00:00:00:01:02"},
    {"input_port": 2,"output_port": 1,"switch_id": "00:00:00:00:00:00:01:01"}
  ],
  "flowpath_reverse": [
    {"input_port": 1,"output_port": 2,"switch_id": "00:00:00:00:00:00:01:01"},
    {"input_port": 1,"output_port": 12,"switch_id": "00:00:00:00:00:00:01:02"
    }
  ],
  "diverse_group": {
    "overlapping_segments": {
      "isl_count": 0,
      "switch_count": 2,
      "isl_percent": 0,
      "switch_percent": 100
    },
    "other_flows": [
      {
        "flowid": "diverse1",
        "flowpath_forward": [
          {"input_port": 13,"output_port": 5,"switch_id": "00:00:00:00:00:00:01:02"},
          {"input_port": 5,"output_port": 1,"switch_id": "00:00:00:00:00:00:01:03"}
        ],
        "flowpath_reverse": [
          {"input_port": 1,"output_port": 5,"switch_id": "00:00:00:00:00:00:01:03"},
          {"input_port": 5,"output_port": 13,"switch_id": "00:00:00:00:00:00:01:02"}
        ],
        "overlapping_segments": {
          "isl_count": 0,
          "switch_count": 1,
          "isl_percent": 0,
          "switch_percent": 50
        }
      },
      {
        "flowid": "diverse2",
        "flowpath_forward": [
          {"input_port": 20,"output_port": 7,"switch_id": "00:00:00:00:00:00:01:02"},
          {"input_port": 5,"output_port": 1,"switch_id": "00:00:00:00:00:00:01:04"}
        ],
        "flowpath_reverse": [
          {"input_port": 5,"output_port": 1,"switch_id": "00:00:00:00:00:00:01:04"},
          {"input_port": 7,"output_port": 20,"switch_id": "00:00:00:00:00:00:01:02"}
        ],
        "overlapping_segments": {
          "isl_count": 0,
          "switch_count": 1,
          "isl_percent": 0,
          "switch_percent": 50
        }
      }
    ]
  }
}
```
where:
- `other_flows` - other flows in this diverse group
- `isl_count` - amount of ISLs overlapped between this flow and all other in the group or a particular flow
- `switch_count` - amount of switches overlapped between this flow and all other in the group or a particular flow
- `isl_percent` - `isl_count` divided by total switches in this group or a particular flow
- `switch_percent` - `switch_count` divided by total switchesin this group or a particular flow

**Comment by IlyaMoiseev** [comment]
Implemented
