### ISSUE TITLE
As a user I'd like to create a flow with a protected path

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1232]
# Details
- a user should be able to create flows with a protected path (optionally)
- the path should be pre-calculated, reserved, and deployed (except ingress rule), so we can switch traffic fast.

# API
1. `flow` object should be extended with an integer parameter `allocate-protected-path` with values `false`(default) and `true`
2. `/flows/{flow-id}/path` should also return `protected_path'  with the protected path and its diversity factor in comparison to the primary one.

**Comment by shusyaM** [comment]
- Each flow (or will this be on deman? ) should have redundant path
- Redundant path should be pre-calculated, reserved in terms of BW
- If the firth path is down the traffic should be out on the redundant path

**Comment by IlyaMoiseev** [comment]
OpenFlow 1.3 Fast Failover solution: https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/7995427/How+to+Work+with+Fast-Failover+OpenFlow+Groups
Example code: https://github.com/rizard/fast-failover-demo/blob/solution/src/main/java/net/floodlightcontroller/fastfailoverdemo/FastFailoverDemo.java#L649
