### ISSUE TITLE
Add prefix to topology names, kafka topics

### ISSUE THREAD

**Issue by PinGwynn** [telstra/open-kilda#125]
start topics and topology names in a storm with one word, for example, kilda ?
Something like that (in storm ui):
kilda-cache
kilda-flow
kilda-islstats
kilda-stats

And in kafka topics too

The reason: when I use open-kilda in a shared environment with already existed data in zookeeper or kafka and get znode list from zookeeper and see something like 'stats', 'cache' - I can't be sure that it is for kilda, not for any other service which uses zookeeper.

And the same situation with kafka

**Comment by carmine** [comment]
This is partially fixed - all kafka topics start with kilda now.

**Comment by pzakatov** [comment]
topology name prefix is now configurable
