### ISSUE TITLE
Create gRPC client/speaker

### ISSUE THREAD

**Issue by jonvestal** [telstra/open-kilda#1264]
Some switches, Noviflow in particular, support gRPC for switch configuration.  As not all configuration options can be completed through OpenFlow a gRPC server needs to be created and act as another south bound interface for sending commands to a switch, such as logical port creation for BFD and LAG.

Scope:
1 Generic GRPC speaker deployed
2 with a message format defined
3 Kafka topics created and documented
4 Auth mechanism documented and implemented. Credentials store
5 support/validate all protobuf features 
6 respond back with all supported propobuf features

Out of scope
- User management on switches

**Comment by pzakatov** [comment]
next to FL
Jon has some gRPC command examples
Should look like a speaker
- Where should credentials be stored?

**Comment by nikitacherevko** [comment]
@jonvestal could you please share examples of gRPC commands for novi?

**Comment by nikitacherevko** [comment]
Preliminary design: 
![image](https://user-images.githubusercontent.com/6116378/46538874-c12b1380-c8bd-11e8-89b7-086f0d4a434f.png)

**Comment by nikitacherevko** [comment]
Requires noviware's version 400.6.4 and corresponding proto file.

**Comment by pzakatov** [comment]
We need to implement this in a generic way and not depend on the BFD feature.

Scope:
1 Generic GRPC speaker deployed
2 with a message format defined
3 Kafka topics created and documented
4 Auth mechanism documented and implemented. Credentials store
5 support/validate all protobuf features
6 respond back with all supported propobuf features

Out of scope
- User management on switches
