### ISSUE TITLE
Flow won't evacuate from a broken ISL if it broke while its switches were down

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1269]
The issue is that Kilda is unable to properly detect link as 'failed' and evacuate all the flows from the link if it stopped working while switches are down and it happened in less than 'discovery timeout' seconds.
Steps:
1. Create a flow
2. Pick two neighboring switches of this flow and disconnect them from controller.
3. Break the link between these two switches (bring the ISL's port down or break it via intermediate switch)
4. Bring the switches back online (connect back to controller). 
Note: Steps 2-4 should happen quicker than '${discovery.timeout}' param
**Expected:** The target ISL is FAILED. Flow is evacuated from this ISL or flow status changes to Down (if there is no alternative path to evacuate to)
**Actual:** The target ISL is FAILED, but the flow remains on that ISL. It won't attempt to reroute, leaving the flow on the broken ISL and in the Up status.
Note: The ISL will appear as 'failed' in the database, but won't be handled as 'failed' by the rest of the system.
@nikitacherevko did some investigation and can provide some more technical details on this problem.

**Comment by rtretyak** [comment]
Created a functional to verify the proper behavior (currently failing). 
Test is located on branch: issue/1269_isl_wont_fail

**Comment by carmine** [comment]
Can we get a state diagram added for ISL health checks?
