### ISSUE TITLE
Remove maven dependency duplicates and improve dependency tree

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#1271]
Some maven dependencies have duplicates. Also some of them have duplicate info (e.g. version in parent and in child dependency). It needs optimization

**Comment by niksv** [comment]
estimates: 3 days

**Comment by niksv** [comment]
PR: https://github.com/telstra/open-kilda/pull/1296

**Comment by sergii-iakovenko** [comment]
PR #1296 has been reverted due to the issue in OpenTsdb Topology. See #1389

**Comment by niksv** [comment]
At this moment Kilda uses Gradle instead maven
