### ISSUE TITLE
Evolve ATDD test stages - atdd-staging (real switches)

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#128]
Find the simplest way to apply our virtual acceptance tests (run against mininet) against real switches in some environment - ie staging. A staging environment should be able to tolerate some destructive tests (creating / deleting flows), amongst other things.

This particular environment should be able to handle a switchover from an old controller to a new controller.  In other words, one of the AT should be:

```
Given a physical topology connected to an external controller
And a set of flows that have traffic  // NB: leverage traffic gen vms
When the physical topology is connected to a kilda controller
Then it learns the topology and flows  // ensure flows go across all switches, with all flow types
And it is able to create new flows  // create additional flows of all types.
```

NB: #233 governs the flow learning / morphing process. That will be going on during the "learns topology and flows" period.

**Comment by a-ovchinnikov** [comment]
Partially addressed in https://github.com/a-ovchinnikov/open-kilda/commit/79f35b4fb87382e6c18d8fdd5d27853668bd6598
