### ISSUE TITLE
Create OpenTSDB topology

### ISSUE THREAD

**Issue by jonvestal** [telstra/open-kilda#13]
Currently every topology which needs to commit to OpenTSDB does it individually.  We would like to create a Storm Topology that listens to a Kafka topic which has pre-formatted messages and then pushes those messages into OpenTSDB only if:

1. Current datapoint <> previous datapoint
2. Previous datapoint is >= 10 mins old

**Comment by carmine** [comment]
@nikitamarchenko will tackle ..
