### ISSUE TITLE
Messaging Refactor - remove unnecessary annotations, refactor abstract classes.

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#134]
We discussed eliminating unnecessary JSON annotations on fields that don't need it (ie the names are the same).

Additionally, there are several abstract classes that don't serve a purpose .. with many subclasses. Either common functionality should be moved to the abstract base class, or the subclasses should be merged into the abstract class if the functionality isn't substantially different.

**Comment by pzakatov** [comment]
common activity. closing
