### ISSUE TITLE
Negative available bandwidth on ISL's

### ISSUE THREAD

**Issue by jonvestal** [telstra/open-kilda#1345]
Carmine thinks this is a race-condition on the commit to Neo4J.

**Comment by Levitan** [comment]
Not a bug.
After first Flow Reroute, database does not have time to take a consistent state. And for next reroutes send response with not valid data. 

@surabujin spoke this was fixed after implementation DAO, and transition to H&S

**Comment by rtretyak** [comment]
> Not a bug.
The fact that our system is unable to easily deal with this race condition does not mean that this is not a bug. System should not allow such ISL oversubscription and this defect is pretty severe.

**Comment by rtretyak** [comment]
Not reproducing anymore. Will merge the related test to develop for the future regression testing.
