### ISSUE TITLE
Sign payload of Verification Packet

### ISSUE THREAD

**Issue by jonvestal** [telstra/open-kilda#14]
Need to sign the payload of a verification packet when the controller sends it to the ingress switch such that when returned to the controller we can verify it is our verification packet and not someone else.

**Comment by carmine** [comment]
Assigned to Nikita

**Comment by nikitamarchenko** [comment]
I propose to use [JSON Web Tokens](https://jwt.io/introduction/) with [net.floodlightcontroller.packet.LLDPOrganizationalTLV](https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/packet/LLDPOrganizationalTLV.java).

@carmine @jonvestal any objections?

**Comment by carmine** [comment]
Looks like a reasonable design choice.

**Comment by nikitamarchenko** [comment]
https://gist.github.com/nikitamarchenko/d88527cb23f11c8027cc93cbb2e7e97e
