### ISSUE TITLE
Move switch (de)activation logic out of Floodlight

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1417]
Now on switch "(de)activaion" FL make several "decisions" and possible do some actions (setup "default rues" in usual way or using "safe mode").

To keep FL just OF speaker we should extract this logic into one of storm topology("event" is most obvious). 

Proposed workflow - FL must produce event "switch activate" and wait commands. "event" topology must make all required decisions and produce set of commands aimed to initialize switch - setup/remove all required rules, configure all required ports and so on.

It will allow to collect all switch management logic in one "point" and as a bonus it will remove switch management "logic" from FL.

**Comment by niksv** [comment]
now network topology is responsible for switch activation
