### ISSUE TITLE
Do switch validation/sync on switch activation

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#1424]
Currently we have to perform manually validations and synchronizations of switches from time to time, because there is always a possibility to get excess rules and meters. 

We can add a functionality on switch activation to install missing rules and meters ("switch sync"), that should help to keep on switches required rules and meters.

**High level diagram**
![highlevel](https://user-images.githubusercontent.com/1427656/48950569-e4785380-ef3b-11e8-9255-f9626588d9ba.png)
We can extend our Event topology for aggregate "Switch is active" events via Throttling bolt. Because sometimes Event topology can receive the same "Switch is active" event twice. After aggregation Throttling bolt send "Validate/Sync rules" command to Kafka. It's not clear who will read and apply the command.

**Current Validate/Sync rules implementation**
![currentsync](https://user-images.githubusercontent.com/1427656/48950576-e9d59e00-ef3b-11e8-8f1e-b8561dd7d0fa.png)

**Propose Validate/Sync rules implementation**
![h ssync](https://user-images.githubusercontent.com/1427656/49107002-e7997980-f284-11e8-9d3c-8270af4844a1.png)
It can be implemented on top of H&S. Because we must run a lot of commands on Floodlight.

**Comment by nikitamarchenko** [comment]
@nikitacherevko I am waiting for detail diagrams for that.

**Comment by Settis** [comment]
Description was updated with High level proposal and diagram about current Validate/Sync implementation.

**Comment by dpoltavets** [comment]
This issue was solved by #2738.
