### ISSUE TITLE
Tests: add tests for flow/rules validation

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1438]
1. test positive scenarios for valid flows
2. try breaking rules/flows and verify that validation reports certain issues

**Comment by rtretyak** [comment]
Completed step 1 for positive scenarios. Reassign to @npliashechnikov for implementing negative scenarios (p.2)

**Comment by rtretyak** [comment]
related to #1478

**Comment by npliashechnikov** [comment]
Implemented negative test cases
