### ISSUE TITLE
Allow Path Computation to exclude a given graph

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1451]
Add ability to exclude a given graph from path computation algorithm. 
Exclusion graph could be:
- an ISL
- a switch
- a path (set of Switches and ISLs)

Scope:
- create a design
- implement it :)

Next tasks: 
- #1231 associate flows and make them diverse
- #1232 Introduce a concept of a backup path

Possible use-cases:
- Calculate a diverse path
- Evacuate flows from ISL/Switch (reroute with exclude)
- Allow user to specify exclusion list from API

**Comment by IlyaMoiseev** [comment]
Closed because another way of graph manipulation will be used in dependent tasks
