### ISSUE TITLE
Get rid from "reply-to" message field

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#1455]
In addition to our usual routing scheme (handler know where to put response) we have a messages with "reply-to" field. This field contain name of topic that should be used for response.

It increase complexity of all handlers involved in processing such messages. Also it mixes different routing approaches.

All current workflows that produce messages with "reply-to" field set must be updated. Extra data types should be created to eliminate the need of "reply-to" value.

**Comment by surabujin** [comment]
Required for #650

**Comment by Levitan** [comment]
Complete by PR #1534
