### ISSUE TITLE
Support OpenJDK 8 or upgrade to 11

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#1462]
Kilda utilizes Oracle JDK 8 in the build pipeline and on different environments, but according to [Oracle Java Support Roadmap](https://www.oracle.com/technetwork/java/eol-135779.html) it's approaching the end of public updates. So we need to investigate and either implement support of OpenJDK 8 or upgrade to Java 11.

Known issues:
- Apache Storm is not ready for Java 11. https://issues.apache.org/jira/browse/STORM-2798

See https://docs.google.com/document/u/1/d/1nFGazvrCvHMZJgFstlbzoHjpAVwv5DEdnaBr_5pKuHo

**Comment by pzakatov** [comment]
Options:
- (try first) OpenJDK8
- License for OracleJDK8
- (preferred) use OpenJDK11

**Comment by sergii-iakovenko** [comment]
Closing as currently Kilda runs on OpenJDK8 with no issues.
