### ISSUE TITLE
Single-switch flow remains in 'Up' status after knocking the switch out

### ISSUE THREAD

**Issue by ylobankov** [telstra/open-kilda#1464]
**Environment:**
Virtual network topology with one active switch at least.

**Steps to reproduce:**
1. Create a single-switch flow (the flow where the source and destination switches are the same).
2. Knock the switch out via mininet service.
    POST http://localhost:17191/knockoutswitch?switch=<switch_name>

**Expected result:**
The flow goes to 'Down' status.

**Actual result:**
The flow remains in 'Up' status.

**Comment by IlyaMoiseev** [comment]
Blocked by pre Hub-and-Spoke
