### ISSUE TITLE
Flow total cost overflow if ISLs have very expensive costs (near to 2^31)

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#1527]
**Environment:**
Triangle topology with two very expensive ISLs and one cheap ISL.
For Example:
A-----2 000 000 000 -----B-----2 000 000 000-----C
\\-------------------------------1------------------------------/

**Steps to reproduce:**
1. Set costs for A->B and B->C ISLs to 2 000 000 000
2. Set A->C ISL cost to 1.
3. Create a flow between A and C

**Expected result:**
Path will be A->C because its cost is 1.

**Actual result:**
Path will be A->B->C because (2 000 000 000 + 2 000 000 000) % 2^32 = -294967296

**Comment by rtretyak** [comment]
Looks like related to #1153
