### ISSUE TITLE
Meters support in switch validation

### ISSUE THREAD

**Issue by Settis** [telstra/open-kilda#1551]
Current implementation
===================
Currently we have `/{switch_id}/rules/validate` API which validates only rules on the switch.

What needs to be done
==================
We also interested in checking meters on the switch.

Proposal
=======
Add new API path `/{switch_id}/validate`. That call will validate rules and meters and make the following response:
```
{
  "rules": {
    "missing": [<cookie>],
    "excess": [<cookie>],
    "proper": [<cookie>]
  },
  "meters": {
    "missing": [ {
        "meterId": 28,
        "cookie": <cookie>,
        "flowId": "foo"
      }
    ],
    "misconfigured": [ {
        "meterId": 32,
        "cookie": <cookie>,
        "flowId": "foo",
        "actualRate": 100,
        "expectedRate": 200
      }
    ],
    "excess": [ {
        "meterId": 15
      }
    ],
    "proper": [ {
        "meterId": 30,
        "cookie": <cookie>,
        "flowId": "foo"
      }
    ]
  }
}
```

Subtask of #1249

**Comment by surabujin** [comment]
We definetely should have "rate" and "burst" and rate/burts fields in meter's "missing", "extra" and "proper" groups.

It can be useful to define meter "object" and put it in all groups e.q:
```
"proper": {
    ...
    "meter": {
        "id": 1,
        "rate": 1000,
        "burst": 10,
        "unit": "kbps"
    },
    "flow": {
        "id": "flow-id",
        "cookie": 100500
    }
}
```
in other words provide all available info.

PS It can lead to overflow of kafka package size. :(
