### ISSUE TITLE
Traffgen sometimes reports no connection for virtual environment

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1555]
We are trying to run traffic examination on virtual topology spawned by LabService (#1435 ) and from time to time receive response 
```
{
  "report" : {
    "intervals" : [ ],
    "error" : "error - unable to connect to server: Connection refused",
    "end" : { },
    "start" : {
      "version" : "iperf 3.0.11",
      "connected" : [ ],
      "system_info" : "Linux 65328159236d 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux\n"
    }
  },
  "error" : "",
  "status" : 1
}
```

**Steps to reproduce:**
1. Build kilda from labservice branch
2. Run functional test: FlowCrudSpec#Valid flow has no rule discrepancies
You may need to run it multiple times in order to reproduce the issue.
We also noticed that for virtual env during successful trafexams all the traffic is exhausted in the first 'interval', leaving all subsequent intervals with 0 bytes(not an actual issue, but this behavior is different from hardware topology)
Need help on fixing the trafexam instability.

**Comment by rtretyak** [comment]
Adding a 500ms sleep between creating consumer and producer seem to have positive effect. Wasn't able to reproduce the issue in multiple runs

**Comment by pzakatov** [comment]
@rtretyak  please close issue if no longer reproducible

**Comment by rtretyak** [comment]
We went for the minor 'sleep' option on the tests side, which is a little bit dirty, but currently works fine.
Closed
