### ISSUE TITLE
Make northbound async

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1562]
Problem
Due to the async nature of Kilda, sometimes it is hard to respond synchronously to an external user. Current approach increases the complexity of the NB as well (converting async internal communications to synchronous external one).

Proposal
For every request, we respond with a token
A client can get the result using special "GET <NB>/result/<token>" API

Pros
- Simplify NB logic (avoid sync-async translation)
- Will allow us to not keep connections open for long-running operations

Cons
- each user request will be (at least) in two parts: 
-- 1. make a request
-- 2. get the result

**Comment by carmine** [comment]
Given the current nature of NB and how responses are defined, this could be complicated. Most/all responses define the exact response *type*. This feature would require a generic response type - it could be JSON - and the user would then have to parse the type.

It is doable, but we won't be able to do the static type checking per se.
