### ISSUE TITLE
Put STATS flag for all meters and collect this stats to OTSDB

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1573]
http://flowgrammable.org/sdn/openflow/message-layer/metermod/

**NOTE: We assume that each meter has only one meterBand.**

There two types of meters on switch at this moment:
1. Meters for flows.
2. Meters for default rules.

**Metrics for flows:**

- pen.flow.meter.bits        - meterBand bits
- pen.flow.meter.bytes     - meterBand bytes
- pen.flow.meter.packets - meterBand packets

Tags: cookie, switchid, flowid, direction, meterid

**Metrics for default rule meters:**

- pen.switch.flow.system.meter.packets - meterBand packets
- pen.switch.flow.system.meter.bytes     - meterBand bytes
- pen.switch.flow.system.meter.bits        - meterBand bits

Tags: cookieHex, switchid, meterid

**Comment by pzakatov** [comment]
@niksv, please make a change to metermod with stats flag enabled as a separate PR ASAP.

**Comment by surabujin** [comment]
@pzakatov 
> Tags: cookie (in Hex), switchid, meterid

It breaks current stats representation - now tag "cookie" store cookie value in decimal(signed long) representation.

As for me it is better to make 2 tags - `cookie` for decimal representation and `cookieHex` for hex representation (If we accept this "format" we should add "cookieHex" tag for all other records with "cookie" tag).

**Comment by pzakatov** [comment]
> As for me it is better to make 2 tags - `cookie` for decimal representation and `cookieHex` for hex representation (If we accept this "format" we should add "cookieHex" tag for all other records with "cookie" tag).

Ok. Let it be 2 tags
