### ISSUE TITLE
Install rules won't respond that it installed DROP_LOOP_RULE

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1602]
Steps:
1. Work with OF_13+ switch
2. drop all rules from the switch (including defaults)
3. call 'install rules' operation for that switch (install default rules `PUT api/v1/switches/$swId/rules`).

**Expected:** Response reports that 4 default rules are installed:
```
[
    -9223372036854775807,
    -9223372036854775806,
    -9223372036854775805,
    -9223372036854775804
]
```
**Actual:** Response contains 3 default rules:
```
[
    -9223372036854775807,
    -9223372036854775806,
    -9223372036854775805
]
```

Note that in fact the `-9223372036854775804` rule is actually installed on the switch

**Comment by niksv** [comment]
Problem was fixed. Tested on https://github.com/telstra/open-kilda/releases/tag/v1.86.0

```
$ curl -X PUT -u kilda:kilda "http://localhost:8080/api/v1/switches/2/rules" -H "accept: */*" -H "EXTRA_AUTH: 1614946950340"
[-9223372036854775807,-9223372036854775806,-9223372036854775805,-9223372036854775804,-9223372036854775783]
```
