### ISSUE TITLE
InstallRulesAction is missing INSTALL_DROP_LOOP flag

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1604]
Since we have added a new DROP_LOOP_RULE, the `org.openkilda.messaging.command.switches.InstallRulesAction` should have a new flag for installing DROP_LOOP_RULE (in order to be consistent with other default rules).
Also, 'install rules' endpoint should be taught to handle this flag and install drop loop rule only

**Comment by niksv** [comment]
Closed by https://github.com/telstra/open-kilda/pull/2686

Now user is able to install Drop loop rule by `INSTALL_DROP_VERIFICATION_LOOP` flag

```
$ curl -X PUT -u kilda:kilda "http://localhost:8080/api/v1/switches/2/rules?install-action=INSTALL_DROP_VERIFICATION_LOOP" -H "accept: */*" -H "EXTRA_AUTH: 1614947396633"
[-9223372036854775804]
```
