### ISSUE TITLE
Several issues with dumping and displaying switch rules via Northbound

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1605]
Issues with `GET /api/v1/switches/$swId/rules` endpoint
- [ ] Issue 1
- [ ] Issue 2
### Issue 1
NB response is not showing the `$.flows.match.eth_src` field (though `eth_dst` is displayed correctly). The problem can easily be observed for the '-9223372036854775804' rule. Compare the floodlight original response from `/wm/core/switch/$swId/flow/json` and the NB response for that rule
### Issue 2
NB response is not correctly showing the `$.flows.instructions.none` field for cases when it has `"drop"` value. The problem can be observed for the '-9223372036854775804' rule by comparing original FL response and NB response.

**Comment by IlyaMoiseev** [comment]
Second issue is not a bug. Flows instruction serializer has this weird rule for empty case: [link](https://github.com/kilda/floodlight/blob/fcbe77b41ac09901e2fb832400966b3a348fb225/src/main/java/net/floodlightcontroller/core/web/serializers/OFInstructionListSerializer.java#L41). And that is foreign code.
By the way, we have our custom endpoint for this functionality: `/wm/kilda/flows/switch_id/$swId`
