### ISSUE TITLE
Set meter burst as 10% of requested rate 

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1671]
new config options:
- flow-meter-burst-coefficient - This coefficient is used to calculate burst size for flow meters. Burst size will be equal to 'coefficient * bandwidth'. Value '0.1' means that burst size will be equal to 10% of flow bandwidth.
- flow-meter-min-burst-size-in-kbits - Minimum possible burst size for flow meters. It will be used instead of calculated flow meter burst size if calculated value will be less than value of this option. 
- system-meter-burst-size-in-packets - This is burst size for default rule meters in packets.

**Comment by rtretyak** [comment]
@pzakatov do we need to add burst to default meters?

**Comment by niksv** [comment]
@rtretyak Yes, Pavel said that we need to do it for default meters too.

**Comment by rtretyak** [comment]
Reopen.
Testing results:
- flow-meter-burst-coefficient - OK
- flow-meter-min-burst-size-in-kbits - Not respected at all. For flow with 500kbps rate I get 502 burst, for flow with 1000kbps rate I get 1004 burst. Expected 500kbps OR 1000kbps rate = 1024kbps burst
- system-meter-burst-size-in-packets - FAIL. Meters with 200pktps rate get a 200 burst. Expected: 4096 pktps burst for any default meter

**Comment by rtretyak** [comment]
Noviflows won't allow burst to be higher than 1.005 of rate size. Since the won't return error and silenty reduce passed burst to allowed value, decided to leave current implementation as is

**Comment by rtretyak** [comment]
Issue to be fixed: centec switches have some upper boundary for the burst, which is quite low (e.g. won't allow 40000). Didn't have time to investigate the exact limit, decided to go with solution for hardcoding maximum burst for Centec switches at around 4000
