### ISSUE TITLE
The kafka topic 'kilda-test' is overly used, potentially causing endless loops

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#17]
At present, kilda-test is used heavily for message passing.

A more clear / direct set of topics and how messages flow should be identified and implemented.

This will require a information map that shows who is listening to what and who is pushing where.

- [x] Day 1. analyze WFM topologies to trace kafka producers and cosumers
- [x] Day 2. analyze other kilda components to find out kafka producers and consumers
- [x] Day 3. trace and document all kilda operations to find out all used components and "transports"
- [x] Day 4. documentation of kilda operations and their interaction

Move to separate ticket:
- finish trace and document all kilda operations
- refactor kafka usage - make more obvious data streams inside kilda
- check and eliminate any side effects of refactoring

**Comment by nikitacherevko** [comment]
I guess this investigation will take about 2 days if refactoring is not in scope

**Comment by nikitamarchenko** [comment]
With map 2.5d

**Comment by surabujin** [comment]
Vote for 2 days.

**Comment by surabujin** [comment]
The documentation is not finished yet. Should I continue to work on it in this task(because 0.7 milestone is over)? Or should I split out this task and complete it in new one?
