### ISSUE TITLE
Burst size > 32000 Kbit is not supported by Centec switches

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#1700]
According to issue #1671 we need to be able to change burst size. Default burst size is 105% of bandwidth. 
But Centec switches support only 32 Mbit busrt size. It causes errors for bandwidth > 32 Mbits. 
We need to handle this case.

**Comment by npliashechnikov** [comment]
I guess it is fixed now by limiting burst to 1024 kbit/s?

**Comment by niksv** [comment]
@npliashechnikov limiting yo 1024 kbit/s is a hotfix. We still need to fix this bug in future
