### ISSUE TITLE
STORM: Got fetch request with offset out of range

### ISSUE THREAD

**Issue by PinGwynn** [telstra/open-kilda#171]
After kafka offset was broken (topic deleted and recreated or something similar) I have millions of messages in storm workers log:

{"timeMillis":1515585602185,"thread":"Thread-7-cache-storm-topologyHealthCheckKafkaSpout-executor[8 8]","level":"WARN","loggerName":"org.apache.storm.kafka.KafkaUtils","message":"Partition{host=hadoop03:6667, topic=kilda.health.check, partition=0} Got fetch request with offset out of range: [398041]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":45,"threadPriority":5}

It looks like storm topology tries to get the message from kafka infinitely.

In this post at stackoverflow described very similar issue: https://stackoverflow.com/questions/40267518/kafka-storm-spout-got-fetch-request-with-offset-out-of-range

**Comment by pzakatov** [comment]
outdated
