### ISSUE TITLE
As an Operator I want to mark/unmark switch as Under maintenance

### ISSUE THREAD

**Issue by shusyaM** [telstra/open-kilda#1713]
Scope:

Create API for mark/unmark "under-maintenance" flag for the switch.
If "under-maintenance" flag is set to True:
- all events from this switch should be ignored
- all events from the ISLs terminated on this switch should be ignored
- all evenrts from the switches connected to ISLs that are terminated on the switch with the flag should be ignoted

**Comment by surabujin** [comment]
Connected with #1343.

Refcatored variant is going to be able to "disable" separate switch port from discovery process. It can be extended to disable whole switch.

**Comment by dpoltavets** [comment]
API to set/clear "under_maintenance" flag for switch: #1883.

**Comment by dpoltavets** [comment]
Instead of `all evens from the switches with the flag should be ignoted`, we decided that it would be enough to mark the isl associated with the switch with the" under_maintenance "flag.

**Comment by ylobankov** [comment]
Closed by #1961.
