### ISSUE TITLE
Anti-flap for port down/up

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1729]
# Problem
Sometimes port with ISL on it bouncing within a short period of time which is not a real problem. We initiate ISL_down immediately.

# Proposal
Implement similar antiflapping approach as for reroute. Introduce a logic where we wait for a "Port UP" event after a "Port Down" for "throttling_delay_seconds_min" seconds. if the last event in a series is "UP", then do not initiate "ISL_Down".

# Details 
The bolt has states: `Nothing`, `WarmingUp`, and `CoolingDown` for each port.
Initially, the bolt has state `Nothing`.
If the bolt receives "Port Up" in `Nothing` state it must emit "Port Up" without state change.
If the bolt receives "Port Down" in `Nothing` state it changes state to `WarmingUp`.
If the bolt does not receive "Port Up" after `delay_seconds_min`, it emits "Port Down" event and goes to `CoolingDown` state.
If In `CoolingDown` state the bolt receives event, it calculates current port state and restarts `seconds_cool_down` timer. 
After `seconds_cool_down` of not receiving any events, state changes to `Nothing`. If the current port state is Up the bolt emit "Port Up" event.

In case with `WarmingUp` state, when delays between every "Port Down" / "Port Up" were less then `delay_seconds_min` and the last "Port Down" / "Port Up" event was during last `delay_seconds_min` period of `delay_seconds_warm_up,` the bolt emit "Port Down" event and go to `CoolingDown` state.

Defaults should be:
- kilda_port_up_down_throttling_delay_seconds_min: 1
- kilda_port_up_down_throttling_delay_seconds_warm_up: 2
- kilda_port_up_down_throttling_delay_seconds_cool_down: 5

**Comment by nikitamarchenko** [comment]
![fsm](http://www.plantuml.com/plantuml/png/XP31IiGm48RlUOev2_i2Uv05FSk2B1vKGcX66qXcGZAb57nufxKjDHuyTJhv_Y-PkLHnHOOKJHyy0gOi4tYiNGbP0fDvlNk7q-aUdbZwG9zc_HvxPs22AnUvPHK4MUjVw8ihIUjRtk577idixGLwO8xwDv_06S874F-uhl16SyvZT9Ejs37vQZMvtVU_xczyLDWEkL4SGgtaCEVNnkl32YuxXCtRQSBwrjNkgwLdaqwSkSYpE4485PfzNf3yaE8t)
[fsm](http://www.plantuml.com/plantuml/png/XP31IiGm48RlUOev2_i2Uv05FSk2B1vKGcX66qXcGZAb57nufxKjDHuyTJhv_Y-PkLHnHOOKJHyy0gOi4tYiNGbP0fDvlNk7q-aUdbZwG9zc_HvxPs22AnUvPHK4MUjVw8ihIUjRtk577idixGLwO8xwDv_06S874F-uhl16SyvZT9Ejs37vQZMvtVU_xczyLDWEkL4SGgtaCEVNnkl32YuxXCtRQSBwrjNkgwLdaqwSkSYpE4485PfzNf3yaE8t)
