### ISSUE TITLE
[Kilda-Gui] Get all flows for an ISL

### ISSUE THREAD

**Issue by hiteshgupta1** [telstra/open-kilda#1741]
Get all flows for an ISL
- Display list of flows in isl detail screen for that isl
- Provide a facility to re-route  one or multiple flows from ISL screen

**Comment by pzakatov** [comment]
@hiteshgupta1 you could reuse #609 `New API: Reroute all flows which go through a particular ISL` once it will be released for "reroute all flows on ISL" feature if needed.

**Comment by neeraj890kumar** [comment]
Acknowledged
