### ISSUE TITLE
Port-antiflap sometimes brings port down too early

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1790]
Port-antiflap brings the port down at the end of `kilda_port_up_down_throttling_delay_seconds_min` instead of after `kilda_port_up_down_throttling_delay_seconds_warm_up` in cases when the last port state during `kilda_port_up_down_throttling_delay_seconds_min` 'check' was DOWN  
Steps:
1. Start blinking certain port
2. Before `kilda_port_up_down_throttling_delay_seconds_min` timeout runs out the port state should end up in 'DOWN' state, but the port should continue to 'flap'
**Expected:** Port remains 'UP' until `kilda_port_up_down_throttling_delay_seconds_warm_up` timeout runs out
**Actual:** Port changes to 'DOWN' right after `kilda_port_up_down_throttling_delay_seconds_min` despite port still being unstable.

**Comment by pzakatov** [comment]
Related to #1729
