### ISSUE TITLE
Evolve PCE with weights computation strategies

### ISSUE THREAD

**Issue by IlyaMoiseev** [telstra/open-kilda#1820]
For now PCE uses only `cost` field as graph edges weights

While path computing logic going to be more complicated - we need to take several factors\costs to compute final edge\node weight, and keep this things maintainable

**Comment by carmine** [comment]
Refactor or evolve?

**Comment by carmine** [comment]
Can we get a concrete example of a weights strategy that we want to put into place?

Arguably, if there is some other numeric field / attribute that we'd like to use, the method signature could change (ie pass in the attribute to use).  If it is more complex, and not calculated a prior, then pass in a function / object.

**Comment by IlyaMoiseev** [comment]
Signature will be `int getFinalCost(Edge edge)`. Initially it will simple calls `getCost` getter. In near future, after implementing maintenance and diverse features, it going to be sum of 4-5 cost numbers, what is arguable.

I think all needed attributes will be accessible from Edge instance. AvailableNetwork graph will be linked, and Edge instance may considered as graph entrypoint. But hope in strategy we will only look at source and dest edge switches, and don't needed to unwind it deeper.
