### ISSUE TITLE
Port-antiflap leaves port down even after UP event

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#1827]
Port-antiflap leaves a port down even if FL receives UP event as the last one.

Steps to reproduce:
- Start blinking a port. 
- The port goes into the cooling down state. Event topology receives DOWN event.
- During the cooling down state, stop blinking with UP as the last event. Hint: the previous DOWN event must comes to FL with the same timestamp in the log.
- Wait until the cooling down state is over for the port.

Expected: 
- Event topology receives UP event.

Actual:
- PortEventThrottlingService registers DOWN event as the last and doesn't forward UP to Event topology.

**Comment by sergii-iakovenko** [comment]
Related to #1729

**Comment by rtretyak** [comment]
Test reproducing the issue available here: #1835 
Please unignore when committing a fix

**Comment by rtretyak** [comment]
Tested in #1835 
Fixed by #1738 #1705 and #1855
