### ISSUE TITLE
Refactor TopologyDefinition to store ISLs in both directions

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1852]
below needs to be groomed. Should we explicitly describe ISLs in both directions in topology.yaml instead?

As a QA engineer, I want my framework to store ISLs in both directions similar to actual Kilda system, so that I don't have to reverse(mirror) those ISLs all the time, eliminating accidents when one forgets to perform the 'mirror' operation, as well as reducing coding efforts.
AC:
- TopologyDefinition class should automatically create reversed copies of all ISLs that are configured in topology.yaml file
- Add 'bidirectional' boolean property for ISLs in topology.yaml. If explicitly set to 'false', do not automatically create reversed copy of ISL. Set to true by default (if property is not set)
- Refactor all existing tests to respect the new ISL logic

**Comment by niksv** [comment]
now now labservice creates ISLs from topology.yaml in both directions https://github.com/telstra/open-kilda/pull/1435
