### ISSUE TITLE
Move to Semantic Versioning 2.0.0

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#1853]
I propose to move from versioning `<major>.<minor>.<month>.<day>` to [Semantic Versioning 2.0.0](https://semver.org/).

**Comment by carmine** [comment]
And keep in mind the finer point .. Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by pzakatov** [comment]
Done
