### ISSUE TITLE
Functional tests for flow pings fail very often on CI

### ISSUE THREAD

**Issue by ylobankov** [telstra/open-kilda#1865]
Lately, we observe a very strange behavior of one of the tests for flow pings  (Flow ping can detect a broken path). This test fails very often when running functional test suite against various PRs on our CI system. QA team conducted some investigation and found no issues from its side (tests, lab service, etc). So now we can assume that PR #1656 might cause the issue. It is needed detailed investigation and probably reworking the mentioned PR.

**Comment by rtretyak** [comment]
Removed the Ignore in PR #2317. Rerunning the suite multiple times to ensure its stability

**Comment by rtretyak** [comment]
build seems fine. original cause of issue remain unknown
