### ISSUE TITLE
Add ability to pass additional mvn commands to all-in-one test runner. Remove atdd

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1868]
As a QA engineer, I want to have ability to pass additional mvn commands to the build command of all-in-one-tests job, so that I can, for example, run certain single test on demand.
Also remove the ability to run 'atdd' tests, since atdd module is about to be removed.
AC:
1. all-in-one-tests job now only runs 'functional' tests
2. it has a text field for passing additional mvn params (text will be appended to the end of the original mvn command)

**Comment by ylobankov** [comment]
Resolved by https://phabricator.pacnetconnect.com/D21010.
