### ISSUE TITLE
Incorrect error message when building a flow with DEACTIVATED switch as src/dst

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1909]
1. Given: topology with a deactivated switch
2. Try building flow, where deactivated switch is used as src or dst
**Expected:** Error response with status code 400, reading `Could not create flow: Source(Destination) switch $swId is not connected to the controller`
**Actual:** Error response with status code 404, reading `Could not create flow: Not enough bandwidth found or path not found ....`

**Comment by niksv** [comment]
Fixed by https://github.com/telstra/open-kilda/pull/2395
