### ISSUE TITLE
Unmetered flow with saved meter 0 causes "Failed to delete meter 0" errors

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#1919]
Unmetered flow created and stored before #1766 has been fixed, causes ```Failed to delete meter 0 from switch ...: Meter id must be positive.``` error on deletion or rerouting.

**Comment by IlyaMoiseev** [comment]
Query to fix this in DB: `match (:switch)-[f:flow]->(:switch) where (f.ignore_bandwidth AND f.bandwidth=0 AND exists(f.meter_id)) remove f.meter_id`

**Comment by IlyaMoiseev** [comment]
Updated variant (result should be the same): `match (:switch)-[f:flow]->(:switch) where (f.ignore_bandwidth AND f.bandwidth=0 AND f.meter_id=0) remove f.meter_id`

**Comment by niksv** [comment]
request LGTM

**Comment by nikitamarchenko** [comment]
lgtm

**Comment by nikitacherevko** [comment]
We've executed the query provided by @IlyaMoiseev. Looks like we resolved the issue and it can be closed
