### ISSUE TITLE
Recheck whether ISLMovement test is working correctly

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1928]
Debug IslMovementSpec#New ISL is not getting discovered when replugging into a self-loop (same port) and check whether self-loop ISL indeed get simulated. I have doubts because drop rule package counter was not increasing when I checked. Need recheck. Note that the 'different port' neighboring test works as expected

**Comment by ylobankov** [comment]
Investigation showed that the test works correctly in a hardware env. In a virtual env, the drop rule package counter is indeed not increasing, unlike the hardware env.
