### ISSUE TITLE
[BUG] - Transaction Logic - There is a possibility to create flow with only reverse path

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#193]
Action Items:
[ ] - Fix the WFM / Transaction manager around creates and deletes on flows to help prevent this situation. 
[ ] - Make flow cleanup more resilient, so that directly modifying the DB isn't necessary. This means looking at the flow of a delete request and ensure that it could delete a flow if it only exists partially.

----

We've got a flow in neo4j with only reverse path and when topology engine sends all flows to WFM_CACHE it makes cache topology broken because CacheBolt expect forward path to add it to cache, therefore NPE is occurred. Stacktrace is provided below:
```
{
  "file": "FlowCache.java",
  "method": "buildFlow",
  "line": 434,
  "exact": false,
  "location": "stormjar.jar",
  "class": "org.openkilda.pce.cache.FlowCache",
  "version": "?"
},
{
  "file": "CacheBolt.java",
  "method": "emitRestoreCommands",
  "line": 419,
  "exact": false,
  "location": "stormjar.jar",
  "class": "org.openkilda.wfm.topology.cache.CacheBolt",
  "version": "?"
},
{
  "file": "CacheBolt.java",
  "method": "handleNetworkDump",
  "line": 279,
  "exact": false,
  "location": "stormjar.jar",
  "version": "?",
  "class": "org.openkilda.wfm.topology.cache.CacheBolt"
},
{
  "file": "CacheBolt.java",
  "method": "doWork",
  "line": 192,
  "exact": false,
  "location": "stormjar.jar",
  "class": "org.openkilda.wfm.topology.cache.CacheBolt",
  "version": "?"
},
{
  "file": "AbstractTickStatefulBolt.java",
  "method": "execute",
  "line": 83,
  "exact": false,
  "location": "stormjar.jar",
  "version": "?",
  "class": "org.openkilda.wfm.topology.utils.AbstractTickStatefulBolt"
}
```

More information of network state is available at [kibana](https://kibana.sirius.pn.telstra.com:5601/app/kibana#/dashboard/244539f0-f20e-11e7-9052-7bb5aee88040?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'kilda-*',key:query,negate:!f,type:query_string,value:'tags:%20%22kilda-tpe%22'),query:(query_string:(analyze_wildcard:!t,query:'tags:%20%22kilda-tpe%22'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'kilda-*',key:'@timestamp',negate:!f,type:phrase,value:'January%2018th%202018,%2015:11:25.204'),query:(match:('@timestamp':(query:1516281085204,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:'0dbf2e70-f209-11e7-9052-7bb5aee88040',panelIndex:1,row:1,size_x:6,size_y:3,type:visualization),(col:7,id:bd994530-f16c-11e7-a202-e79f0134df49,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:1,id:'2489ab10-f210-11e7-9052-7bb5aee88040',panelIndex:3,row:4,size_x:12,size_y:3,type:visualization),(col:1,columns:!(app_id,level,message),id:fa81a1f0-f229-11e7-9f55-7bb8fa2a1bf7,panelIndex:4,row:7,size_x:12,size_y:8,sort:!('@timestamp',desc),type:search)),query:(query_string:(query:'message:%20%22WFM_CACHE%22')),timeRestore:!f,title:KILDA-Dashboard,uiState:(P-2:(vis:(params:(sort:(columnIndex:!n,direction:!n))))),viewMode:view))

**Comment by carmine** [comment]
I've updated the title to reflect that the WFM for flow creation / deletion needs to be fixed such that this scenario is handled appropriately.

Also, adjusting the description to ensure we can delete partially created flows .. ie make delete lenient if some non-essential things don't exist.

**Comment by pzakatov** [comment]
outdated
