### ISSUE TITLE
Ability to edit/override maximum bandwidth on an ISL

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1937]
There could be a case when underlying service provides lower bandwidth than reported by a port speed. In that case, we need to have the ability to override max bandwidth on the ISL.

API: `PATCH /links?<link params>` and `max_bandwidth` in the body

**Comment by pzakatov** [comment]
@Levitan please note that `available_bandwidth` is not updating as a part of current "bandwidth update" operation, but it should. So, please fix this as well as a part of this ticket.

**Comment by Levitan** [comment]
Need add in this issue:
- Add calculation available bandwidth after update maximum bandwidth
- Add link props for reverse path

**Comment by surabujin** [comment]
@pzakatov we need new API endpoint or we can use existing `PUT /api/v1/link/props` here?

PS It already capable to set `max_bandwidth. But still it's behaviour should be altered to perform extra required steps (alter `available_bandwidth` etc).
