### ISSUE TITLE
Investigate Topology Health Check design and implementation.

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#197]
Ensure the design and implementation is simple, elegant, well tested.

The basics should be covered:
(1) Healthy elements show up as healthy
(2) Unhealthy elements show up as unhealthy
(3) We follow policies regarding how we determine healthy / unhealthy
(4) We can easily report on the healthy / unhealthy / **flapping** elements
(5) We have policies for flapping elements - ie how to treat those.

Each layer we add to the initial / raw check should be like a pipeline of filters.

**Comment by IlyaMoiseev** [comment]
Fixed in #1357
