### ISSUE TITLE
Stats subsystem can't handle exceptions

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1976]
Concern: stats may completely break given we receive some kind of exception without producing an error log message.
Steps:
1. For example: try sending meterStatsRequest to OF_12 switch

**Expected:** system logs an error. Stats subsystem handles exception and continues to work for other switches (non OF_12)
**Actual:** No errors in logs. Stats silently stop working for the whole set of switches

**Comment by niksv** [comment]
Fixed by #1979
