### ISSUE TITLE
Unable to set meters with kbps flag on noviflow switch with "E" manufacturer

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2010]
Trying to create a flow with Noviflow switch with "E" manufacturer as a src/dst switch leads to a meter error, leading to inability to install an ingress rule.
Error info:
```
OFMeterModFailedErrorMsgVer13(xid=99402, code=BAD_FLAGS, data=OFMeterModVer13(xid=99402, command=ADD, flags=[KBPS, BURST, STATS], meterId=32, meters=[OFMeterBandDropVer13(rate=500, burstSize=1024)])) from switch OFSwitch DPID[00:00:00:90:fb:64:cd:4a] in state net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$MasterState@2b553e48
```
Switch info:
`"description": "E OF_13 NW400.6.4"`

Investigation:
1. Tried to install meter directly on 'E' switch the way Kilda tried to install it, resulted in error
```
ofsw10_lon# set config meter meterid 10 flags kbps burst stats bands 1 type drop rate 500 burstsize 1024
	Error 114: Provided meter configuration cannot be added.
```
Also tried using lower burst, no burst, no burst/stats flags, bigger rate(kbps), result is the same
**Was able to install meter only when I changed kbps flag to pktps**.
Note that 'help' section states `kbps` flag as valid one
2. The same command on a regular NoviSwitch with description `"NoviFlow Inc OF_13 NW400.6.4"` is not throwing an error:
```
ofsw2-lon# set config meter meterid 10 flags kbps burst stats bands 1 type drop rate 500 burstsize 1024
ofsw2-lon# show config meter meterid 10
	+----------------------+
	| Meter id: 10         |
	+----------------------+
	Flags: 0xd
		OFPMF_KBPS
		OFPMF_BURST
		OFPMF_STATS
	Bands count: 1
	Band 1:
		Type: OFPMBT_DROP (1)
		Rate: 500 kbps
		Burst size: 502 kb
```

**Expected behavior:** System is able to properly set meters as well as flow rules when setting ingress rules on this type of switches

**Comment by niksv** [comment]
fixed by #2355
