### ISSUE TITLE
Store all fields from OFPMP_DESC reply as a switch properties

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#2033]
When a switch connected to a controller, as a part of the initial exchange there is an OFPMP_DESC. We should store all the fields in a DB, like:
- Manufacturer desc.
- Hardware desc.
- Software desc.
- Serial no.
- Datapath desc.

**Comment by surabujin** [comment]
I have implemented this as part of event topology refactoring.

**Comment by surabujin** [comment]
Have been implemented as part of `network` topology.
