### ISSUE TITLE
Problems with finding symmetric reverse path

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2067]
Note: the issue is not critical, since reverse path is still _forced_ to be symmetric.
Observation:
1. Given two switches with parallel ISLs: `00:00:00:00:00:00:00:02` and `00:00:00:00:00:00:00:02`
2. Build a flow between them, see no issues.
3. Given two switches with parallel ISLs but different dpids: `00:00:00:22:3d:6c:00:b8` and `00:00:00:22:3d:5a:04:87`
4. Build a flow between them
**Expected:** no issues, nothing special.
**Actual:** Kilda complains in logs:
```
Failed to find symmetric reverse path from 00:00:00:22:3d:5a:04:87 to 00:00:00:22:3d:6c:00:b8. Forward path: Edge(srcSwitch=Node(switchId=00:00:00:22:3d:6c:00:b8, cost=0), destSwitch=Node(switchId=00:00:00:22:3d:5a:04:87, cost=0), srcPort=1, destPort=2, cost=700, availableBandwidth=10000000, latency=1)
```
Previously, before #1765 fix Kilda would build an asymmetric path in this case. Asymmetric path won't be built now, but the root cause of the issue remain unfixed.
related to #1765

**Comment by ylobankov** [comment]
Closed by #1926.
