### ISSUE TITLE
reduce logging levels in topology/flow/service/FlowService.java:rerouteFlow

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#2075]
https://github.com/telstra/open-kilda/blob/develop/services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java#L278

First two logs should be "debug".
Last one - "info".

**Comment by sergii-iakovenko** [comment]
Closing as the requested changes are not actual anymore: FlowService methods log a finalizing message as "info".
