### ISSUE TITLE
Cleanup extension for hardware env

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2076]
We need a cleanup tool that will make the staging (hardware) environment clean and suitable for further test suite.
1. Do the minimal cleanup steps required: delete flows, props, excess rules and meters, reset ISL properties like cost, bw, maintenance etc.
2. This should require an explicit flag and should not be run by default.
3. Do cleanup _before_ healthcheck test. Healthcheck test should still be run

**Comment by ylobankov** [comment]
Closed by #2091.
