### ISSUE TITLE
Wrong CookieID showing in Swagger UI

### ISSUE THREAD

**Issue by Settis** [telstra/open-kilda#2120]
Steps to reproduce:
1. Create a flow.
2. Get flow history via Swagger UI `/flows/{flow_id}/history`.

Expected result:
`dumps` contain right `forwardCookie` and `reverseCookie` like `4611686018427387906` and `2305843009213693954`.

Actual result:
The values are `4611686018427388000` and `2305843009213694000`.

**Please note**, that the bug is also appears in `/switches/{switch-id}/rules`.

Root  cause:
The API itself works fine and provides correct data. The bug in UI only when Swagger parse the result and make pretty view.

Possible solutions:
- Make API return cookie as string instead of long.

**Comment by sergii-iakovenko** [comment]
I removed 
> - Update Swagger UI, possible it was fixed.

from the list of possible solutions as the root cause is the way how browsers handle long values in JSONs.
