### ISSUE TITLE
Flow creation via NB with switch id in uppercase

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#214]
If we try to create flow through NB API and provide switch-id in uppercase we will get an error: 
```
error-message=Could not create flow: Path was not found, error-description=splitter_bolt
```

**Comment by surabujin** [comment]
@dpoltavets  Looks like all our API calls are affected by this issue.

All API calls accepting datapathId(switchId) must be validated and fixed if they are affected.

**Comment by surabujin** [comment]
One more "hit" in this issue, with on "/switches/{switch_id}/rules/validate" call. Luck that monitoring use lowercased version of this call...

**Comment by dpoltavets** [comment]
Resolved with the introduction of the SwitchId class.
