### ISSUE TITLE
Network dump doesn't populate switches to db

### ISSUE THREAD

**Issue by timofei-durakov** [telstra/open-kilda#2140]
Steps to reproduce:

- set up virtual network environment
- run BaseSpecification
- kill storm topologies
- clean up neo4j
- redeploy wfm
 
Expected result: 
 database will be updated with network data

Actual result:
 database is empty. There are error messages in logs:
`Unhandled exception in org.openkilda.wfm.topology.event.NetworkTopologyBolt`
`Switch not found: 00:00:00:00:00:00:00:03`

**Comment by sergii-iakovenko** [comment]
Not actual. Can't be reproduced.
