### ISSUE TITLE
Create functional test to verify minimal port speed value is chosen for ISL capacity

### ISSUE THREAD

**Issue by ylobankov** [telstra/open-kilda#2145]
As a QA engineer, I would like to have at least one functional test to verify minimal port speed value is chosen for ISL capacity (for the case when we have different port speed on ISL endpoints). For more details please refer to #2001.

**Comment by andriidovhan** [comment]
branch: issue-2145-minimal-port-speed-value-choosen-for-isl-capacity

**Comment by andriidovhan** [comment]
PR is created
https://github.com/telstra/open-kilda/pull/2326

**Comment by ylobankov** [comment]
Closed by #2326.
