### ISSUE TITLE
Add "remove excess" to /switches/{switch_id}/synchronize

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#2189]
Scope:
1. Add "Remove excess=(true/false)" optional parameter to `/switches/{switch_id}/synchronize`. Optional, `False` by default
2. Implement excess flow removal if flag above set to `True` as a part of synchronize operation.
System should be able to remove both excess rules and meters from the switch

**Comment by rtretyak** [comment]
This is not supposed to remove excess meters. Am I right?

**Comment by ylobankov** [comment]
Guys, shouldn't there be separate flags for excess rules and excess meters? Or we are going to proceed with one common flag?

**Comment by pzakatov** [comment]
one common flag is enough
