### ISSUE TITLE
`make build-base` can do better to warn users of failure

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#22]
For both the tarball downloads, and container builds, it'd be good to verify whether files / containers exist and warn the user.

I suggest adding verification checks and colorful error messages.

**Comment by nikitamarchenko** [comment]
got 
`make: docker: Command not found`
on new env

**Comment by nikitamarchenko** [comment]
`WARN: Couldn't find java type conversion for 'of_match_bmap_t' in of_table_stats_entry:match`

**Comment by nikitamarchenko** [comment]
`make[2]: mvn: Command not found`

**Comment by nikitamarchenko** [comment]
`make: docker-compose: Command not found`

**Comment by carmine** [comment]
Where did these problems come up?  If on the host machine (ie not inside a container), then it is expected that the user has installed docker / mvn / docker-compose.

**Comment by nikitamarchenko** [comment]
It's host machine, and check pre-requirements is save time on debugging `make build` command.

**Comment by pzakatov** [comment]
apr 22 cleanup
