### ISSUE TITLE
Migrate to "extended" kafka-consumer "setup" into storm-topologies

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#2239]
There is 2 way to setup/initialize kafka-spout in storm topology. Let name them "generic" and "extended". Consumer produced by "extended" setup method use `MessageDeserializer` as value deserializer, while consumer produced by "generic" setup use `StringDeserializer` as value deserializer.

`MessageDeserializer` decode "our" `Message` based object from JSON. So bolts in topology receive already decoded message object and do not need to decode them from JSON by themselves.

"Generic" setup method is already marked as "deprecated". The goal for this issue is to get rid from it completelly.

Related PR/issues:
* https://github.com/telstra/open-kilda/pull/1674

**Comment by niksv** [comment]
Closed by #2253 2253
