### ISSUE TITLE
extend existing 'Unable to create a flow on an isl port' test

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2254]
tests: https://github.com/telstra/open-kilda/pull/2223
1)Try to create on an isl port in case isl status is FAILED

- switch port down (we have to get the FAILED status)
- try to create flow using the port from isl above
Expected: flow should NOT be created

2)Try to create on an isl port in case isl status is MOVED
- one side of isl reconnect to another port(we have to get MOVED status)
- try to create flow using the port from isl above
Expected: flow should NOT be created

**Comment by rtretyak** [comment]
related to https://github.com/telstra/open-kilda/issues/1041

**Comment by andriidovhan** [comment]
required tests were added
