### ISSUE TITLE
the 'created' field is deleted after updating flow

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2333]
the _'created'_ field is deleted after updating/rerouting the flow

**Steps to reproduce:**

1. create a flow;
2. GET created flow(just to make sure that the 'created' field exist);
3. update flow OR reroute flow;
4. GET updated flow

**Actual result**
the _'created'_ field is not available anymore

***Expected result:**
the _'created'_ field should not be deleted

**Comment by rtretyak** [comment]
Looks like this is fixed in both v1 and v2
