### ISSUE TITLE
VxLAN on OVS design

### ISSUE THREAD

**Issue by Settis** [telstra/open-kilda#2357]
The sub task of #647 
OVS don't have an action for push_vxlan and pop_vxlan. You can set vxlan type on the interface instead.
For example in [OpenStack SF](http://artifacts.opnfv.org/sfc/brahmaputra/docs/design/architecture.html#ovs-nsh-patch-workaround).
![OPNVF SFC Loopback Workaround](http://artifacts.opnfv.org/sfc/brahmaputra/docs/design/_images/OPNFV_SFC_BrahmaputraOvsNshWorkaround_toSf.jpg)
They use `vtep` port for VxLAN push and then route the package via Kernel to OVS back.

**Comment by timofei-durakov** [comment]
addressed by https://github.com/telstra/open-kilda/pull/4516
