### ISSUE TITLE
Remove invalid/outdated kilda system (default) rules

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#2376]
Speaker always tries to install system rules on switch activation. If any system rule's match field/priority has been changed - it will be installed to the switch next to already existing old ones and it is unexpected/incorrect behavior.

Speaker (Floodlight) should keep only those rules on switches that he expects to be installed on switches and remove excess system entries.

NB: OF specification says that "A flow table entry is identified by its match fields and priority: the match fields and priority taken together identify a unique flow entry in the flow table."

**Comment by surabujin** [comment]
We can drop all rules "system/default" before installing new/actual rules. "System/default" rules can be distinguished by "system/default" bit flag into the cookie.
