### ISSUE TITLE
Update traffic encapsulation schema

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#2386]
# Goal
increase max flows to 4k

# Details
Now we use 2 different VLAN tag for each flow "path" (one for A-to-Z and another for Z-to-A direction). There are no obstacles to use the same VLAN tag for both directions. Advantages from this approach - the flow will need less unshareable "resources".

# Plan
- [ ] Coding by May 28
- [ ] SWE test by May 30
- [ ] QA test by Jun 3
- [ ] Deploy be Jun 4

**Comment by niksv** [comment]
Closed by #2397
