### ISSUE TITLE
Assess `make atdd` for acceptance tests that are really unit tests or integration tests (if any)

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#24]
There are a lot of tests in ATDD. Some of these might be better placed as unit tests or integration tests, vs a business requirement test.  

The desire to change/refactor stems from getting tests closer to the point of change, helping improve developer productivity. In general, it takes longer to find and fix a bug in atdd than it is in an integration test, which takes longer than finding in a unit test.

For each acceptance test, review whether it can be made into a unit test, or an integration test, or whether it is a truly an acceptance test.

**Comment by carmine** [comment]
@deepak to tackle ..

**Comment by nikitacherevko** [comment]
I think we may do this task in 2 days.

**Comment by surabujin** [comment]
I think it will take 5 days. Most time will be required to analyse and possible refactor of tests structure.

**Comment by nikitamarchenko** [comment]
> acceptance testing: Formal testing with respect to user needs, requirements, and business processes conducted to determine  whether or not a system satisfies the acceptance criteria and to enable the user, customers or other authorized entity to determine whether or not to accept the system.

For do that we need a list of needs, requirements, and business processes. With that list my estimate 4d.

**Comment by pzakatov** [comment]
outdated
