### ISSUE TITLE
Emitting to HistoryBolt causes retries in FlowHS topology

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#2418]
In case when FlowCreateHubBolt or FlowRerouteHubBolt emits a message to HistoryBolt, processing of a tuple retries multiple times. This causes issues in command processing.

Note: currently emitting from FlowCreateHubBolt or FlowRerouteHubBolt is disabled (see commented out method sendHistoryUpdate).

**Comment by nikitacherevko** [comment]
The issue is not reproducible with the latest changes from develop branch.
