### ISSUE TITLE
lack of resource on a virtual environment causes a lot of reties in the 'flow' topology 

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2429]
**Step to reproduce:**

-  schedule creating ~4k flows

**Actual result:**
I guess due to lack of resources on a virtual env system is starting to re-read messages from _kafka_.
So then as a result it causes a  lot of retries in the _flow_ topology

for example:
according to db flow was created at _"01:08:08.859Z"_.
in a _kibana_ service we can observe so many retries:  `07:31, 07:05, 06:57, 06:41, 06:34, 06:31, 06:21, 06:19, 06:19 ...`
error in the _storm -> flow_ topology
`java.lang.RuntimeException: Invalid prepared state for commit, preparedState null txid 0 at org.apache.storm.state.InMemoryKeyValueState.commit(InMemoryKeyValueState.java:103) at org.apache.storm.to
`

**Comment by rtretyak** [comment]
Was not able to reproduce this exact issue on local env, tried multiple times. Run into #4224 in this scenario instead
