### ISSUE TITLE
Refactor topologies that consume kafka messages - move the logic into testable libraries

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#25]
At present, several topologies that consume messages from kafka hold the message processing logic within the bolts.

To facilitate testing and changes, it'll be better to move that logic into a library and add unit tests.  The unit tests should interact with messages library so that if/when things change in message format, the unit tests will pick it up.

**Comment by nikitacherevko** [comment]
Dear @carmine ,
Could you please provide me some of these bolts, which you want to move to lib. And whether it should be another maven module or we should locate it somewhere else.

Besides, currently we have some tests that cover such cases and we can rewrite other tests to do it too. It may be just simple junit tests or integration tests with listening kafka topic.

**Comment by nikitacherevko** [comment]
I'd like to clarify the scope of work for more accurate estimate,
but at first sight it looks like this issue will take up to 5 days

**Comment by nikitamarchenko** [comment]
Newer write Storm topologies, 7d for me.

**Comment by surabujin** [comment]
Is the goal of this task to move "bolts" into some new independent(from storm codebase) library to simplify tests?

Full topology and tests refactoring will take more that 15d... 

PS Is the same goal can be achieved with current structure by using "local" topology run?

**Comment by nikitamarchenko** [comment]
I will try to do that.

**Comment by pzakatov** [comment]
obsolete. Moved to #1130
