### ISSUE TITLE
system is allowing to create a one-switch flow on a DEACTIVATED switch

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2576]
**Steps to reproduce**

1. deactivate a switch
2. try to create an one-switch flow on the deactivated switch

**Actual result**
Flow is created
Flow status is "In progress"

**Expected result**
Flow shouldn't be created
An error should be returned, something like "Could not create flow."

**NOTE:**
APIv1 and APIv2 are  affected

**Comment by rtretyak** [comment]
This is fixed in V2
