### ISSUE TITLE
Misleading log entries when flow is rerouted

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2584]
When reroute request is issued, but the flow is already on the best path and as a result the flow is NOT rerouted, the following message is present in logs:
`Rerouted flow with new path: FlowPathsWithEncapsulation(forwardPath=....` which I find misleading, since the path didn't actually change and reroute was not actually performed
**Steps:**
- Create a flow
- Call `/api/v1/flows/:flowId/reroute` for that flow
- Observe `rerouted: false` in response
- Look for logs with that flow id
**Expected:** details to be defined, but message should _not_ state that the path was changed
**Actual:** There is a `Rerouted flow with new path: FlowPathsWithEncapsulation(forwardPath=....` message saying that the flow is rerouted with a new path.

**Additional note**: The `Kilda Flow operations` Kibana Dashboard will also report such operation as `Rerouted`, but I'm not sure whether such operation should be qualified as a successful or not successful reroute

**Comment by sergii-iakovenko** [comment]
Closing as not actual. Currently such reroute requests produce the following result message in the log:
```
WARN | Failed reroute of the flow XXX, reason: Reroute is unsuccessful. Couldn't find new path(s)
```
