### ISSUE TITLE
performance degradation after creating huge amount of flows

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2585]
I tried to create 4094 flows on a local environment
Unfortunately I was able to create 3092 flows 
After that system was not able to proceed new request for creating flow.
An error was returned `Operation has timed out`

**Comment by rtretyak** [comment]
Only relevant for v1 API, I was able to create 4k flows using h&s v2 API

**Comment by rtretyak** [comment]
v1 is removed
