### ISSUE TITLE
Wrong 'Warn' logging during deletion of rules, saying that flag is not supported

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2590]
**Steps:**
1.  Call `/api/v1/switches/:sw/rules?delete-action={{action}}` where 'action' is one of the following: DROP_ALL, DROP_ALL_ADD_DEFAULTS, IGNORE_DEFAULTS, OVERWRITE_DEFAULTS, REMOVE_DEFAULTS, REMOVE_ADD_DEFAULTS
**Expected**: Corresponding delete action is performed with no warnings
**Actual**: Corresponding action is properly performed, but following WARN message is logged: `Received unexpected delete switch rule action: {{action}}`

**Comment by nrydanov** [comment]
No longer reproduces. Closed.

**Comment by nrydanov** [comment]
No longer reproduced. Closed.
