### ISSUE TITLE
Create default drop rule per port basis

### ISSUE THREAD

**Issue by timofei-durakov** [telstra/open-kilda#2620]
Now Switch has 1 drop rule in table 0 for all packets not matched.
We need to create new default drop rules on a per port basis:
table: 0 
match: in_port
priority: 2
cookie: default masked cookie, that encode port number, tbd

**Comment by rtretyak** [comment]
So the old drop-all rule with `priority: 1` should still be present, right?

**Comment by timofei-durakov** [comment]
@rtretyak correct, since it has lower priority it will be ok

**Comment by rtretyak** [comment]
What to test:
- On switch connect new default drop rules should be installed in addition to old one.
  - amount of rules equals to amount of ports on switch regardless of UP/DOWN state (logical ports too?)
  - verify proper match and priority on those rules
  - verify cookie is properly masked and has a port number encoded properly
- Corresponding install/delete rules endpoints that leverage default rules should consider new default rules
  - Delete actions such as `REMOVE_ADD_DEFAULTS` etc.
  - Install actions should be able to force installation of new default rules
- Default Rules Validation should be able to catch a missing/misconfigured or excess drop rule
- Send traffic which is caught by a certain drop rule. Verify packet-count growth. Verify OTSDB stats are correctly logged for the rule.

**Comment by surabujin** [comment]
On new port "added after switch connect" we should install "drop rule" too. But we can avoid rule removal on port remove.

**Comment by timofei-durakov** [comment]
No longer valid, since this counters are available by using OpenFlow port stats rx-dropped
