### ISSUE TITLE
Evaluate Path Computation Engine 0.1

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#27]
Initial PCE code contribution covered a lot of ground. This issue is meant to address the quality and extent of this coding contribution. 

Definition:
PCE = Path Computation Engine
PME = Path Management Engine

DESIGN:
- [x] Document the key use cases that are of interest (2h) 
- [ ] Document the current vs desired PCE design, with the below use cases in mind

KEY USE CASES to Analyze:
- [ ] PCE: calculatePath(src,dst,policy)
- [ ] PCE: calculatePathWithExclusions(src,dst,policy,exclusions) // exclusions = ISLs not to use.
- [ ] PCE: reservePath(path,[expiration])
- [ ] PME: deployPath(path,[expiration])
- [ ] PME: pathIsDeployed(path)
- [ ] OPS: networkHealth(flags) -> X switches (U warnings), Y isls (V warnings), Z flows (W warnings) 
--> if flags | fault_detail, then dump warning details.

TESTING:
- [ ] (new) Code coverage
- [ ] Extend unit tests
- [ ] Extend acceptance tests

**Comment by nikitacherevko** [comment]
I guess this task will take up to 20 days, because of large scope of work.
Probably it would be better to divide it to smaller ones.

**Comment by surabujin** [comment]
Join to 10d estimation.

**Comment by carmine** [comment]
I have context, so setting it at 5d. I'll tackle this work.

**Comment by a-ovchinnikov** [comment]
3d to 5d.
