### ISSUE TITLE
Unhandled exception in org.openkilda.wfm.topology.stats.bolts.CacheFilterBolt

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2755]
**Steps to repoduce:**

1.  create a single-switch or simple flow with `"maximum-bandwidth": 0` and `"ignore_bandwidth": true`
2. observe error log in kibana

**NOTE:** 
This kind of error also can be observed during `rerouteFlow` action

**Comment by nrydanov** [comment]
No longer reproduces. Closed.
