### ISSUE TITLE
Flow delete may sometimes fail by hitting DB race condition if h&s reroute is active

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2758]
**Description:** when doing multiple deletes in a loop, system may run into a race condition and fail to delete a flow. Note that flows may be in the reroute process (h&s)
**Comment:** Similar cases for create/update had been fixed by introducing 'retries' on operation
**Error:**
```
flows.each { flowHelper.deleteFlow(it.id) }
|     |
|     org.springframework.web.client.HttpServerErrorException: 500
|     {
|       "correlation_id" : "a75412d9-fbcc-412e-888c-9e15ab923de2 : fn-tests-1566916483417",
|       "timestamp" : 1566916483787,
|       "error-type" : "Flow deletion error",
|       "error-message" : "Can not delete flow: Error executing Cypher; Code: Neo.ClientError.Statement.EntityNotFound; Description: Unable to load NODE with id 2356.",
|       "error-description" : "Error executing Cypher; Code: Neo.ClientError.Statement.EntityNotFound; Description: Unable to load NODE with id 2356."
```

**Comment by rtretyak** [comment]
Note that this is not reproducing for V2 delete. This issue's a candidate to be closed

**Comment by niksv** [comment]
V1 delete uses v2 delete under the hood. Also error message says that error was produced by Neo4j. But Neo4j for replaced with Oriend db
