### ISSUE TITLE
system is marking protected path as down(when system can't find not-overlapping new protected path) while rerouting flow

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2762]
**Steps to reproduce:**
1. Create a protected flow on switches with three diverse paths only;
2. detect which path is not used by the flow and make it more preferable;
3. reroute the flow; (response: ` "rerouted": true`)

**Actual result**
The flow status is DEGRADED
Main path of the flow is rerouted and marked as UP
Protected path is not rerouted and marked as DOWN
error is kibana:
`Failed reroute of the flow <flowId>, reason: Reroute <flowId> is unsuccessful: can't find non overlapping new protected path.`

**Expected result:** 
The protected path is operable, so the protected path should be marked as UP
and Flow should be in UP state because 

**NOTE**
described behaviour doesn't depend from ` "flows_reroute_via_flowhs":` configuration

**Comment by rtretyak** [comment]
This is a h&s -only issue, i.e. happens only with h&s reroutes 'on'

**Comment by andriidovhan** [comment]
for QA: remove the Ignore annotation when this issue is fixed
```
"System doesn't mark protected path as DOWN when can't find non overlapping protected path during intentional\
 reroute"()
```

**Comment by pkazlenka** [comment]
Issue is fixed, as well as the test.
