### ISSUE TITLE
LLDP Connected Devices: add ability to synchronize lldp rules

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2779]
As a system administrator, I want to be able to synchronize(install missing, remove excess) lldp rules when calling 'sync switch' endpoint, so that discrepancies in lldp rules could be fixed via NB API.
AC:
- system fixes any discrepancies in lldp rules and meters when calling `/api/v1/switches/:sw/synchronize`
- subsequent switch validate call should show no discrepancies in rules or meters

**Comment by niksv** [comment]
fixed here https://github.com/telstra/open-kilda/pull/3024
