### ISSUE TITLE
Flow creation via NB API but in neo4j / topology-engine-rest found 100 records corresponding to single flow.

### ISSUE THREAD

**Issue by gauravchug** [telstra/open-kilda#279]
I have created flows using NB API.
**flowid: "f9f3sfdsf0001"
flowid: "f222220001"**

**Actual Result :** 
In neo4j / topology-engine-rest ,  found 100 records corresponding to single flow.

**Expected Result :**
It should return two records where i can see forward and reserve path of flow.

**Comment by pzakatov** [comment]
outdated
