### ISSUE TITLE
Build error in open-kilda

### ISSUE THREAD

**Issue by SanjayAwasthi** [telstra/open-kilda#280]
I am building open-kilda with command "make build-latest" and I am getting following error.

Successfully built 6d3585f9047e
Successfully tagged kilda/logstash:latest
docker-compose build
ERROR: Invalid interpolation format for "image" option in service "zookeeper": "kilda/zookeeper:${full_build_number:-latest}"
Makefile:23: recipe for target 'build-latest' failed
make: *** [build-latest] Error 1

Please rectify it.

**Comment by carmine** [comment]
I believe this bug no longer exists
