### ISSUE TITLE
Occasionally unable to discover a switch

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2805]
Sometimes I am unable to re-create a topology for testing needs. Switch occasionally would be discovered as an 'isl discovery stub', but never fully discovered due to fsm errors.
```
    {
        "switch_id": "00:00:9a:5d:60:8a:08:3d",
        "address": null,
        "hostname": null,
        "description": "auto created as part of ISL 00:00:9a:5d:60:8a:08:3d_4 <===> 00:00:ee:d4:0c:4c:35:5a_4 discovery",
        "state": "DEACTIVATED",
        "under_maintenance": false,
        "of_version": null,
        "manufacturer": null,
        "hardware": null,
        "software": null,
        "serial_number": null
    }
```
Errors are (full errors with traces attached at the bottom):
```
Transition from "SYNC" to "SETUP" on "SYNC_ENDED" with context ...
```
```
Error during transition
```
`
00010012 : couldn't invoke 'public void org.openkilda.wfm.topology.network.controller.sw.SwitchFsm.setupEnter(org.openkilda.wfm.topology.network.controller.sw.SwitchFsm$SwitchFsmState,org.openkilda.wfm.topology.network.controller.sw.SwitchFsm$SwitchFsmState,org.openkilda.wfm.topology.network.controller.sw.SwitchFsm$SwitchFsmEvent,org.openkilda.wfm.topology.network.controller.sw.SwitchFsm$SwitchFsmContext)' with [null, SETUP, SYNC_ENDED, SwitchFsm.SwitchFsmContext(output=org.openkilda.wfm.topology.network.storm.bolt.sw.SwitchHandler@44276797, speakerData=null, history=null, syncResponse=SwitchSyncResponse(switchId=00:00:9a:5d:60:8a:08:3d, rules=RulesSyncEntry(missing=[], misconfigured=[], proper=[-9223372036854775807, -9223372036854775806, -9223372036854775805, -9223372036854775804], excess=[], installed=[], removed=[]), meters=MetersSyncEntry(missing=[], misconfigured=[], proper=[], excess=[], installed=[], removed=[])), syncKey=fc9ca956-ef69-4515-88e7-00b673f70f26, portNumber=null, portEnabled=null)] on org.openkilda.wfm.topology.network.controller.sw.SwitchFsm@5c2b4ef: org.neo4j.driver.v1.exceptions.ClientException: Node(36283) already exists with label `switch` and property `name` = '00:00:9a:5d:60:8a:08:3d'.
`

I am unable to reproduce this on just-deployed kilda, but rather after cleaning up the environment by deleting (without force) old switches and creating new topology. Note that new switches would always use newly-generated random mac addresses.

[error1.txt](https://github.com/telstra/open-kilda/files/3621782/error1.txt)
[error2.txt](https://github.com/telstra/open-kilda/files/3621783/error2.txt)

**Comment by surabujin** [comment]
Network topology has race condition in code persisting data into DB. - ISL data require SWITCH data in DB on creation time. But in some circumstances, ISL can be "discovered" almost in the same time as switch discovered/activate and SWITCH data do not stored in DB yet. In this case, ISL code creates SWITCH stub record and expect that it will be replaced with actual data by `SwitchFsm` code.

`SwitchFsm` have DB transaction retry policy, targeted to make several "save" data attempts on constraint violation errors. But at this moment retry policy in SwitchFsm(same is true for all other FSM in network topology) does not include a rule for `org.openkilda.persistence.ConstraintViolationException` (exception used to indicate unique constraint violation). 

So to fix this issue we should add `org.openkilda.persistence.ConstraintViolationException` into retry policy into the network (at least network) topology.

**Comment by rtretyak** [comment]
I am not experiencing this lately thus closing
