### ISSUE TITLE
Find flows by switch/port doesn't work properly

### ISSUE THREAD

**Issue by timofei-durakov** [telstra/open-kilda#2885]
`/v1/switches/{switch-id}/flows` in case when port is specified returns less flows then actually goes through it. 
Steps to Reproduce:
TBD

**Comment by andriidovhan** [comment]
**Steps to reproduce:**

1. Create single-switch flow1;
2. make sure that flow1 is returned  via `/api/v1/switches/:switch-id/flows`;
3. create simple(not single-switch) flow2 on the same switch;
4. GET `/api/v1/switches/:switch-id/flows`.

**Actual result:**
flow2 is returned only

**Expected result**
flow1 and flow2 should be returned
