### ISSUE TITLE
no validation for the 'vlan_id' field while creating a flow via APIv2

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2949]
**Step to reproduce**

- try to create a flow with negative vlan number(e.g. `-1`) via APIv2;

**Actual result**
Flow is created with negative vlan_id(` -1 `).
Then as result we can't GET flow(s) and delete the created flow.
500 Internal Server Error is returned to mentioned requests.

**Expected result**
Flow shouldn't be created.

**Workaround**
update the flow with valid `vlan-id`

**Comment by rtretyak** [comment]
more general case: #3491
