### ISSUE TITLE
[Bug] Swagger added junk data in links/props API

### ISSUE THREAD

**Issue by gauravchug** [telstra/open-kilda#295]
Swagger added junk data in links/props API.

**Actual Result**
<nb_host>/api/v1/link/props{?src_switch,src_port,dst_switch,dst_port}&src_switch=00%3A00%3A00%3A00%3A00%3A00%3A00%3A00&src_port=1&dst_switch=00%3A00%3A00%3A00%3A00%3A00%3A01%3A00&dst_port=1

**Expected Result**
<nb_host>/api/v1/link/props{?src_switch,src_port,dst_switch,dst_port}&src_switch=00:00:00:00:00:00:00:00&src_port=1&dst_switch=00:00:00:00:00:00:01:00&dst_port=1

**Comment by pzakatov** [comment]
outdated. Reopen if needed
