### ISSUE TITLE
v2 delete: Dead locks when simultaneously removing multiple flows

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#2983]
**Summary:** sometimes system is unable to concurrently remove a flow. Flow hangs in 'In Progress' state
**Steps:**
```
        when: "Create multiple flows on the same ISLs concurrently"
        then: "Available bandwidth on related isls is reduced based on bandwidth of created flows"
        when: "Simultaneously remove all the flows" //issue here
        then: "Available bandwidth on all related isls is reverted back to normal"
```
**Test script:** `ContentionV2Spec."Parallel flow crud requests properly allocate/deallocate bandwidth resources"`. Note that you may want to add `@Rerun` annotation to catch the issue, it is pretty rare. Or increase the amount of parallel threads.
**Problem flow history:** [deadlock_history.txt](https://github.com/telstra/open-kilda/files/3904828/deadlock_history.txt)

**Comment by sergii-iakovenko** [comment]
Become not actual after migration from Neo4j persistence. Can't be reproduced.

ContentionV2Spec."Parallel flow crud requests properly allocate/deallocate bandwidth resources" fails due to another issue (https://github.com/telstra/open-kilda/issues/3411)
