### ISSUE TITLE
updateFlowV2 is leaving excess rule/meter after updating a flow

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2995]
**Steps to reproduce**
* create a vxlan flow via APIv2;
* update flow encapsulation via APIv2(vxlan -> transit_vlan) 
* validate src/dst  switch

**Actual result** 
Flow is updated, but excess rule and meter are on the switch
if you try to synchronize the switch, then system returns an error:
```
{
      "error-type": "Internal service error",
    "error-message": "For input string: \"0x000000000000003d\"",
    "error-description": "Error in SwitchSyncFsm"
}
```

**Expected result**
switch should pass switchValidation

**Comment by andriidovhan** [comment]
for QA: ` def "System allows to create/update encapsulation type for a flow\
(#encapsulationCreate.toString() -> #encapsulationUpdate.toString())"() `

**Comment by andriidovhan** [comment]
one more case:
**Steps to reproduce:**
* create a single -switch flow(for example the `02` switch);
* validate the `02`  switch, make sure that there is no excess rule/meter;
* update the flow via APIv2 to multi-switch flow; (e.g `dstSwitch = 04`)
* validate the srcSwitch

**Actual result:**
Flow is updated, but excess rule and meter are on the switch.
NOTE: we can synchronize the switch

**Expected result:**
switch should pass switchValidation

**Comment by niksv** [comment]
Looks like this bug was fixed. @rtretyak @andriidovhan Could you please check?

**Comment by andriidovhan** [comment]
We will check once the hardware switch is available

**Comment by andriidovhan** [comment]
That matter is not reproduced anymore.
