### ISSUE TITLE
rerouteFlowV2 is leavling excess rule after rerouting a vxlan flow

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2996]
**Steps to reproduce:**
* create a vxlan flow via APIv2;
* make other path more preferable;
* init flow reroute via APIv2 (`"/api/v2/flows/{flow_id}/reroute"`);

**Actual result:**
Flow is rerouted, but excess rule appeared on the src/dst switches
if you try to synchronize the switch, then system returns an error:
```
{
    "error-type": "Internal service error",
    "error-message": "For input string: \"0x000000000000003e\"",
    "error-description": "Error in SwitchSyncFsm"
}
```

**Expected result:**
no excess rule when reroute is completed

**NOTE**
this issue can be related to  #2995

**Comment by andriidovhan** [comment]
for QA: `def "Intentional flow reroute with VXLAN encapsulation is not causing any packet loss"() {`

**Comment by niksv** [comment]
Looks like this bug was fixed. @rtretyak @andriidovhan Could you please check?

**Comment by andriidovhan** [comment]
We will check once a hardware switch is available.

**Comment by andriidovhan** [comment]
That matter is not reproduced anymore.
