### ISSUE TITLE
Syncing VXLAN rule installs a malformed rule

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3021]
1. Create a VXLAN flow
2. Intentionally create a missing rule by manually removing one of the flow rules
3. Reinstall the missing rule by synchronizing target switch
**Expected:** System installs missing rule in the exact same form as it originally looked like
**Actual:** System installs missing rule, but its match is missing `ip_proto`, `udp_dst` and `eth_type` fields (for egress rule)

Note: V2 Delete is having troubles deleting such flow, it leaves the malformed rules as excess and system is unable to synchronize them afterwards

**Comment by niksv** [comment]
Looks like this bug was fixed. @rtretyak @andriidovhan Could you please check?

**Comment by andriidovhan** [comment]
We will check once the hardware switch is available

**Comment by andriidovhan** [comment]
The issue is reproduced on kilda_V1.88

**Comment by andriidovhan** [comment]
my bad, the issue is not reproduced anymore.
