### ISSUE TITLE
the allocateProtectedPath property is automatically disabled when system can't enable it during updating flow

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#3033]
**Steps to reproduce**
* create a flow(`allocateProtectedPath = false`);
* update the flow via APIv2(`allocateProtectedPath = true`); (system shouldn't be able to enable the `prottectedPath` )
it can be easy reproduced by test: `def "Flow rules are not reinstalled according to switch property while swapping to protected path"()`

**Actual result**
HttpStatus code 200 is returned.
In a fact, flow is not updated(`allocateProtectedPath = false`)
Flow is reverted to state before updating.

**Expected result**
Flow should be updated(`allocateProtectedPath = true`).
If system can't enable protected path, then flow should be marked as `DEGRADED`

**Comment by andriidovhan** [comment]
**Issue:**
The `flowUpdate` operation doesn't inform user that a flow isn't updated and automatically reverts the flow to `stateBefore`.
Then as result user can be a little bit disappointed that successful response was returned by the system, but in fact flow wasn't updated.


As a user, I want to know actual status of the `flowUpdate` operation, so that I can be sure that flow is really updated.

AC:
* flow should be reverted to 'stateBefore';
* flow status should be changed to `Down`;
* TBD

**Comment by dpoltavets** [comment]
The PR (#3237) that closes this issue solves the first case described above. The second case has nothing to do with the problem being solved, and a separate issue should be created for it.
