### ISSUE TITLE
h&s auto-reroute may build path on a failed ISL and mark flow as UP

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3087]
Under certain circumstances it is possible for h&s reroute to build flow on a path (and leave it there), which is already known to be broken. Flow will have UP status and pass all validations, only the ping/traffic won't be going through. As far as investigation goes: a first reroute should start, then a subsequent reroute (initiated by one more port down) happens while the first one is in progress and for some reason the last reroute gets suppressed/fail to actually happen.
Adding below some artifacts. Issue can be sometimes reproduced by running EnduranceV2Spec.
history: [path_on_failed_isl.txt](https://github.com/telstra/open-kilda/files/4009815/path_on_failed_isl.txt)
Some logs:
![image](https://user-images.githubusercontent.com/7931639/71582467-0830a480-2b13-11ea-9c21-0db71f1bad2d.png)

What happened to the last legal reroute that should have fixed the flow, but it failed to happen:
![image](https://user-images.githubusercontent.com/7931639/71582515-3d3cf700-2b13-11ea-82b9-3446c0a0e5e7.png)

Note, the very first reroute actually finished only after all the other reroutes failed:
![image](https://user-images.githubusercontent.com/7931639/71582549-652c5a80-2b13-11ea-8055-6937b2ea6864.png)

So the sequence was:
1. Start a reroute
2. After ~7 seconds more reroute requests come, they get throttled into a single request
3. We see that request does not get satisfied for some reason (?)
4. The very first reroute from the step 1 finishes its execution and marks the flow as UP, ignoring the step 2 requests.

**Comment by surabujin** [comment]
There is a "lock" for flow on reroute operation, so when second reroute event come into rerouting handler, it checks this lock and does not perform "second" (and so on) reroute if it busy. It helps to not "break" flow's data persistence, but it can't handle double errors (like in this case).

**Comment by surabujin** [comment]
Fix has been released https://github.com/telstra/open-kilda/releases/tag/v1.45.2
