### ISSUE TITLE
Avoid linear search in FlowCache

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#309]
Currently pce.cache.FlowCache performs linear search through key-value pairs to locate a flow by node, ISL or port. This may cause performance issues when reroute events are processed.

The possible solution is alternative views of the flow data: a map of node_id to flow_id, isl to flow_id, etc. Or re-implement the cache to use http://commons.apache.org/proper/commons-collections/javadocs/api-release/org/apache/commons/collections4/map/MultiKeyMap.html

**Comment by sergii-iakovenko** [comment]
Pre-H&S makes this issue obsolete.

**Comment by IlyaMoiseev** [comment]
Obsolete, FlowCache was removed during Pre-H&S
