### ISSUE TITLE
It is possible to have duplicates in neo4j because of MERGE query

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#318]
I've run stress test that sent several hundred messages with links discovered messages between two switches and then TE created several nodes with the same switch id.

**Comment by nikitacherevko** [comment]
That's probably the cause of the issue: https://stackoverflow.com/questions/34302176/neo4j-merge-and-atomic-transaction?answertab=oldest#tab-top

I have already tried to add constraints for switches and duplicates have disappeared, but have incorrect fields values (one switch has only one field with state 'disabled', looks like query with node creation was ignored).

**Comment by carmine** [comment]
I'm curious if this is also an artifact of using py2neo .. as discovered for reading objects, where py2neo will cache the properties in a relationship.  In that scenario. an object.pull() was necessary.

Similarly, I'm curious if we need to deal with the object itself (get it), set the properties, and do an object.push().
