### ISSUE TITLE
Reason is not specified when flow reroute fails due to timeout

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3249]
**Steps:**
1. Perform a long reroute that will fail due to timeout (high-loaded system/too many reroutes/big network delay)
2. Find reason of reroute failure in logs
**Expected:** Reroute failure reason states that reroute failed due to timeout, specifies which value is used for timeout.
**Actual:** Reason of reroute failure is 'null':
```
Failed reroute of the flow perfload_28Feb133400_664_walnut8267, reason: null
```

**Comment by surabujin** [comment]
The #3109 partially solves this issue. But it would be good to have a better solution.
