### ISSUE TITLE
Create a way to delete switch when it is no longer used

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#328]
Check that switch is not a part of a flow
Check that switch have no ISLs
Check that switch is not Active
Delete switch from neo4j
Delete switch from a cache

Proposed design
---------------------
Add `DELETE` action to `/switches/{switch_id}` in NB API with optional flag `force` (default is false).
The action must be protected by `EXTRA_AUTH`.

Feature workflow when the event dispatched from the separate topology:
![sendfromtopo](https://user-images.githubusercontent.com/1427656/43403262-e66347a4-9414-11e8-8962-1841458914f1.png)

A detailed description of the checks:
- Check that the switch is deactivated. Read switch status from neo4j and check it. Otherwise, raise an error "Removable switch is active. It must be deactivated first.".
- Check that the switch is not a part of a flow. Do `/switches/{switch_id}/rules/validate` and check that no rules are presented. Otherwise, raise an error "Switch have assigned rules. It must be freed first.".
- Check that the switch has no active ISL's. Otherwise, raise an error "Switch have active links. Ensure that it the switch is unplugged first.".
- Check that the switch has no inactive ISL's. Otherwise, raise an error "Switch have inactive links. Remove them first.".

Steps to complete
-----------------------
- [ ] approve the desing
- [ ] implement NB API
- [ ] implement checks (can be a part of NB)
- [ ] implement deleting the switch from neo4j
- [ ] implement deleting the switch from cache #1074

**Comment by surabujin** [comment]
Perhaps "depopulate" is more correct term here? We should not "delete" switch in advice, but we can mark it with "should not be used" marker.

**Comment by Settis** [comment]
How to check that switch is not a part of flow? Is it a sufficient condition, that the switch have no more rules except Kilda default (drop, verification broadcast and unicast) rules?

**Comment by Settis** [comment]
The issue description was updated with Proposed design.

**Comment by Settis** [comment]
The issue description was updated with UML and detailed description.

**Comment by surabujin** [comment]
Why proposed design prefer to not check operation results? I though we stop use "fire and forget" approach.

**Comment by Settis** [comment]
It can be changed to check operation results if needed. As you can see, we have 2 async operations for delete the switch from DB and Cache topology. @surabujin, can we wait for results in NB?
