### ISSUE TITLE
v2 Create protected flow may hit deadlocks when allocating resources

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3299]
**Description:** Sometimes when creating a flow with protected path(`allocateProtectedPath=true`) system may create a corrupted flow with excess paths allocated. Such flow cannot be removed via v2 API due to #3256 

error observed:
```
LockClient[52600] can't wait on resource RWLock[NODE(81), hash=173985210] since => LockClient[52600] <-[:HELD_BY]- RWLock[NODE(61), hash=1488959714] <-[:WAITING_FOR]- LockClient[52602] <-[:HELD_BY]- RWLock[NODE(81), hash=173985210]
--
```
[full_error.txt](https://github.com/telstra/open-kilda/files/4342505/full_error.txt)
![image](https://user-images.githubusercontent.com/7931639/76841724-dbeb1100-6841-11ea-8eaf-7948fe57741c.png)

**Comment by sergii-iakovenko** [comment]
@rtretyak Become not actual, since we moved to tinkerpop / orientdb persistence.
