### ISSUE TITLE
Suggest to standarize logger layout pattern 

### ISSUE THREAD

**Issue by andy-wang-haibo** [telstra/open-kilda#334]
Different components have different logger layout patterns, which will make parsing logs to extract information less efficient. Also suggest wfm logger timestamp to add date (year/month/day) part.

examples:
./templates/templates/northbound/log4j2.xml.j2:5:            pattern="%d{ISO8601} | %-5.5p | %-32.32t | %-32.32c{1} | @project.name@ - @project.version@ | %m%n"

./services/wfm/src/main/resources/log4j2.xml:5:            pattern="%d{**HH:mm:ss**} [%t] %-5level %logger{36} - %msg%n"

**Comment by pzakatov** [comment]
outdated
