### ISSUE TITLE
Disable floodlight's LLD packets

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#340]
Floodlight implements it's own link discovery mechanism. Kilda implements it's own LLDP mechanism. So we don't need FL's LLDP and can disable it.

Find the way to disable FL's LLDP mechanism. It can solve "overflooded" issues with acton switches.

**Comment by surabujin** [comment]
Flodlight implemnets LLDP into `net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager`. We don't request to load this module in our FL configs. But it is loaded as a dependency for `net.floodlightcontroller.accesscontrollist.ACL` (https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/4882434/ACL+Access+Control+List+Dev). As far as I know we don't use this module from our code.

So lets try to disable it.

**Comment by surabujin** [comment]
The "ACL" module was added into FL config into 010471d
@nikitacherevko  do you remember details related to this change?

**Comment by nikitacherevko** [comment]
@surabujin looks like we might delete this module without any consequences
