### ISSUE TITLE
Rate limit for controller's messages

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#341]
Find a way to setup rate limit for messages the controller sends to switches. This should solve the issues with "overflooded" switches which drop packets if we send too many.

**Comment by surabujin** [comment]
Mostly done with research regarding rate limiting "issue" on accton switches. I have write flooding module (send ICMP package via one switch port) and check is all produced package was send (using ports send packet counter)... all 5k packets batch was send. At same time I am tracing syslog to catch "drop packets message"...

A lot of "drop message" records was logged during this experiment. Looks like we have misunderstanding the meaning of this messages. Looks like this messages are related to dropped log messages not OF message/packets. In other words switch logging system is dropping log messages if their amount reach some limit in a second. And this is much more looks like true, than unconditional random drop of control(open flow messages) messages.

To completely remove any doubts one more experiment can be done. In this experiment test module should "flood" switch with OFRules in maximum possible speed and check existence of this rules on the switch at the end.

**Comment by pzakatov** [comment]
closed
