### ISSUE TITLE
Misleading errors on flow creation in case of no path found

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3489]
1. Try creating a flow with big bandwidth so that it is guaranteed to have no path
Observe errors in kibana and flow history:
<details>
  <summary>kibana</summary>
  
![image](https://user-images.githubusercontent.com/7931639/82434899-356af880-9a9c-11ea-8d2e-2c6c381b2666.png)

</details>

history: [3489_hist.txt](https://github.com/telstra/open-kilda/files/4656160/3489_hist.txt)
error: [3489_errors.txt](https://github.com/telstra/open-kilda/files/4656162/3489_errors.txt)

**Comment by dmitrii-beliakov** [comment]
The issue is no longer reproducible. When creating a flow with bandwidth more than links allow and the path computation strategy `COST_AND_AVAILABLE_BANDWIDTH` in the history there are action messages that are correct:
```
"timestamp": 1690391074,
                "action": "Failed to create the flow",
                "details": "ResourcesAllocationAction failed: Not enough bandwidth or no path found. Switch 00:00:00:00:00:00:00:01 doesn't have links with enough bandwidth, Failed to find path with requested bandwidth=9000000000",
                "timestamp_iso": "2023-07-26T17:04:34.970Z"
```
The same for Kibana:
```
ResourcesAllocationAction failed: Not enough bandwidth or no path found. Switch 00:00:00:00:00:00:00:01 doesn't have links with enough bandwidth, Failed to find path with requested bandwidth=9000000000

```
