### ISSUE TITLE
v2 API is missing payload validations when creating a flow

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3491]
In v1 there's a number of validations applied to the flow payload, for example: flowId cannot be empty or port number/vlan cannot be negative etc..
In v2 all these validations are missing, allowing to create broken flows. Existence of such flows in the database also breaks flow-related v1 APIs.

**Comment by andriidovhan** [comment]
As for me would be great to have the same validation(for the `flowId` field) as in gui(`Only Alphanumeric characters are allowed!`)
for example we can create a flow(`"flowid": "<script>alert(testFlowCreate)</script>
",`) via API, but then as a result we can't do anything with created flow neither API or GUI.
Flow can be deleted directly via DB or `deleteAllFlows` endpoint

**Comment by andriidovhan** [comment]
After creating a flow on the non-existent port, as a result, flow is DOWN and two excess rules on a switch
```
 "excess": [
            36028797031153677,
            -9200854038717923315
        ],
        "excess-hex": [
            "80000000ba000d",
            "805000000000000d"
        ],
```

```

```
