### ISSUE TITLE
QinQ: shared rules are not deleted during sync/update flow after disabling multiTable mode

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#3546]
**Steps to reproduce:**

1. enable multiTable mode on a switch;
2. create a flow(i.e. singleSwFlow)
3. make sure that flow rules are created in multiTable mode
4. update swProps(`"multi_table": false`)
5. make sure that flow rules are still in multiTable mode
6. update the flow;
7. make sure that flow rules are recreated in singleTable mode;

**Actual result:**
shared rules are not deleted
`switchValidation` shows these rules as `excess`

**Expected result:**
shared rules should be deleted

**Comment by niksv** [comment]
Won't fix because single table mode is [deprecated](https://github.com/telstra/open-kilda#deprecation)
