### ISSUE TITLE
Missed cache during path swap after auto reroute

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#3628]
**Steps to reproduce 1:**
1. Create flow with protected path
2. Call API `/v1/flows/{flow_id}/swap`
3. Check kibana logs.

**Expected result:**
**no** messages `Missed cache for switch **** cookie *****` in logs

**Actual result:**
`Missed cache for switch **** cookie *****` messages in logs

**Steps to reproduce 2:**
1. Create flow with protected path and with huge bandwidth (to use all available bandwidth on ISLs)
2. Find some port on main flow path on transit switch
3. Change port status to down
4. Check kibana logs.

**Expected result:**
Failed reroute because of not enough bandwidth
**no** messages `Missed cache for switch **** cookie *****` in logs

**Actual result:**
Failed reroute because of not enough bandwidth
`Missed cache for switch **** cookie *****` messages in logs

**Reason:**
Kilda pushes 2 commands:
1. Swap paths
2. Reroute

Swap path command removes main ingress rules from switch. Stats topology removes records from cache (but all transit and egress rules are still on switches).
Reroute command failed because of non existent path. 

In normal case (if path is found) reroute action removes transit and egress rules and creates new ones. Creating of new rules will update cache records with new cookies.

**Comment by andriidovhan** [comment]
The `Missed cache for switch **** cookie *****` error message can be reproduced with `"System is able to collect stats after intentional swapping flow path to protected"()` autotest
