### ISSUE TITLE
ISL discovery events and processes should be traceable via correlationId 

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#364]
Processing of ISL discovery events leave a trail in the form of log messages produced by different system components. These messages are recorded separately with minimal (or sometimes no) common context. So currently the task of finding related messages for the same event is non-trivial and time consuming. 

Unique correlationId assigned to an event and passed through processing steps will make locating of  corresponding messages much easier, and give a complete picture on how it's performed.

The changes to be done:
- Classes in Floodlight modules that consume Floodlight events must generate and assign a unique ID to each event. This ID must be set in outgoing messages as correlationId.
- Floodlight, TopologyEngine and Storm bolts must put provided correlationId into the logger context in order to have it logged along with each message. 
- **TBD**: discovery packets sent to switches should be supplied with correlationId. And when a packet comes back from a switch, the correlationId should be extracted and used as the context.

**Comment by pzakatov** [comment]
@sergii-iakovenko where is PR for that issue? It can't be #379 (should be smaller).

**Comment by surabujin** [comment]
I believe Nikita mean to pass correlationId inside discovery message, to be able to track ISL discovery/failure event till the end.

**Comment by sergii-iakovenko** [comment]
The correlationId changes are located in misc/floodlight_intro_correlationcontext, misc/wfm_bolts_put_correlationid_in_mdc and misc/northbound_cleanup_handling_correlationid branches.

**Comment by sergii-iakovenko** [comment]
@surabujin Pls, prepare a PR for https://github.com/surabujin/open-kilda/commits/issue/364

**Comment by pzakatov** [comment]
outdated
