### ISSUE TITLE
Server42 stops tracking a flow if flow rtt is disabled only one endpoint, but still available on the other (same pop)

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3710]
Given: 2 switches connected to the same server42 (same pop)
1. Turn on flow rtt feature on both switches. Global server42 toggles should be also enabled
2. Create a flow with these switches as src/dst endpoints
// at this point flow rtt stats should be available in forward and reverse direction
3. Turn off flow rtt feature on dst switch only
**Expected:** rtt stats are no longer available for reverse direction, but still available for forward direction
**Actual:** rtt stats are no longer available for given flow in any direction. Flow is completely removed from server42

**Comment by niksv** [comment]
Possible closed by #3853 
Need to check

**Comment by rtretyak** [comment]
System continues to write 0 values for reverse direction, not sure if this is ok

**Comment by rtretyak** [comment]
not reproducing anymore
