### ISSUE TITLE
Add "Rule Sync" to SWITCH ACTIVATION

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#372]
SUMMARY: Validate Switch Flows on Switch Activated event - ie ensure it has the rules we think it should have; no more, no less.

KEY FEATURES:
- [x] There needs to be a flag in TE that determines whether this feature is enabled (ie a policy variable / boolean .. **sync_rules_on_activation** .. if true, do it, otherwise don't)
- [x] There should be a NB API that allows us to toggle **sync_rules_on_activation**
- [x] Leverage flow_segments to determine what flows should exist
- [x] CHANGE - DON'T DO THIS - Create uninstall commands (and send to floodlight) for switch rules that shouldn't be there. 
- [x] CHANGE - DO THIS - generate and log an error statement for rules that kilda thinks shouldn't be there
- [x] Create install commands for switch rules that should be there
- [x] Remember that there may be 3 base rules that will not show up in flow_segments. These base rules may be on all switches. This sync shouldn't install those base rules .. that'll be a separate activity.
- [x] Log an INFO message for any rule changes
- [x] Ensure all messages use the same correlation ID.
- [x] This command can be invoked through the NB API .. is /switch/{id}/sync_rules
- [x] The NB API should return the results - IGNORED RULES, INSTALLED RULES, SHOULD-DELETE RULES, UNCHANGED RULES (ie in the db and switch)
- [x] IGNORED RULES - start with adding the cookies of the default rules; we may add more to this "IGNORE" list.

NOTES:

1. this relies on all switch rules being stored in the DB beforehand (e.g. “PUSH FLOWS” or prior run)
2. FT flowCache and the DB should be in sync - the FT shouldn't need to do anything
3. Switch ADDED / ACTIVATED events should flow as they do today
4. Upon receiving the SWITCH ACTIVATED event, TE can issue the command to FL to dump the flows
5. FL to send the dumped flows on the kilda.flow topic
6. FT to forward the dumped flows to TE .. FT is in the middle to facilitate future changes / actions
7. Upon receiving the DUMPED FLOWS from, TE can create the install / uninstall commands
8. When invoking this command manually from the NB API, it should send a new request type.

**Comment by jonvestal** [comment]
Actually 3 base rules on everything except Acton.

We should be able to fire this off ad-hoc against a switch.

We should be able to have this "regularly" check as we have seen switches just drop rules.

**Comment by surabujin** [comment]
@carmine This task requires persistent/shared "flag". So this comment https://github.com/telstra/open-kilda/issues/374#issuecomment-375212362 is meaningful for it too.
