### ISSUE TITLE
Make flow states more granular and self-explainable and add last_state_change timestamp

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#375]
The flow state is currently stored in the Flow Topology. If a flow goes down, it is tracked there, but not in the database.

This feature is to propagate flow state to the database - from the very beginning of a request to the end. There is already an "ALLOCATED" state. Most likely need to add:
- INSTALLING
- FAILED-INSTALL
- UP
- DOWN (or FAILED-REROUTE)
- UNINSTALLING
- FAILED-UNINSTALL

Key Features:
- [ ] - the state updates should leverage the timestamp to ensure an old state value doesn't overwrite a newer state value
- [ ] - the timestamp will need to be stored in the db (presumably last_update or last_state_change)
- [ ] - need to clarify when each state value occurs (ie where in the code it emanates from)

**Comment by jonvestal** [comment]
And for down/failed/uninstalling need to be able to inform user why it is in that state.  Thinking bandwidth not available, path not available, etc.

**Comment by surabujin** [comment]
On this moment all flow operations already over complicated and messed up. Can we deal with "defining piplines and "messaging" issues first?

Implementing this issue now will significantly increase chaos level in flow logic.

**Comment by carmine** [comment]
Related to #472 - Hub and Spoke
