### ISSUE TITLE
Add "DELETE_SWITCH_RULES" to NB API

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#376]
This is a primitive command to delete all switch rules on a switch. The default behavior should keep the default rules (ie the the discovery rule and the drop-in-no-match rule). 

**This should not update the Flow Topology or the DB** - we have delete_flow command for that (it will delete a specific set of rules on all switches).

Key Features:
- [ ] The command should go between NB and FL
- [ ] There should be a flag that describes what to do about the default rules:  [DROP, DROP_ADD, IGNORE, OVERWRITE-
  - DROP - drop all rules, including base rules
  - DROP_ADD - drop all rules (ie DROP), then add the base rules back (discovery, drop unmatched)
  - IGNORE - drop all non-base rules (ie don't drop the base rules, leave them alone)
  - OVERWRITE - This is the same as IGNORE and ADD - ie drop all non-base rules, and install the base rules again
- [ ] Similar to the NB API for delete all flows  (ie DELETE .../flows), **use EXTRA_AUTH** in order for this command to work. Just requires an extra step to make this call; it is designed to help prevent accidentally calling this.

**Comment by jonvestal** [comment]
i think we need to add something like we did for the other delete so it can't be triggered by accident

**Comment by carmine** [comment]
Add a checklist item for this .. ie **EXTRA_AUTH**
