### ISSUE TITLE
FlowOperationsService reports DB access errors as Warns

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3768]
DB access errors are reported with log level WARN, should be Error.
I would also expect any transaction exceptions or exhaustment of retry attempts to be reported as Error.
```
TX retry attempts exceed with error
Retrying transaction finished with exception
```
[example1.txt](https://github.com/telstra/open-kilda/files/5347921/example1.txt)
[example2.txt](https://github.com/telstra/open-kilda/files/5347925/example2.txt)
![image](https://user-images.githubusercontent.com/7931639/95461384-d6404e80-097e-11eb-9256-1dc611809fac.png)

**Comment by sergii-iakovenko** [comment]
Closing as not actual. Retry logic for transactions was refactored since the issue was reported.
