### ISSUE TITLE
Server42 turning rule should be always installed if global toggle is 'on'

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3809]
System should install server42 'turning rule' based only on global server42 feature toggle. Example: if global toggle is on and even if server42 rtt switch property is turned off system still should install the turning rule, so that flows that have server42 attached only to 1 endpoint could generate rtt  stats _without installing a dummy server42 switch properties on the second endpoint_ (so that turning rule is installed).
AC:
- server42 turning rule (`-9223372036854775781` / `800000000000001b`) presence on switch is as follows:
  - global toggle true, switch toggle true; rule **installed**
  - global toggle true, switch toggle false; rule **installed**
  - global toggle false, switch toggle true; rule **not installed**
  - global toggle false, switch toggle false; rule **not installed**
- switch validation/synchronization respects the above requirements
- when global server42 toggle changes state, all switches should be synchronized (with remove excess = true)
- rule should not be installed and override the above requirements if switch does not support such type of rule (missing switch features)

**Comment by niksv** [comment]
We have 2 server42 toggles
1. global server42Rtt toggle (one in whole system)
2. server42 switch property (per switch)

Now turning rule will be install on switch in both toggles are true.

There are two ways to solve the problem
1. (quick) just install server42 'turning rule' always, regardless server42 toggles
2. (right) install server42 'turning rule' if global server42Rtt toggle is `True`, regardless per switch server42 property

To implement the second option we need to add switch synchronization(for all switches) when we change server42Rtt global feature toggle.

**Comment by rtretyak** [comment]
We'll go with the second option and rely on the global toggle. I've updated the ticket

**Comment by niksv** [comment]
Implemented in #3853
