### ISSUE TITLE
partialUpdate(pathComputationStrategy/ignoreBandwidth) is reinstalling flow rules

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#3896]
**Steps to reproduce:**

1. create a flow;
2. get flow rules;
3. update the flow via `partialUpdate` (`pathComputationStrategy` or `ignoreBandwidth`);
4. make sure that flow is `UP` and the flow is really updated;
5. get flow rules and compare them with rules from item2.

**Expected result:**
The flow is partially updated without reinstalling its rules.

**Actual result:**
The flow was partially updated and flow rules were reinstalled.

**Comment by vkhalin** [comment]
actual result works correctly. If we change path computation strategy it will reinstall rules
