### ISSUE TITLE
Allow the user to override default settings of the rule - the PRIORITY, the MASK, the COOKIE.

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#398]
A method has been added to ISwitchManager / SwitchManager in FL. This should be plumbed through to NB API.

**Comment by surabujin** [comment]
Which one priority should be configurable? At this point we use 2(but should use 3) priority - ISL match rule(now mutch flow's rule priority but is should be "above" them), flow rules, drop rule.

Which "mask" are you meaning here? Mask for cookie? I don't quite sure why for we apply any mask on cookie value. Invalid (too narrow or removing meaningfull part of our cookie value) cookie value can lead to unpredictable behaviour during OFRules updates/removes.

All other masks used in OFRules match field can't(must not) be configurable from user side.

Is the goal of this changes are correct position kilda's OFRules relatively to not kilda's OFRules? Perhaps will be easier to use "separate" OF tables for kilda and not kilda rules? As far as I understand the only requirements to be able to do it - is support at least 2 OF tables on all supported switches.
