### ISSUE TITLE
ISL rarely may not be properly discovered after port flapping

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#3990]
1. Port down happens and ISL status changes to FAILED
2. Port up happens after ~10 seconds (10s = antiflapCooldown)
**Expected:** ISL status changed to DISCOVERED
**Actual:** ISL status _does_ change to UP for 0.5 seconds but then again changes to DOWN and remains DOWN.
Seems to be a floating issue, not easy to reproduce
Full logs of the related period: 
[elasticsearsh_dump1734.json.gz](https://github.com/telstra/open-kilda/files/5826006/elasticsearsh_dump1734.json.gz)
second appeareance: 
[elasticsearsh_dump1737.json.gz](https://github.com/telstra/open-kilda/files/5826051/elasticsearsh_dump1737.json.gz) `("port event" OR "changed status" OR loggerName: org.openkilda.wfm.topology.network.controller.AntiFlapFsm) AND "00:00:00:00:00:00:00:01_2"`

![image](https://user-images.githubusercontent.com/7931639/104839792-2eff7b80-58cc-11eb-8206-99e929954839.png)

**Comment by rozdy** [comment]
dump1734: Probably root cause is the race condition beetwean two network dumps (from regions 1 and 2) with different status of port 2 on 00:00:00:00:00:00:00:01 switch.
