### ISSUE TITLE
northbound: Add ability for loading properties from external file

### ISSUE THREAD

**Issue by PinGwynn** [telstra/open-kilda#40]
For now, northbound.properties is compiled in .jar file.

Make able to load it from an external file over "-cf" command line option, like in floodlight.

**Comment by surabujin** [comment]
northbound use spring configuration. It allow us to override as single property in CLI arguments so and all required properties by passing custom properties file.

For example to pass kafka host address:

    java -jar ./target/northbound.jar  --kafka.hosts=test2.local:9092


To pass custom properties file:

    java -jar ./target/northbound.jar --spring.config.location=file:/tmp/ --spring.config.name=tmp

[Spring documetation related to properties overriding](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files)

**Comment by PinGwynn** [comment]
@surabujin thank you. This approach is suitable. I think it should be documented.
