### ISSUE TITLE
FLOW LCM ... not picking up Flows from Neo

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#400]
When the Flow Topology (and/or other topologies with it) are lifecycled, then the Flow Topology flowcache may not be in sync with the flows in Neo4j.

**Comment by surabujin** [comment]
Till now there is no any attempts to fetch any persistent state in "flow" topology. So this feature must be implemented from scratch.

**Comment by surabujin** [comment]
Implemented in https://github.com/telstra/open-kilda/pull/446
