### ISSUE TITLE
Swap endpoints on server42-enabled switch leaves excess rules

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#4003]
1. 2 flows, one of the switches has server42 rules installed
 2. Swap switches on those flows (flow1 new src switch = flow2 old dst switch)
 3. Validate switches
 **Expected:** All rules are proper
**Actual:** SERVER42_INPUT rules are put to 'excess' section

reproducible by autotests, search using ticket number

**Comment by andriidovhan** [comment]
It is not reproduced anymore.
