### ISSUE TITLE
Protected flow may remain on the broken main path due to double swap

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#4034]
Issue is sometimes observed during tests run. Steps:
1. Given a flow with protected path
2. Break main path
**Expected:** Flow immediately swaps to protected path and remains there
**Actual:** Sometimes two swap requests are generated, swapping the flow to protected and then in a matter of milliseconds back to the main path (which is broken)

Originally occurred in test `"System is able to switch #flowDescription flows to protected paths"`, but is not easily reproduced locally
Logs that show the problem: [elasticsearsh_dump_4034.json.gz](https://github.com/telstra/open-kilda/files/5925444/elasticsearsh_dump_4034.json.gz) (flow 03Feb120245_892_chestnut3301)

The issue is severe, but setting priority to 'normal' as it looks like pretty rare

**Comment by niksv** [comment]
For some reason two swap path commands were generated for flow `03Feb120245_892_chestnut3301`. Both commands were put into queue and applied one by one. To find affected flows Kilda tries to find affected paths and filter only paths which IDs are equal to flow primary forward path. For some reasons two paths were filtered

**Comment by rtretyak** [comment]
This reproduces pretty often during tests. Ignoring the test and making priority higher here
