### ISSUE TITLE
Async request processing in Northbound

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#405]
Re-implement the Northbound and Kafka communication approach. 

The potential solution looks like:
1. Create a new layer between NB services and kafka producers/consumers. It will manage all async requests and should return CompletableFuture.
2. Create simple mechanism to get the response.
3. The response dispatcher may reject new request if there're too many requests being processed. (to be discussed)
4. Use the CompletableFuture as the REST method result.

- The response dispatcher should subscribe on DeferredResult events 
(onTimeout and others) and react correspondingly. E.g. removes a correlationId->CompletableFuture entry if it waits a response for too long (timeout happens).

**Comment by nikitacherevko** [comment]
Updated description due to latest offline discussion.
