### ISSUE TITLE
Write ATDD: Deleting the DROP RULE deletes all rules

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#414]
During testing, when we ran the delete drop rule command:

curl -H "${AUTH}" -H "${CORR}" -H "${CONT}" -H "EXTRA_AUTH: 1522328668125" -X DELETE http://{northbound-url}/api/v1/switches/{switch-id}/rules?delete-action=REMOVE_DROP

It deleted all rules on the switch. It returned a single cookie, so presumably it thought it did the right thing. However, the function that deletes a single rule, given a cookie, might not be doing the right thing.

[UPDATE 2018.04.03] This should be fixed, based on (commit # tbd) - the bug was that the cookie mask wasn't added, which effectively means no match rules were used. Switches will delete all rules in this scenario.

- [ ] TODO: Write the ATDD test that validates this behavior.

**Comment by rtretyak** [comment]
covered in functional-tests
