### ISSUE TITLE
[multiTable] system is not switching flow to singleTable mode after updating vlanId

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#4170]
**Steps to reproduce:**

1. find switchPair with enabled multiTable mode;
2. create a flow on the founded switchPair; 
3. update swProps on the src switch (`"multi_table": true ->false`)
4. update the srcVlanId on the flow;

**Expected result:**
The flow should change: 
- the mode to singleTable on the src switch;
- `src_with_multi_table` flag of FlowPath in DB.
- old multiTable flow rules are not deleted and they are considered as excess rules;

**Actual result:**
- flow mode is not changed;
- `src_with_multi_table` flag of FlowPath in DB is not changed;
- flow rules on src switch are still in the multiTable mode

**Comment by rtretyak** [comment]
Lowering priority since we are going to deprecate the single-table mode

**Comment by niksv** [comment]
Won't fix because single table mode is [deprecated](https://github.com/telstra/open-kilda#deprecation)
