### ISSUE TITLE
Current NP API collects responses. Ensure old/zombie responses are removed.

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#427]
There should be a mechanism to delete old messages.  Ideally, we could maintain a list of outstanding requests outside of the current correlation mechanism.

With this separate list, we could ensure that any response that doesn't match an existing request is deleted.

**Comment by sergii-iakovenko** [comment]
Pls, consider the solution described in #405.

**Comment by pzakatov** [comment]
outdated
