### ISSUE TITLE
Include Port Status in ISL latency stats 

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#43]
Capture the latency data from an ISL discovery packet and dump it as a stat, using "pen.isl.latency".

Tag with LINK ID and switch/port information (ie ID), as well as state.

**Comment by jonvestal** [comment]
Is t this done?

**Comment by carmine** [comment]
Most of it is in master. The Port status isn't captured yet.

**Comment by pzakatov** [comment]
done
