### ISSUE TITLE
What's the special authorization required for DELETING the flows

### ISSUE THREAD

**Issue by NandanBharadwaj** [telstra/open-kilda#4326]
![image](https://user-images.githubusercontent.com/23073204/122543535-75fdc280-d05e-11eb-823a-aff031a09e32.png)

**Comment by surabujin** [comment]
At the start of the project most API was used by "hands" and this kind "authorization" was introduced to prevent accidental removal of important resources.

Whe API is used by some application this "authoreization" have no sence (application can calculate correct value of authorization token and provide it into request). So at this moment it still exist to keep original API compatibility.

**Comment by niksv** [comment]
@NandanBharadwaj Hi, it requires special header "EXTRA_AUTH"

If you will try to send request with special authorization you will get next response
```
curl -u user:password -X DELETE "http://localhost:8080/api/v1/flows" -H "accept: */*"
Invalid Auth: 1624010570092
```

To send correct response you need sent request with header "EXTRA_AUTH" and received magic number (1624010570092 in our case).

```
curl -u user:password -X DELETE "http://localhost:8080/api/v1/flows" -H "accept: */*" -H "EXTRA_AUTH: 1624010570092"
[]
```
This magic number is just current epoch time. If current server time and EXTRA_AUTH in your request are different more than 2 minutes - request will be rejected.
The whole extra authorization is needed to do not send danger operations by mistake. That is why EXTRA_AUTH field is missed in swagger.

**Comment by NandanBharadwaj** [comment]
@surabujin @niksv Thanks for your response, that worked. I think as a follow up the DELETE button for the flow in the GUI should somehow be enabled with this. And the documentation in the API doc. Let me know if I can help on that part.
