### ISSUE TITLE
Flow between multitable and non-multitable switches has invalid path properties

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#4339]
A flow created / updated / rerouted between multitable and non-multitable switches eventually gets a path with invalid src_with_multi_table / dst_with_multi_table properties. As the result, Kilda ignores such path on the next update / reroute and leaves excess rules on the path switches.

**Comment by rtretyak** [comment]
Had no luck with reproducing this on actual codebase.
Tried all combinations of creating flow with multi/single-table endpoint switches, tried changing switch modes after/before creating the flow, rerouting the flow after doing the change. Also, non of the existing autotest scenarios is able to reproduce it.
The described issue may be a leftover db inconsistency after the migration in #3946

**Comment by niksv** [comment]
Won't fix because single table mode is [deprecated](https://github.com/telstra/open-kilda#deprecation)
