### ISSUE TITLE
[flowHistory] 'stateBefore' section is present twice for the "Flow deleting" action

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#4391]
**Steps to reproduce:**

1. create any flow (oneSwitchFlow/multiSwitchFlow)
2. delete the flow

**Expected result:**
one section should be present 

**Actual result:**
the 'stateBefore' section is present twice for the "Flow deleting" action

```
{
        "clazz": "org.openkilda.messaging.payload.history.FlowHistoryEntry",
        "flow_id": "testSwitchFlow_history",
        "timestamp": 1627288517,
        "action": "Flow deleting",
        "task_id": "3e11fd54-fcaa-4e06-8af9-fed4f0e9f435 : adovhan_postman_deleteFlowV2",
        "payload": [
            {
                "timestamp": 1627288517,
                "action": "Flow was validated successfully",
                "details": null
            },
...
            {
                "timestamp": 1627288518,
                "action": "Flow was deleted successfully",
                "details": null
            }
        ],
        "dumps": [
            {
                "type": "stateBefore",
                "bandwidth": 835,
                "ignoreBandwidth": false,
                "forwardCookie": 4611686018427424405,
                "reverseCookie": 4611686018427424405,
                "sourceSwitch": "00:00:00:22:3d:5a:04:87",
                "destinationSwitch": "00:00:00:22:3d:5a:04:87",
                "sourcePort": 25,
                "destinationPort": 23,
                "sourceVlan": 11,
                "destinationVlan": 12,
                "sourceInnerVlan": 0,
                "destinationInnerVlan": 0,
                "forwardMeterId": 1532,
                "reverseMeterId": 1532,
                "forwardPath": "[{\"switch_id\":\"00:00:00:22:3d:5a:04:87\",\"input_port\":25,\"output_port\":23}]",
                "reversePath": "[{\"switch_id\":\"00:00:00:22:3d:5a:04:87\",\"input_port\":25,\"output_port\":23}]",
                "forwardStatus": "ACTIVE",
                "reverseStatus": "ACTIVE",
                "groupId": null,
                "allocateProtectedPath": false,
                "pinned": false,
                "periodicPings": false,
                "encapsulationType": "TRANSIT_VLAN",
                "pathComputationStrategy": "COST",
                "maxLatency": 0,
                "loopSwitchId": null
            },
            {
                "type": "stateBefore",
                "bandwidth": 835,
                "ignoreBandwidth": false,
                "forwardCookie": 2305843009213730453,
                "reverseCookie": 2305843009213730453,
                "sourceSwitch": "00:00:00:22:3d:5a:04:87",
                "destinationSwitch": "00:00:00:22:3d:5a:04:87",
                "sourcePort": 25,
                "destinationPort": 23,
                "sourceVlan": 11,
                "destinationVlan": 12,
                "sourceInnerVlan": 0,
                "destinationInnerVlan": 0,
                "forwardMeterId": 1533,
                "reverseMeterId": 1533,
                "forwardPath": "[{\"switch_id\":\"00:00:00:22:3d:5a:04:87\",\"input_port\":23,\"output_port\":25}]",
                "reversePath": "[{\"switch_id\":\"00:00:00:22:3d:5a:04:87\",\"input_port\":23,\"output_port\":25}]",
                "forwardStatus": "ACTIVE",
                "reverseStatus": "ACTIVE",
                "groupId": null,
                "allocateProtectedPath": false,
                "pinned": false,
                "periodicPings": false,
                "encapsulationType": "TRANSIT_VLAN",
                "pathComputationStrategy": "COST",
                "maxLatency": 0,
                "loopSwitchId": null
            }
        ]
    }
```

**Comment by artHalMirantis** [comment]
reproduced on the develop branch after merge

Actual result: stateBefore is presented 4 times for the flow delete action

`{
        "clazz": "org.openkilda.messaging.payload.history.FlowHistoryEntry",
        "flow_id": "22Apr181345_454_bonza2109",
        "timestamp": 1658917722,
        "timestamp_iso": "2022-07-27T10:28:42.462Z",
        "action": "Flow deleting",
        "task_id": "5069e5c9-1d91-4f38-815b-09caa8c2437f : consectetur labore sint",
        "payload": [
            {
                "timestamp": 1658917722,
                "action": "Flow was validated successfully",
                "details": null,
                "timestamp_iso": "2022-07-27T10:28:42.462Z"
            },
            …
            {
                "timestamp": 1658917723,
                "action": "Flow was deleted successfully",
                "details": null,
                "timestamp_iso": "2022-07-27T10:28:43.464Z"
            }
        ],
        "dumps": [
            {
                "type": "stateBefore",
                "bandwidth": 500,
                "ignoreBandwidth": false,
                "forwardCookie": 4611686018427420905,
                "reverseCookie": 4611686018427420905,
                "sourceSwitch": "00:00:00:00:00:00:00:04",
                "destinationSwitch": "00:00:00:00:00:00:00:01",
                "sourcePort": 10,
                "destinationPort": 11,
                "sourceVlan": 2859,
                "destinationVlan": 610,
                "sourceInnerVlan": 0,
                "destinationInnerVlan": 0,
                "forwardMeterId": 2246,
                "reverseMeterId": 2246,
                "forwardPath": "[{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":10,\"output_port\":1},{\"switch_id\":\"00:00:00:00:00:00:00:02\",\"input_port\":2,\"output_port\":4},{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":1,\"output_port\":11}]",
                "reversePath": "[{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":10,\"output_port\":1},{\"switch_id\":\"00:00:00:00:00:00:00:02\",\"input_port\":2,\"output_port\":4},{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":1,\"output_port\":11}]",
                "forwardStatus": "ACTIVE",
                "reverseStatus": "ACTIVE",
                "diverseGroupId": "46bb2413-bdc7-4a94-84fb-00dce55df9b9",
                "affinityGroupId": null,
                "allocateProtectedPath": true,
                "pinned": false,
                "periodicPings": false,
                "encapsulationType": "TRANSIT_VLAN",
                "pathComputationStrategy": "COST_AND_AVAILABLE_BANDWIDTH",
                "maxLatency": 0,
                "loopSwitchId": null
            },
            {
                "type": "stateBefore",
                "bandwidth": 500,
                "ignoreBandwidth": false,
                "forwardCookie": 2305843009213726954,
                "reverseCookie": 2305843009213726954,
                "sourceSwitch": "00:00:00:00:00:00:00:04",
                "destinationSwitch": "00:00:00:00:00:00:00:01",
                "sourcePort": 10,
                "destinationPort": 11,
                "sourceVlan": 2859,
                "destinationVlan": 610,
                "sourceInnerVlan": 0,
                "destinationInnerVlan": 0,
                "forwardMeterId": 33,
                "reverseMeterId": 33,
                "forwardPath": "[{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":11,\"output_port\":2},{\"switch_id\":\"00:00:00:00:00:00:00:07\",\"input_port\":15,\"output_port\":50},{\"switch_id\":\"00:00:00:00:00:00:00:08\",\"input_port\":7,\"output_port\":16},{\"switch_id\":\"00:00:00:00:00:00:00:03\",\"input_port\":6,\"output_port\":4},{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":4,\"output_port\":10}]",
                "reversePath": "[{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":11,\"output_port\":2},{\"switch_id\":\"00:00:00:00:00:00:00:07\",\"input_port\":15,\"output_port\":50},{\"switch_id\":\"00:00:00:00:00:00:00:08\",\"input_port\":7,\"output_port\":16},{\"switch_id\":\"00:00:00:00:00:00:00:03\",\"input_port\":6,\"output_port\":4},{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":4,\"output_port\":10}]",
                "forwardStatus": "ACTIVE",
                "reverseStatus": "ACTIVE",
                "diverseGroupId": "46bb2413-bdc7-4a94-84fb-00dce55df9b9",
                "affinityGroupId": null,
                "allocateProtectedPath": true,
                "pinned": false,
                "periodicPings": false,
                "encapsulationType": "TRANSIT_VLAN",
                "pathComputationStrategy": "COST_AND_AVAILABLE_BANDWIDTH",
                "maxLatency": 0,
                "loopSwitchId": null
            },
            {
                "type": "stateBefore",
                "bandwidth": 500,
                "ignoreBandwidth": false,
                "forwardCookie": 4611686018427420906,
                "reverseCookie": 4611686018427420906,
                "sourceSwitch": "00:00:00:00:00:00:00:04",
                "destinationSwitch": "00:00:00:00:00:00:00:01",
                "sourcePort": 10,
                "destinationPort": 11,
                "sourceVlan": 2859,
                "destinationVlan": 610,
                "sourceInnerVlan": 0,
                "destinationInnerVlan": 0,
                "forwardMeterId": 2247,
                "reverseMeterId": 2247,
                "forwardPath": "[{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":10,\"output_port\":4},{\"switch_id\":\"00:00:00:00:00:00:00:03\",\"input_port\":4,\"output_port\":6},{\"switch_id\":\"00:00:00:00:00:00:00:08\",\"input_port\":16,\"output_port\":7},{\"switch_id\":\"00:00:00:00:00:00:00:07\",\"input_port\":50,\"output_port\":15},{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":2,\"output_port\":11}]",
                "reversePath": "[{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":10,\"output_port\":4},{\"switch_id\":\"00:00:00:00:00:00:00:03\",\"input_port\":4,\"output_port\":6},{\"switch_id\":\"00:00:00:00:00:00:00:08\",\"input_port\":16,\"output_port\":7},{\"switch_id\":\"00:00:00:00:00:00:00:07\",\"input_port\":50,\"output_port\":15},{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":2,\"output_port\":11}]",
                "forwardStatus": "ACTIVE",
                "reverseStatus": "ACTIVE",
                "diverseGroupId": "46bb2413-bdc7-4a94-84fb-00dce55df9b9",
                "affinityGroupId": null,
                "allocateProtectedPath": true,
                "pinned": false,
                "periodicPings": false,
                "encapsulationType": "TRANSIT_VLAN",
                "pathComputationStrategy": "COST_AND_AVAILABLE_BANDWIDTH",
                "maxLatency": 0,
                "loopSwitchId": null
            },
            {
                "type": "stateBefore",
                "bandwidth": 500,
                "ignoreBandwidth": false,
                "forwardCookie": 2305843009213726953,
                "reverseCookie": 2305843009213726953,
                "sourceSwitch": "00:00:00:00:00:00:00:04",
                "destinationSwitch": "00:00:00:00:00:00:00:01",
                "sourcePort": 10,
                "destinationPort": 11,
                "sourceVlan": 2859,
                "destinationVlan": 610,
                "sourceInnerVlan": 0,
                "destinationInnerVlan": 0,
                "forwardMeterId": 32,
                "reverseMeterId": 32,
                "forwardPath": "[{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":11,\"output_port\":1},{\"switch_id\":\"00:00:00:00:00:00:00:02\",\"input_port\":4,\"output_port\":2},{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":1,\"output_port\":10}]",
                "reversePath": "[{\"switch_id\":\"00:00:00:00:00:00:00:01\",\"input_port\":11,\"output_port\":1},{\"switch_id\":\"00:00:00:00:00:00:00:02\",\"input_port\":4,\"output_port\":2},{\"switch_id\":\"00:00:00:00:00:00:00:04\",\"input_port\":1,\"output_port\":10}]",
                "forwardStatus": "ACTIVE",
                "reverseStatus": "ACTIVE",
                "diverseGroupId": "46bb2413-bdc7-4a94-84fb-00dce55df9b9",
                "affinityGroupId": null,
                "allocateProtectedPath": true,
                "pinned": false,
                "periodicPings": false,
                "encapsulationType": "TRANSIT_VLAN",
                "pathComputationStrategy": "COST_AND_AVAILABLE_BANDWIDTH",
                "maxLatency": 0,
                "loopSwitchId": null
            }
        ]
    }
`
