### ISSUE TITLE
SERVER_42_FLOW_RTT_INGRESS_FORWARD is misconfigured for vxlan flow in singleTable mode

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#4708]
**Steps to reproduce:**

1. find switch pair in `signleTable` mode with active s42;
2. create a `vxlan` flow on the switchPair;

**Expected result:** 
No misconfigured rules

**Actual result:**
The `SERVER_42_FLOW_RTT_INGRESS_FORWARD` rule is misconfigured.

**NOTE:**
The issue is reproduced on a real switch. (not ovs)

**Comment by niksv** [comment]
Won't fix because single table mode is [deprecated](https://github.com/telstra/open-kilda#deprecation)
