### ISSUE TITLE
Finalize Flow Validation - discovery / comparison criteria.

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#471]
The current solution mostly works. Current solution:

- The NB API has a /api/v1/flows/{flowid}/validate target.
- The primary code is in the FlowServiceImpl.
- As part of the code, we get switch rules for each switch in the flow path.
- We normalize the flowpath into SimpleSwitchRule, and we normalize the switch rules into the same structure
- We also currently print a debug log statement for each switch rule we receive .. this can be used to finish this task .. to figure out scenarios where we haven't parsed the right information.

At present, it is "mostly correct" - but it finds a couple of discrepancies which are false - ie there should be no discrepancies.  To repeat this, all you need to do is:

1) bring up the controller - ie make up-test-mode
2) bring up the example network topology and the install rules.. run this from the top level directory:
: `make -f base/hacks/usecase/flow.crud.make deploy-flow-topo`
: `make -f base/hacks/usecase/flow.crud.make deploy-flows`
: `make -f base/hacks/usecase/flow.crud.make validate-flows`
--> This last one will report discrepancies, and that is what needs to be fixed.

The Ask:
- [ ] Add an ATDD for this (to the FLOW CRUD ?)
- [ ] Fix the code - ie make the false discrepancies go away

Hints:
- It may be that the sequence of the path is causing the problem .. ie maybe it got the ingress and transit wrong for the reverse direction?  Probably not, but worth validating.
- More likely, it isn't parsing the switch rule correctly and isn't pulling out the values in the right way for the fields.  To resolve this, look at the NB API Log and see what we receive.

**Comment by sergii-iakovenko** [comment]
Resolved by #520.
