### ISSUE TITLE
Add validation for LAG port update request

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#4719]
There is API `/v2/switches/{switch_id}/lags/{logical_port_number}` which allows to add/remove physical ports into LAG group.

We should  allow to decrease the LAG port capacity only to the consumed BW value. So, if for example, we have two ports in a LAG group  (10G each) with 20G total BW and the consumed is 18G, we should not allow to remove the port from the group. 
If the consumed BW is less than 10 G we should allow to remove the port from the lag group

In case of error Kilda must return 400 Bad request response.

**Comment by andriidovhan** [comment]
Should we allow to decrease the LAG port capacity in case the `ignore_bandwidth` field is set to true?
for example
```
- LAG group 20G (two ports - 10G each)
- flow bandwidth is 18G
- `ignore_bandwidth: true`
- delete one port from the LAG group.
```
