### ISSUE TITLE
Move HistoryBolt from FlowHsTopology to separate HistoryTopology

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#4722]
FlowHsTopology has a lot of hub bolts and one HistoryBolt which writes history data into MySQL DB.
If there are too many history records for Mysql Db, History Bolt can slow down whole topology, because each hub will wait until HistoryBolt will finish writing of data, because we use anchor for HistoryBolt. And Hub bolt can't take new tuple for work until HistoryBolt will mark tuple as "finished". 

There are 2 solutions:
1. Do not use anchor for HistoryBolt, But in this case we can lose some history data, because History bolt wouldn't retry to proceed failed tuples again.
2. Move History bolt to separate topology and send History event throw Kafka from FlowHs Topology to History topology

We need to implement solution 2.

**Comment by dpoltavets** [comment]
Resolved by #4730
