### ISSUE TITLE
Updating of LAG port with non existing physical ports causes timeout response

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#4727]
Steps to reproduce:

1. Create valid LAG port via `POST /v2/switches/{switch_id}/lags`:
```
{
  "port_numbers": [
    22
  ]
}
```

2. Update LAG port via `PUT /v2/switches/{switch_id}/lags` with non existing port::
```
{
  "port_numbers": [
    22, 122
  ]
}
```

**Expected result:**
Bad Request

**Actual result:**
Timeout

**Comment by vshakirova** [comment]
Reopen due to rollback
