### ISSUE TITLE
wfm: hardcoded endpoint should be in properties 

### ISSUE THREAD

**Issue by PinGwynn** [telstra/open-kilda#48]
Affected file:
./wfm/src/main/java/org/openkilda/wfm/topology/islstats/IslStatsTopology.java: 
OpenTsdbClient.Builder tsdbBuilder = OpenTsdbClient.newBuilder("http://opentsdb.pendev:4242")

**Comment by surabujin** [comment]
Closed by https://github.com/telstra/open-kilda/pull/71
