### ISSUE TITLE
[y-flow] y-flow validation is not detecting discrepencies for on-switch-Yflow

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#4825]
**Steps to reproduce:**
1. creat one-switch y-flow
2. delete shared rules
3. validate y-flow
4. make sure the deleted rules are are marked as `missing` on a switch

**Expected result:**
yflow validation detects discrepancies

**Actual results:**
y-flow validation is not detecting discrepencies

**Comment by sergii-iakovenko** [comment]
@vkhalin Need to re-validate the fix.

**Comment by artHalMirantis** [comment]
validated
tests passed successfully for the single/multiply switches
