### ISSUE TITLE
Sub flows in Y flow can be diverse to each other

### ISSUE THREAD

**Issue by niksv** [telstra/open-kilda#4961]
**Steps to reproduce:**
1. Create a Y flow
2. Check that sub flow not in the same diverse group (property `diverse_group_id` in orient db is empty)
3. update Y flow to make it diverse with some other flow.
4. Check sub flow diverse group in DB (property `diverse_group_id` in orient db)

**Expected result:** 
sub flows must not be diverse to each other

**Actual result:**
sub flows are in one diverse group

**Comment by surabujin** [comment]
There is a "special" behaviour for affinity flows into path computation component. It ignores diversity settings for flows inside same affinity group (sub flows of y-flow). So despite stored into DB diversity settings, sub flows will ignore them for each other, but still will take into account diversity requirements for other flows (ouside of affinity group).

**Comment by shusyaM** [comment]
Can be closed since it was proved that the subflows are technically not diverse to each other
