### ISSUE TITLE
Cant validate switch (v2 validation) if number of rules more than 1800

### ISSUE THREAD

**Issue by artHalMirantis** [telstra/open-kilda#4966]
1 create 1800+ rules
2 perform switch validation using v2 endpoint [/v2/switches/{switch_id}/validate]

Actual result: northbound: timeout exception with 400 http code
kafka (from kibana) log: The message is 1204811 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.

expected result: right result with all the rules
number of rules flow - to discuss

**Comment by niksv** [comment]
Closed by #4993
