### ISSUE TITLE
Subflows in Y flow are returned in diverse group

### ISSUE THREAD

**Issue by shusyaM** [telstra/open-kilda#4996]
**Steps to reproduce:**

1.  Create a Y flow
2. Check that sub flow not in the same diverse group (property diverse_group_id in orient db is empty)
3. update Y flow to make it diverse with some other flow.
4. Get Y-flow path by Get Y flow path API

**Expected result:**
Sub flows must not be returned in the same diverse group

**Actual result:**
Sub flows are returned in one diverse group

**Comment by niksv** [comment]
Closed by #5185 #5183
