### ISSUE TITLE
northbound: health-check fail if we are running several instances

### ISSUE THREAD

**Issue by PinGwynn** [telstra/open-kilda#50]
Test case:
docker-compose scale northbound=2

result:
On the first instance:
curl -s http://172.18.0.7:8080/api/v1/health-check

{"name":"Northbound","version":"1.0-SNAPSHOT","description":"Northbound API service provides API for Kilda controller","components":{"event-splitter-storm-topology":"operational","flow-storm-topology"
:"operational","event-wfm-storm-topology":"operational","cache-storm-topology":"non-operational","statistics-storm-topology":"operational"}}

On the second one:
curl -s http://172.18.0.8:8080/api/v1/health-check

{"name":"Northbound","version":"1.0-SNAPSHOT","description":"Northbound API service provides API for Kilda controller","components":{"event-splitter-storm-topology":"non-operational","flow-storm-topology"
:"non-operational","event-wfm-storm-topology":"non-operational","cache-storm-topology":"non-operational","statistics-storm-topology":"non-operational"}}

If we stop instance where health-check is ok, non-operational instance comes to the operational state.

This behaviour blocks rolling-updates of northbound on Amazon ECS an example. Because before stops healthy task we must be sure that second task (container) in a healthy state too.

**Comment by surabujin** [comment]
My estimate 1-3d

**Comment by sergii-iakovenko** [comment]
We should consider [Spring Endpoints](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html) as implementation approach for health-checks. It provides extendable and configurable way to expose metrics and health-check information.

**Comment by IlyaMoiseev** [comment]
Fixed in #1357
