### ISSUE TITLE
status info is null in get flow v2

### ISSUE THREAD

**Issue by artHalMirantis** [telstra/open-kilda#5069]
Steps to reproduce:

1. Create a flow from switch A to switch B. The 'ignore_bandwidth' flag should be set to True in the request body. 
2. Update the flow. The value for maximum bandwidth for flow should be more than available bandwidth for the link. For example, the available bandwidth for the link is 1000. So we should set the value for maximum bandwidth for the flow to 1100. The 'ignore_bandwidth' flag should be set to False in the request body. 
3. get flow using v2 api request GET [/v2/flows/{flow_id}]

**Expected**: status info contains readable error like
"Not enough bandwidth or no path found. Failed to find path with requested bandwidth=10000001: Switch 00:00:00:00:00:00:00:01 doesn't have links with enough bandwidth"
**Actual**: status info is null

**Comment by pablomuri** [comment]
This [issue](https://github.com/telstra/open-kilda/issues/3570) explains how the status_info must work and it works correctly. The status_info must be null/empty since the flow is in UP state.
