### ISSUE TITLE
Add new text field for Ticket reference when an ISL is put into maintenance

### ISSUE THREAD

**Issue by shusyaM** [telstra/open-kilda#5072]
A new textfield "Ticket ref" should be added on ISL Details page which should appear only when an ISL is put into maintenance. The textfield should store the current Jira ticket reference number. 
New parameter "ticket_ref" should be added in the backend which should overwritten each time an ISL is put into maintenance.  The parameter should be available in Create/Update link API: TBD
The ticket is based on the request from NOC team: https://peneng.atlassian.net/browse/PM-6986

**Comment by neeraj890kumar** [comment]
@shusyaM I have checked the backend ticket in which the field added in the API is 'description'
https://github.com/telstra/open-kilda/issues/5083
Please confirm if we should label it as Ticket Ref and post data in description or we should label it as Description as well 
Also kindly confirm if user can only add the ticket ref or can also add other text like description related to the ticket?
