### ISSUE TITLE
Include gradle optimization parameters to Makefile 

### ISSUE THREAD

**Issue by dmitrii-beliakov** [telstra/open-kilda#5155]
For better development experience, there is a way to build OpenKilda faster. One way is to optimize gradle tasks:

- cache of already compiled sources, that would speed up things even when switching between branches.
- use parallel mode
- don't show debug messages in the console

The proposal is to try and test the following command for re-building the project, adjust if needed, and then add it to the Makefile for regular use.
```shell
make clean && docker system prune --volumes -f && \
make build-stable GRADLE_COMPILE_PARAMS="--parallel --max-workers 16 --build-cache -q -Dorg.gradle.jvmargs=-Xmx4096M"  \
up-stable test-topology \
```

`--build-cache` sometimes cannot recognize changes (it is more likely when downloading from repos), so it is worth to add a command to clean gradle cache as a separate command (kind of extended clean).

**Comment by niksv** [comment]
Not each CPU has 16 cores. Maybe it's better to set there number of CPU cores? for example `$(shell grep -c 'processor' /proc/cpuinfo)`

**Comment by dmitrii-beliakov** [comment]
yeah, thanks for pointing out 👍. Probably, some sort of profile is needed. I imagine this as something that is easy to change, at the same time it is available in git. I am not sure though how good it is to have, let's say, 4 as a default parallelism parameter that every single dev would change to 8 or 16. 
The target doesn't have to support `/proc/cpuinfo`, as well as this parameter returns the number of logical processors, maybe this is not so efficient.
