### ISSUE TITLE
Remove deprecated feature toggles

### ISSUE THREAD

**Issue by pkazlenka** [telstra/open-kilda#5163]
We have a bunch of obsolete feature toggles that aren't used anymore. It would be great to clean up the code from them.
E.g. we obviously don't need toggles like `createFlowEnabled` or `modifyYFlowEnabled`. 
The list of feature toggles is here: https://github.com/telstra/open-kilda/blob/develop/src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/model/system/FeatureTogglesDto.java

**Comment by pkazlenka** [comment]
@KalebArmbrust , we are happy to receive any help. 
Obsolete feature flags (if any) should be defined by @niksv , I guess.

**Comment by niksv** [comment]
We are opensource project and we can't remove fields from our API so I have to close the ticket. 

@KalebArmbrust Hey! if you want to help you can take one of these issues: 
https://github.com/telstra/open-kilda/issues/862 
https://github.com/telstra/open-kilda/issues/2154

**Comment by KalebArmbrust** [comment]
@niksv I looked at both issues but unfortunately they are unfamiliar to me so I will not be able to help. Best of luck!
