### ISSUE TITLE
link properties not deleted after isl brought to maintenance mode and back again 

### ISSUE THREAD

**Issue by artHalMirantis** [telstra/open-kilda#5270]
Steps to reproduce

1. Open Kilda GUI
2. choose any ISL
3. turn maintenance mode on it
4. bring it back again (maintenance mode = off)
5. get link properties using GET [/v1/link/props]

actual result : properties are on the link
exprected result: no link properties

**Comment by gauravchug** [comment]
@artHalMirantis User have that option to remove it in the popup

**Comment by gauravchug** [comment]
we have added a description field in the ISL detail screen as well and the same field is used in maintenance mode. so user can add description or remove them while putting ISL maintenance mode on/off @artHalMirantis

**Comment by artHalMirantis** [comment]
closing as expected behaviour
