### ISSUE TITLE
error description typo for the HA flow update (one switch case)

### ISSUE THREAD

**Issue by artHalMirantis** [telstra/open-kilda#5302]
1. create ha flow
2. try to update to one-switch ha flow
3. get error

actual result: example
The ha-flow 24Jul120617_041_tapiocaflour2122 is one switch flow. At lease one of subflow endpoint switch id must differ from shared endpoint switch id 00:00:00:00:00:00:00:02'

expected result: word "least" , not the "lease"

**Comment by pablomuri** [comment]
Already fixed
