### ISSUE TITLE
Don't run pre-test healthcheck when just one test is being launched.

### ISSUE THREAD

**Issue by pkazlenka** [telstra/open-kilda#5345]
At the moment, each time when we launch tests, we call `HealthCheckSpecification.healthCheck()` method to verify if the environment is clean and is ready to run tests. 
It isn't a problem when we run a lot of test at once, but during tests development it is: time to finish all the checks is significant comparing to the time to run the test itself.
So, we need to add some mechanism to:
1. Detect if test run doesn't need to run healthcheck. I guess we can receive a list of tests of current test run using spock API. Then, if the whole run is only one test case, we can say that it is definitely not a full or partial regression run, but just launch of single tests from developer's machine during the test development process. Or may be there are better ideas.
2. Skip healthcheck if we don't run regression.
3. There should be ability to force run healthcheck even for single test case run. E.g. configuration variable on environment variable.

**Comment by yuliiamir** [comment]
The appropriate changes have been added in the scope of https://github.com/telstra/open-kilda/pull/5354.
