### ISSUE TITLE
Ha-Flow: History: Deletion action: The confirmation action about flow deletion  is absent in the history.payload

### ISSUE THREAD

**Issue by yuliiamir** [telstra/open-kilda#5367]
The confirmation action "HA-flow has been deleted successfully" about flow deletion  is absent in the history.payload.
STR:
1. Create Ha-Flow.
2. Delete Ha-Flow.
3. Get history record.
Actual result: 
`{
    "clazz": "org.openkilda.messaging.payload.history.HaFlowHistoryEntry",
    "ha_flow_id": "07Sep101115_325_edamame2247",
    "time": 1694074498.378,
    "timestamp_iso": "2023-09-07T08:14:58.378Z",
    "action": "HA-Flow delete",
    "task_id": "b20d6f3b-5184-4249-b21f-7f3e9d67d40e : fn-tests-1350fd22-eff4-481e-997e-01711371e371",
    "payloads": [
      {
        "timestamp": 1694074498.378,
        "timestamp_iso": "2023-09-07T08:14:58.378Z",
        "action": "HA-Flow delete",
        "details": null
      },
      {
        "timestamp": 1694074498.847,
        "timestamp_iso": "2023-09-07T08:14:58.847Z",
        "action": "HA-flow path has been removed",
        "details": "The following HA-path has been removed: 07Sep101115_325_edamame2247_926f06cf-d3a1-4221-96ea-461bafd75223"
      },
      {
        "timestamp": 1694074498.856,
        "timestamp_iso": "2023-09-07T08:14:58.856Z",
        "action": "HA-flow path has been removed",
        "details": "The following HA-path has been removed: 07Sep101115_325_edamame2247_a3c07dba-587b-47ed-8948-e6279ce4c5f1"
      }
    ],
    "dumps": []`

Expected result: 
The last action after _HA-flow path has been removed_ should be the action about the flow deletion confirmation **HA-flow has been deleted successfully** (the same logic we have for the regular flow).

**Comment by yuliiamir** [comment]
To avoid duplication of the issue, the same behaviour has been caught for update/reroute (only 'create' with required action confirmation).

**Comment by yuliiamir** [comment]
Note, the same behaviour has been caught for the update operation.

**Comment by dmitrii-beliakov** [comment]
@yuliiamir this behavior is no longer reproducible in the current develop branch. There was a refactoring mistake that has been fixed recently. I double checked for similar problems and I found only one action that potentially could be missed.

**Comment by yuliiamir** [comment]
The issue has been fixed. The required actions are present for the deletion event.
```
[
  {
    "clazz": "org.openkilda.messaging.payload.history.HaFlowHistoryEntry",
    "ha_flow_id": "10Oct105530_822_rhubarb8006",
    "time": 1696928171.743,
    "timestamp_iso": "2023-10-10T08:56:11.743Z",
    "action": "HA-Flow delete",
    "task_id": "1ab8ccd5-2acf-43b0-b904-ee0a9d4ce1f9 : fn-tests-243e82cf-0bf6-4889-bcf2-f5511edcf248",
    "payloads": [
      {
        "timestamp": 1696928171.743,
        "timestamp_iso": "2023-10-10T08:56:11.743Z",
        "action": "HA-Flow delete",
        "details": null
      },
      {
        "timestamp": 1696928171.777,
        "timestamp_iso": "2023-10-10T08:56:11.777Z",
        "action": "Commands for removing ha-flow rules have been sent",
        "details": null
      },
      {
        "timestamp": 1696928171.917,
        "timestamp_iso": "2023-10-10T08:56:11.917Z",
        "action": "Rule was deleted",
        "details": "The rule with command ID dc62d71b-674a-11ee-9ce9-db8b95aaf839 has been removed: switch 00:00:00:00:00:00:00:01"
      },
      {
        "timestamp": 1696928171.917,
        "timestamp_iso": "2023-10-10T08:56:11.917Z",
        "action": "Rule was deleted",
        "details": "The rule with command ID dc62d71d-674a-11ee-9ce9-db8b95aaf839 has been removed: switch 00:00:00:00:00:00:00:03"
      },
      {
        "timestamp": 1696928171.918,
        "timestamp_iso": "2023-10-10T08:56:11.918Z",
        "action": "Rule was deleted",
        "details": "The rule with command ID dc62d71c-674a-11ee-9ce9-db8b95aaf839 has been removed: switch 00:00:00:00:00:00:00:02"
      },
      {
        "timestamp": 1696928171.965,
        "timestamp_iso": "2023-10-10T08:56:11.965Z",
        "action": "HA-flow path has been removed",
        "details": "The following HA-path has been removed: 10Oct105530_822_rhubarb8006_966df706-d53a-4340-a713-1a75b1e8f2df"
      },
      {
        "timestamp": 1696928171.97,
        "timestamp_iso": "2023-10-10T08:56:11.970Z",
        "action": "HA-flow path has been removed",
        "details": "The following HA-path has been removed: 10Oct105530_822_rhubarb8006_6af73999-98f8-41c8-bf45-9d9aa95aa3a7"
      },
      {
        "timestamp": 1696928171.987,
        "timestamp_iso": "2023-10-10T08:56:11.987Z",
        "action": "Flow resources have been deallocated",
        "details": "The ha-flow resources for 10Oct105530_822_rhubarb8006_966df706-d53a-4340-a713-1a75b1e8f2df / 10Oct105530_822_rhubarb8006_6af73999-98f8-41c8-bf45-9d9aa95aa3a7 have been deallocated"
      },
      {
        "timestamp": 1696928171.995,
        "timestamp_iso": "2023-10-10T08:56:11.995Z",
        "action": "HA-flow was removed",
        "details": "The HA-flow 10Oct105530_822_rhubarb8006 was removed"
      },
      {
        "timestamp": 1696928171.996,
        "timestamp_iso": "2023-10-10T08:56:11.996Z",
        "action": "HA-flow has been deleted successfully",
        "details": null
      }
    ],
    "dumps": [],
    "timestamp": 1696928248741
  }
]
```
