### ISSUE TITLE
Changing the stats datasource for exporter apps.

### ISSUE THREAD

**Issue by IvanChupin** [telstra/open-kilda#5423]
In this task there are 3 exporters has been modified.

1)kilda-error-ratio-exporter/inject_dir/bin/collect_error_rate.py
kilda-error-ratio-exporter/docker-compose.yaml
```
added new params:
VICTORIA_ENDPOINT=CHANGEIT
METRIC_PREFIX=CHANGEIT

old params:
NORTHBOUND_USERNAME
NORTHBOUND_ENDPOINT
NORTHBOUND_PASSWORD
SNMP_USER
SNMP_PASSWORD
```

2)kilda-flow-ping-stats-in-db-total/inject_dir/bin/outstanding_railroad.py
kilda-flow-ping-stats-in-db-total/docker-compose.yml

```
added new params:
VICTORIA_READ_QUERY=CHANGEIT
old params:
```

3)kilda-flow-ping/inject_dir/usr/sbin/elastic-railroad.py
kilda-flow-ping/docker-compose.yml
```
new params:
VICTORIA_METRICS_SCHEMA=CHANGEIT
VICTORIA_METRICS_HOST_ADDRESS=CHANGEIT
VICTORIA_METRICS_WRITE_PORT=CHANGEIT
VICTORIA_METRICS_OPENTSDB_WRITE_PATH=CHANGEIT

old params:
NB_ENDPOINT
NB_USER
NB_PASS
```

 Need to test the updates on rigel or vega.

**There is the DIFF**
https://phabricator.common.pn.telstra.com/D37928

**Comment by niksv** [comment]
Not related to kilda
