### ISSUE TITLE
Topology Discovery Acceleration - Cache Warming Mechanisms

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#55]
Switches, Links, Flows

Provide the ability to warm up the open-kilda cache for these items. This should accelerate network convergence (ie once both switches of a link are up, no need to wait for port, we can verify the link immediately .. same with flows, once all switches in the path are up)

- Pre-populate topology (switches, links, flows)
- Accelerate Link discovery (both switches are up, send link health check)
- Ensure cached flows exist and are active (exist on the switch … and data is flowing or has flowed)

Progress:

- [x] Day 1: Investigation of current cache implementation. 
- [x] Day 2: Preliminary design. Details clarification.
- [x] Day 3: Design
- [x] Day 4: Design. Cache processing
- [x] Day 5: Saving topology into TE.
- [x] Day 6: Updating Cache functionality. Link discovery acceleration
- [x] Day 7: Link discovery acceleration
- [x] Day 8: Flows
- [x] Day 9: Flows
- [x] Day 10: Testing
- [x] Day 11: Testing/atdd

**Comment by carmine** [comment]
Estimate is between 5d-10d; probably more at 5d.

**Comment by nikitamarchenko** [comment]
I don't understand how the cache is working now, and why we are using them, so 10d for me is minimum.

**Comment by nikitacherevko** [comment]
I think this issue will take up to 10 days, because we have to figure out how caching works here and we may spend several days on it

**Comment by a-ovchinnikov** [comment]
More 10d than 5d.

**Comment by nikitacherevko** [comment]
From my point of view cache warming up is the process where we actualize our data stored in cache. Am I right that currently our cache contains all latest information related to switches/ports/links and we don’t have to update our cache “manually”? 

This is how I see what we should do. Please correct me if I’m wrong:
1. We should modify our cache topology to add possibility to get specific cached switches/links/flows.
2. Once we receive event which tell us that switch is up, then we receive second from cache and if it is up we should verify link then. The same idea for links and flows.

Besides I’d like to ask you to tell me what do you mean under “Pre-populate topology”. And one more question: how we can verify that our flow is active and how we can send link health check?

**Comment by carmine** [comment]
Consider the scenario where open-kilda is deployed for the first time, replacing some other controller.  In that scenario, there is an existing topology that needs to be discovered.

To accelerate that discovery, the user could create / upload the existing topology before connecting switches.

**Comment by carmine** [comment]
Regarding the cache ... when the system first comes up, and the cache is loaded, there should be some state variable that says "this is cached; needs to be confirmed".  Then, yes, when a switch comes up, the cached data goes from "cached" to "active" or something like that.

Why do this?  There are 2 use cases ... 1) accelerate link discovery, so that when a switch event happens, we can immediately send health checks out of ports that we think are links, rather than wait for the port up event).   Then, 2) dump a report, as part of troubleshooting, that communicates what is cached and not discovered yet.

**Comment by nikitacherevko** [comment]
@carmine How user will “create / upload the existing topology”? Is it will be some json file or something else? We should take somewhere this information about topology to save it into cache and I’d like to find out how you see it.
Thanks in advance.

**Comment by carmine** [comment]
There are some existing formats in the ATDD code branch. Look at how the topology ATDD tests read from files .. from the TopologyEngine as well.

**Comment by nikitacherevko** [comment]
This is how I see implementation:
<img width="1308" alt="screen shot 2017-12-01 at 2 48 36 pm" src="https://user-images.githubusercontent.com/6116378/33483558-0c60d9f2-d6a7-11e7-98f7-3d0b6ac5c8b7.png">

Topology will be read from json by TE with following format:
`{
    "switches": [
        {
            "switch_id": null,
            "address": null,
            "hostname": null,
            "description": null,
            "controller": null
        }
    ],
    "links": [
        {
            "available_bandwidth": null,
            "speed": null,
            "path_nodes": [
                {
                    "switchId": null,
                    "portNo": null,
                    "seqId": null
                }
            ]
        }
    ],
    "flows": [
        {
            "flowid": null,
            "src_switch": null,
            "dst_switch": null,
            "src_port": null,
            "dst_port": null,
            "src_vlan": null,
            "dst_vlan": null,
            "transit_vlan": null,
            "bandwidth": null,
            "cookie": null,
            "meter_id": null,
            "description": null,
            "path_nodes": [
                {
                    "switchId": null,
                    "portNo": null,
                    "seqId": null
                }
            ]
        }
    ]
}`

**Comment by nikitacherevko** [comment]
@nikitamarchenko @a-ovchinnikov @surabujin @carmine please take a loot at the diagram above and tell me if I'm doing something in a wrong way.

@carmine One more question about flows. First, we save them into storage in TE. What should we do after we are sure that all switches is UP? May we just tell FlowTopology to create/update flow? But we already have it created in TE and probably we have to do it differently.

**Comment by carmine** [comment]
After switches are up, and ISLs have been confirmed:

1. Are there any flows which have dead links and consequently need to be re-routed?
2. For switches / links that have been confirmed, interrogate the rules on the switch and confirm that the flow rules are still there .. first implementation should at least highlight which switches are out of sync with the TE.

**Comment by carmine** [comment]
Regarding the diagram, it looks about right.
