### ISSUE TITLE
Statistics from some of flows are missing in OpenTSDB

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#554]
### Steps to reproduce:
- The controller with staging network topology is up.
- Create 100 flows that go through a switch.
- Check that the flows are installed properly: {northbound_endpoint}/api/v1/switches/{switch_id}/flows and  {northbound_endpoint}/api/v1/switches/{switch_id}/rules/validate.
- Check that FlowStatsData appears in Floodlight log and contains switch rules corresponding to the installed flows.
```
Posting: topic=kilda.stats, message={"clazz":"org.openkilda.messaging.info.InfoMessage",
"destination":"WFM_STATS",
"payload":{"clazz":"org.openkilda.messaging.info.stats.FlowStatsData","switch_id":"de:ad:be:ef:00:00:00:01",
"stats":[{"xid":830195,"entries":[{"tableId":0,"cookie":4611686018427387906,"packetCount":0,"byteCount":0},{"tableId":0,"cookie":2305843009213693954,"packetCount":0,"byteCount":0},{"tableId":0,"cookie":4611686018427387907,"packetCount":0,"byteCount":0},
...
}],
"timestamp":1523620424223},"timestamp":1523620424223,"correlation_id":"system-request"}
```
- Check that FlowStatsData appears in Storm StatsTopology log and contains switch rules corresponding to the installed flows.
```
Ingoing tuple: {message={"clazz":"org.openkilda.messaging.info.InfoMessage",
"destination":"WFM_STATS",
"payload":{"clazz":"org.openkilda.messaging.info.stats.FlowStatsData","switch_id":"de:ad:be:ef:00:00:00:01",
"stats":[{"xid":830195,"entries":[{"tableId":0,"cookie":4611686018427387906,"packetCount":0,"byteCount":0},{"tableId":0,"cookie":2305843009213693954,"packetCount":0,"byteCount":0},{"tableId":0,"cookie":4611686018427387907,"packetCount":0,"byteCount":0},
...
```
- Check that "Processing datapoint: " message exists in Storm OpenTsdbTopology log for each rule from the FlowStatsData. Can be done via Kibana with the following query: `"Processing datapoint: " AND "pen.flow.raw.packets" AND "{switch_id}" AND "{timestampt_from_FlowStatsData}"`

- Check the number of "emit: " messages in Storm OpenTsdbTopology log. Can be done via Kibana with the following query: `"emit: " AND "pen.flow.raw.packets" AND "{switch_id}" AND "{timestampt_from_FlowStatsData}"`

### The actual result:
- The number of "emit: " messages is less than half of switch rules. Some flows don't have records sent to OpenTsdb for a while.

### The expected result:
- The "emit: " messages corresponds to the switch rules from FlowStatsData, and OpenTsdb contains values for these rules.

**Comment by sergii-iakovenko** [comment]
Resolved by #558
