### ISSUE TITLE
Switch / Flow Validation not working properly - interprets cookies incorrectly

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#559]
GET /switches/{switch_id}/rules/validate, and probably /flows/{flow_id}/validate has the same bug.

The DB and the switch has the right information , but validation misinterprets the cookie, so it thinks the rule doesn't exist.

**Comment by sergii-iakovenko** [comment]
The issue with switch rules validation & sync is resolved by #662

**Comment by sergii-iakovenko** [comment]
The flow validation handles both system and non-standard cookies properly. ATDD scenarios for these cases were added in #664
