### ISSUE TITLE
ISL Failure Policy Configuration

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#56]
At present, when an ISL fails its health check, it is deleted from the graph. We'd like to make that a policy decision, so that the operator can decide whether they want to delete the ISL, or just mark it as inactive. The benefit of marking it as inactive is that the GUI can use this information to highlight inactive ISLs; if they are deleted, then the GUI won't know it ever existed.

To add this feature, here are some things that need to be done:

- Add a configuration variable that allows the operator to select the policy.
- Make the default policy to be "INACTIVE" .. ie mark an ISL as INACTIVE if it fails the health check policy
- Add an INACTIVE attribute to the ISL state information in code and in the database. INACTIVE should be false if it has just been created/confirmed.
- Based on the policy, once the ISL health check fails, then remove it if the policy is DELETE, otherwise set the INACTIVE attribute of the ISL to True
- PCE will have to be adjusted, which means the Neo4J query will need to be modified, to ensure it ignores inactive ISLs in path computation (eg AND INACTIVE=FALSE).

Instead of calling the attribute INACTIVE, consider using ACTIVE instead.

Approach
------------
 - [x] Day 1 research (done);
 - [x] Day 2 reserach and task elaboration (done);
 - [x] Day 3 implementation of the feature (done);
 - [x] Day 4 feature testing on dev env.

**Comment by carmine** [comment]
Estimate 1-2d .. should just be an extra attribute in the table, an extra clause in the PCE query against neo4j, and some unit tests and/or acceptance tests to validate behavior.

**Comment by nikitamarchenko** [comment]
Need more information about that issue for time estimating.

**Comment by surabujin** [comment]
estimation - 5d (I need to see into neo4j first).

**Comment by nikitacherevko** [comment]
It looks like there won't be a lot of changes, but I think it will take 2-3 days, but we don't have such estimate, so I guess 5d is more suitable here

**Comment by a-ovchinnikov** [comment]
I'd say it looks more like 3d or even 4d.
