### ISSUE TITLE
OPS: Flow verification - Packets

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#565]
The idea - use our link validation mechanism to validate whole flow. We can inject validation packet on edge switch, it will be "routed" using flow rules on all intermediate switches and catched on the edge switch on other side of flow ("packet out" message must specify special out port called "TABLE" to pass packet via existing on switch open flow rules).

Goals:
- measure flow latency
- one more way to verify switch availability (detect control plane issues)

Implementation (send side):
- receive verification request vie kafka queue
- record request in validation queue (keep metadata required to check received packages and measure flow latency)
- produce verification package (this package is mostly simmilar to ISL verification package, the differences - destination MAC cotains address of target switch, vlan field is set to "input vlan")
- push verification packet into switch
- ensure that packet have been processed - use "barrier message" to ensure that switch handle all requests

Implementation (receive side)
- accept all packet_in messages
- if received packet looks like verificaion packet (match MAC address, it is UDP, match source/dest UDP port)
- if receided packet contain signed payload
- if signature match
- if verification metadata is in "pending queue"
- measure flow latency
- produce verification response (kafka queue)

**Comment by surabujin** [comment]
https://github.com/telstra/open-kilda/pull/684

**Comment by surabujin** [comment]
Got some improvements request during code review. Return tast to "in progress".

**Comment by surabujin** [comment]
@nikitamarchenko @carmine https://github.com/telstra/open-kilda/blob/feature/flow-verification-automation/docs/design/flow-ping/ping-topology.md design draft.

**Comment by nikitamarchenko** [comment]
need more clear diagrams of process, use uml

**Comment by surabujin** [comment]
Ok... more detail diagramm can be created after the code will be completed, tested and pruve it's capability to fulfill its goals. Until that moment creation of detailed diagramm will took same amount time as creation of working code.

**Comment by rtretyak** [comment]
Observing issues with flow verificaitons.
Steps:
1. Create flow between any switches
2. Run flow verification for that flow with any timeout
3. Result: no answer, request hangs.
Also observing errors in Floodlight logs:
Give up waiting for flow VERIFICATION packet (packetId: 9d141ed1-e574-467a-b2e0-0d31b2009a3d)
Give up waiting for flow VERIFICATION packet (packetId: cd3165c8-ebd3-4eca-88b8-a32375dbc1d5)
unknown error during packet_in message processing: null

**Comment by pzakatov** [comment]
Waiting for Multi-FL, since it could produce heavy load to a single FL instance

**Comment by pzakatov** [comment]
considered as done.
