### ISSUE TITLE
Health Check Policy Configuration

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#57]
- ISL Health Check Frequency (1s)
- ISL Drop/Inactive Bar (3 consecutive failures)
- Exponential backoff for inactive check (ie for inactive or failed ISLs, who frequently to continue checking?)
- Maximum Failure before stopping all checks - ie Lifetime failure limit, or sliding window failure limit. 
- Allow manually clearing failure counter(s)

NB: Issue #58 should be adjusted based on the above (ie overrides)

Approach
------------
 - [x] Day 1 research;
 - [x] Day 2 research and task elaboration;
 - [x] Day 3 implementation;
 - [ ] Day 4 implementation/testing;
 - [ ] Day 5 testing.

**Comment by carmine** [comment]
Estimate .. 5d: some of this is simple (ie frequency of check), some of this doesn't exist (backoff / max failure, etc).

**Comment by nikitamarchenko** [comment]
agree with 5d

**Comment by surabujin** [comment]
@carmine what do you meant under "some of this doesn't exist (backoff / max failure, etc)"? Is this task not about adding this stuff?

I bet 7d

**Comment by nikitacherevko** [comment]
I suppose 5 days would be enough

**Comment by a-ovchinnikov** [comment]
5d looks reasonable.
