### ISSUE TITLE
Validate and document "sync_rules" toggle

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#572]
please comment/remove a code related to this so it ("sync rules" toggle) disappear from API. We probably restore it in the future

**Comment by dpoltavets** [comment]
The message associated with "sync_rules" is commented out in the "switchActivated" method in FL.
https://github.com/telstra/open-kilda/blob/94a3058572f8db7fe32a79fc12a78249eab86372/services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchEventCollector.java#L96

**Comment by pzakatov** [comment]
So, we need to remove/comment the toggle then. We should not expose toggles which are not working.
