### ISSUE TITLE
Topology Discovery Overrides

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#58]
- Allow per-port / per-switch policy override (ie increase or decrease a health check and/or failure policy. Motivation - an infra team is suppose to bring up an isl, or an isl has gone down and needs to be fixed, an operator can make the switch / port / link discovery more sensitive and resilient until the link comes up. Also imagine if the port was previously marked as not an ISL).

- Manually invoke a one-off discovery exercise - switch / port

NB: Issue #57 is related

**Comment by carmine** [comment]
Estimate:
- 1d for the manual invoke
- 2d for the per port / per switch discovery override

Both of these mean sending a message to the storm topology to reset and/or adjust the timers / counters / etc for the port and/or switch.

**Comment by nikitamarchenko** [comment]
6d from me

**Comment by nikitacherevko** [comment]
about 5 days, I suppose

**Comment by a-ovchinnikov** [comment]
5d, not sure that such overrides must be persistent. They must be logged for sure, but I doubt that we want to keep them forever. Also theer should be some sort of a decay mechanism, i.e. these policies should turn back to regular ones after some timeout.

**Comment by pzakatov** [comment]
implemented as port discovery controls
