### ISSUE TITLE
✅Resume / ⭕️Suspend ISL - Discovery on Neighbor Switch Port when Switch is discovered

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#59]
- Resume discovery / health checks on Switch A port X, which now leads to Sw B, port Y, if we detect that B:Y has just come up and leads to A:[X]
- Suspend discovery / health checks for opposite end if switch / switch:port goes down
- Verify that ISL down follows the policy (ie is it deleted from db or marked "inactive")

- [x] add the resume feature
- [ ] add the suspend feature

**Comment by carmine** [comment]
Estimate: 1-2d.  Should just be a simple check when a switch/port comes up, we do an isl discovery across it, and once we receive it and see who is on the other end, make sure the other end is also doing health checks now.

**Comment by nikitamarchenko** [comment]
- 1-2d coding
- 1-2d atdd
- 1-2d debugging

so 5d from me

**Comment by surabujin** [comment]
Estimate 3-5d

**Comment by nikitacherevko** [comment]
I suppose 5 days is enough for this task

**Comment by a-ovchinnikov** [comment]
5d is a good estimate.

**Comment by carmine** [comment]
It appears that this may not be needed (To be confirmed) ... if the switch is connected to something that comes up, determine whether the port goes through a down/up event.

Having said that, this UC is good as a safeguard, in case physical switch behavior varies.

**Comment by pzakatov** [comment]
outdated
