### ISSUE TITLE
PCE Policy Configuration and Extensions - Cost and Latency

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#60]
Currently, the PCE will create a path between two based on the number of hops, and whether the desired bandwidth is available. For instance, if the client desires a 100MB bandwidth link between A and J, the currently algorithm ensures that 100MB is available on the suggested shortest path, which is based on the number of hops.

This issue is to make the strategy based on some policy. This means it can be configurable. The other policies are:

- BW & Cost (eg latency; manually determined)
- BW & Latency (auto calculated, presumed to be trusted)

For now, implement the BW & Cost policy.  This means that the user uploads a cost field for each link, and the PCE should select a path that has enough BandWidth, and where each link is below cost X.

Given that the user will have to upload costs, these will need to be tracked in the graph. Also, the user should specify what the default cost is, so that if a link doesn't have a specified cost, it'll be given a default cost.

Whereas at some point COST and LATENCY might be dynamically calculated, for the initial implementation, we are looking to enable the kilda operator to upload latency and cost. With the latency and cost in some link static inventory db, the data can be used when a link is discovered and put into the dynamic db.

Key Results:

- [x] *DD - Start with ATDD and TDD
  - [x] Start with one or more ATDDs that should pass once this feature is in place.
  - [x] Send the initial design around for review.

----

- [ ] Adjust DB Queries and PCE Class - ie enable each policy at the lowest level
  - [x] spike - neo4j java wrapper + dijkstra test
  - [ ] Identify an initial set of TDDs that will satisfy one or more steps of the ATDDs (this is iterative, this item just confirms you've done this once)
  - [ ] add queries and fields to neo4j db
    - [ ] including the ability to use default values for cost / latency / external if it doesn't exist .. however this may be address by the link creation process
  - [ ] validate unit tests
  - [ ] The NB API for flow creation should accept an optional variable to specify the path computation approach (hops, cost, latency). TBD - whether we'd allow a combination of filters.

----

- [ ] Adjust link Creation in TE
  - [ ] Identify an initial set of TDDs that will satisfy one or more steps of the ATDDs (this is iterative, this item just confirms you've done this once)
  - [x] The link discovery / storage process needs to look to see if there is any information in the static link inventory db (ie cost, latency) and store that with the new link, in the dynamic db.
  - [ ] There should be a policy (config variable in properties file) that the PCE uses to determine how to calculate the path. This is the default.
  - [x] Add .. Updating the cost / latency in the static db should propagate to the dynamic db
  - [x] Add .. Deleting the cost / latency in the static db should propagate to the dynamic db

----

- [ ] LINK_PROPS: NB API or TER API that allows for CRUD operations on static link data; the data should include switch/port information of src/dst; account for bi-directional asymmetric costs (ie s1->s2 cost/latency may be different to s2->s1)
  - [x] Write AT for upload / download of data through NB | TER 
  - [x] Add Create/Update to TER
  - [x] Add Delete to TER
  - [x] Add Read to TER
  - [x] Add Pass through Mechanisms to NB API
  - [x] Update LinkDto in Northbound, adding the link_props dictionary
  - [ ] Complete AT Implementation related to LINK_PROPS
  - [ ] Commit / Publish simple props mechanism

----

- [ ] Other
  - [ ] cypher.forbid_exhaustive_shortestpath to true, as explained in Operations Manual → Configuration settings -- https://neo4j.com/docs/operations-manual/3.3/reference/configuration-settings/#config_cypher.forbid_exhaustive_shortestpath

**Comment by carmine** [comment]
Estimate 2-5d .. this includes adding some attributes that my not exist .. allowing the attributes to be set ... copy / paste the query (and alter) that leverages the attribute, etc.

**Comment by nikitamarchenko** [comment]
Need more information, can't understand what should we do here.

**Comment by a-ovchinnikov** [comment]
I believe this one should take somewhere from 4d to 6d to complete.

**Comment by nikitamarchenko** [comment]
@carmine can you write more information about that issue?
