### ISSUE TITLE
BUG: Meters should start from 10, but we see 9 assigned in prod recently

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#607]

**Comment by surabujin** [comment]
The minimum meterId is set to 11 in  org.openkilda.pce.cache.ResourceCache#MIN_METER_ID. So we should not create "NEW" meters with id lower that 11. But if flow was downloaded by CrudBold during initialisation (initFlowCache method) and flow in DB have meterId we don't apply any limits on this value (meterId can be less that 11).

So "OLD" flows can have meterId lower than 11(current limit).

Do we faced this scenario or something else?

To "remove" all meterId lower that 11, we can locate and "update" all flows with meterId < 11 (meterId is "local" for switch i.e. we can have same meterId for different switches... i.e. we can have more that 10 flows with meterId < 11 in DB).

PS There is one more minimal limit for meterId. If flow topology don't sent meterId on switch - FL will allocate it manually (org.openkilda.floodlight.kafka.RecordHandler#allocateMeterId) in this case it will start from 200. It should never happen, but the code still there.

**Comment by carmine** [comment]
Has been fixed.
