### ISSUE TITLE
when ISL goes down, set cost to 10000. do nothing if cost=10000

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#608]

**Comment by pzakatov** [comment]
@surabujin currently, when ISL restored, cost restore to initial value as well.

**Comment by surabujin** [comment]
I have updated this change. Now it react only on port down event. And now it update both directions of ISL. If only one direction being updated, reverse direction keep usual cost and can be choosen during path computation.

**Comment by surabujin** [comment]
https://github.com/telstra/open-kilda/pull/661
