### ISSUE TITLE
New API: Reroute all flows which go through a particular ISL

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#609]
Initiate a reroute for all flows on this ISL.

API: PATCH `links/flows/reroute?<params>`

Related: #1548 (Maintenance mode for ISL)

**Comment by pzakatov** [comment]
consider "evacuate" option as well

**Comment by surabujin** [comment]
Path computation is split on 2 parts now - first build `AvailableNetwork`, and second one - compute path using data stored in `AvailableNetwork`.

To evacuate some ISL we should remove it from `AvailableNetwork` and try to build path.
