### ISSUE TITLE
Leverage External ISL DB to filter checks

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#61]
The motivation is if a customer TOR is linked to two separate topology switches .. we wouldn’t want to mark the links through the customer TOR as an ISL

the external ISL DB can communicate what the links are, preventing checks on ports not in the database

- [x] Day1.
- [x] Day2.
- [x] Day3.
- [x] Day4.
- [ ] Day5.

**Comment by carmine** [comment]
Estimate: 5d .. need to define the abstraction, and the implementation that will reach out to PEN.

**Comment by nikitamarchenko** [comment]
I don't know what TOR is. That's why that I will do this for 15d or more.

**Comment by surabujin** [comment]
Are you talking about neo4j DB?

**Comment by nikitacherevko** [comment]
It is not clear for me what exactly we should do, so I find it difficult to give an estimate right now

**Comment by carmine** [comment]
Ignore the motivation for the use case for a second... the solution is to define a filter that is used to determine, once a port up event is received, whether we should send a discovery packet through it or not.  The filter implementation will most likely reach out to an external system (maybe through a rest API) to determine whether an ISL discovery packet should be sent.

**Comment by a-ovchinnikov** [comment]
5d to 7d.

**Comment by a-ovchinnikov** [comment]
Also how this external DB is supposed to be populated?
