### ISSUE TITLE
Troubleshoot Topology Cache - Dump Cache

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#62]
Scope:
-  Report on cache state
-  eg: controller just started, reads cache, starts discovery topology. What from the cache has been Validated, Stale, New
-  NB: how long to keep around Stale Cached items.

For cache state .. will need to send a message to a kafka topic ; the topology should list to the topic ; and it should send the message globally (to all bolts).

- [x] Day 1. Research
- [x] Day 2. Develop design document day 1
- [x] Day 3. Develop design document day 2
- [x] Day 4. Create client day 1
- [x] Day 5. Create client day 2
- [x] Day 6. Create client day 3
- [x] Day 7. Create client day 4
- [x] Day 8. Debugging and Integration day 1
- [x] Day 9. Debugging and Integration day 2
- [x] Day 10. Debugging and Integration day 3
- [x] Day 11. Update Bolt States with new attributes day 1
- [x] Day 12. Update Bolt States with new attributes day 2
- [ ] Day 13. Documentation, tests

**Comment by carmine** [comment]
Estimate: 2-5d .. this is just adding a new "control" topic to each topology; creating a control message that tells all bolts in the topology to dump state.  The variance in the estimate is due to the number of topologies we have to do this for.

**Comment by nikitamarchenko** [comment]
I can do it for 10d, perhaps

**Comment by surabujin** [comment]
Estimate 5-7d

**Comment by nikitacherevko** [comment]
this issue may takes up to 10 days, because we need cover all this functionality with tests and 5 days may be not enough

**Comment by a-ovchinnikov** [comment]
8d to 10d.

**Comment by nikitamarchenko** [comment]
We need to create a separate debugging mechanism for checking what is going on inside all bolts and all topologies. @carmine Am I right?

**Comment by carmine** [comment]
Generally speaking, we should create a design for troubleshooting the storm topologies. One option for debugging is to create a single kafka topic that all topologies listen to and process the message if applicable to them. Another option is to create a topic per topology. Feels like a global topic could be more useful, particularly if there are messages that can be global.

**Comment by nikitamarchenko** [comment]
current progress here https://github.com/telstra/open-kilda/compare/master...nikitamarchenko:dev/nmarchenko/debug-system

**Comment by nikitamarchenko** [comment]
demo https://asciinema.org/a/Fv0RWO6PL22CP3COVQYOpBNCg
