### ISSUE TITLE
Troubleshoot Storm Topologies

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#63]
For each topology that maintains some state, create spout that listens to debug topic, with a command to dump state information. Should be global spout - ie goes to all bolts.

Add a task to complete this work item for each storm topology

- [x] Day1.
- [x] Day2.
- [x] Day3.
- [x] Day4.
- [x] Day5.

Extra required tasks:

- ~~Day6 - solve issue with determine "last" response message~~
- [x] Day7 - tests/testing
- [x] Sync with @nikitamarchenko and push PR.

**Comment by carmine** [comment]
Estimate: 5d .. add a "control" topic for each topology, and a "control" message that can be used to do some debugging.

**Comment by nikitamarchenko** [comment]
agree with 5d

**Comment by surabujin** [comment]
Agree with 5d too.

**Comment by a-ovchinnikov** [comment]
Looks like it can be done in 5d.

**Comment by nikitamarchenko** [comment]
Sequence Diagram:
![image](https://user-images.githubusercontent.com/3450363/33181215-06cc2e90-d078-11e7-9807-b4d78fcefccf.png)

The scope of work:
- create a client with ability send\recive Kafka messages, and print a result I propose use python for that.
- create new KafkaSpout for all topologies
- create KafkaBolt to all topologies
- add new KafkaSpout and KafkaBolt to topologies
- add dump state functional to all bolts with a state

I will write client as part of #62.

@carmine @surabujin @nikitacherevko @a-ovchinnikov If you have any questions or objections, please write comments in that thread.

**Comment by surabujin** [comment]
The list of stateful bolt that must be altered to implement this "dump" mechanics:
* `org.openkilda.wfm.topology.cache.CacheBolt`
* `org.openkilda.wfm.topology.event.OFELinkBolt`
* `org.openkilda.wfm.topology.event.OFEPortBolt`
* `org.openkilda.wfm.topology.event.OFESwitchBolt`
* `org.openkilda.wfm.topology.flow.bolts.CrudBolt`
* `org.openkilda.wfm.topology.flow.bolts.TransactionBolt`

And we have one more stateful bolt `org.openkilda.simulator.bolts.SwitchBolt` that is part of "simulator". Should it be altered too?

**Comment by carmine** [comment]
The initial design looks about right. What is missing is the message format (high level).  You'd want to be able to:

1) hit all topologies, and stateful bolts within them, or

**Comment by nikitamarchenko** [comment]
We will use CommandMessage from messaging as base format and use destination field for targeting.

1. destination='*' | hit all topologies, and stateful bolts within them
2. destination='topology_name/*' | or hit all stateful bolts within a single topology
3. destination='topology_name/bolt_id' | or hit a single stateful bolt within a single topology.
Also, we can use full wildcards support in future.

Command format:

```
{
  "name": "command_name",
  "args": [
    "arg1",
    "arg2",
    "argN"
  ]
}
```

Updated diagram
![image](https://user-images.githubusercontent.com/3450363/33287210-a88a037e-d3c0-11e7-9ab1-4c41cabf3a5f.png)

**Comment by nikitamarchenko** [comment]
current progress here https://github.com/telstra/open-kilda/compare/master...nikitamarchenko:dev/nmarchenko/debug-system

**Comment by surabujin** [comment]
Split out "solve issue with determine "last" response message" into https://github.com/telstra/open-kilda/issues/97
