### ISSUE TITLE
Change message "Deactivating ISL: src_switch=<switchID>, src_port=<port>"

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#639]
change to Warn
add a reason: port down, no packets, etc.

**Comment by surabujin** [comment]
The message format have been changed, the current message for this event

```
Deactivate ISL ff:fe:00:00:00:00:00:0a-2 <===> ff:fe:00:00:00:00:00:0b-2
```

but the level is still "info". @pzakatov Should we change log level on warning?

**Comment by pzakatov** [comment]
@surabujin, yes, please.

**Comment by pzakatov** [comment]
@surabujin , what is the status?

**Comment by pzakatov** [comment]
outdated
