### ISSUE TITLE
500 on create flow in case "Path was not found"

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#659]
We need be more specific on this error:

- Code: 404 Not Found. 
- Error message: "Can't create flow. Not enough bandwidth found or path not found"

**Comment by npliashechnikov** [comment]
Verified - now Kilda generates HTTP 404 on both "Create Flow" and "Update Flow" API calls, although the error messages are slightly different:
Create flow: Could not create flow: Not enough bandwidth found or path not found
Update flow: Could not update flow: Path was not found
