### ISSUE TITLE
Rename "WFM" storm topology

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#687]
In code we have "event" topology, it handle ISL(network) discovery process. When it uploaded into storm it's name replaced with "wfm". It produce confusion.

At least one of this item must be renamed to make naming consistent across system.

PS To add even more confusion - our module with all storm topology have name WFM (WorkFlowManager)

**Comment by pzakatov** [comment]
It should be called "Event"

**Comment by pzakatov** [comment]
@PinGwynn , what is the status?

**Comment by pzakatov** [comment]
outdated
