### ISSUE TITLE
Pipeline design

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#688]
The goal of this document it to collect ideas about "defining" pipelines in
open-kilda project.

Terminology
-----------
* `event` - single processing data unit
* `service` - some isolated component/application that group `handlers` in it
* `handler` - processing unit - it consume `event` from `transport`, process it, 
  produce 0..N new `events` 
* `branch` - when `handler` produce more than 1 `event` on 1 incoming `event`
* `transport` - set of tools provides communication channel between 
  `handlers` - now it is a kafka and storm internal transport
* `pipeline` - set of `handlers` that should be executed to complete a `task` 
* `task` - one instance of business function the project is created for (link 
  discovery, link health check, flow create, flow read, flow update, flow 
  delete, etc)

Current implementation
----------------------

There is no any pipeline definition now. Each `handler` consume `events` from 
`service's` (they relate to) `transport` (kafka topic) i.e. each `service` 
have one incoming `transport` channel(kafka topic). Each `handler` must 
know where to send the results of it's work (produced `event`) i.e. kafka 
topic.

Advantages:
* hm... it is exists now and sometime works as expected
* `hanlders` don't know anything about whole `pipeline` (almost don't know, 
  exception is the target `transport` channel) 

Disadvantages:
* There is no way to trace whole pipeline - you can't say in advance which 
  `services`/`handlers` will be involved in serving specific `task`.
* There is no simple way to detect is the `task` have been completed
* There is no simple way to detect the `task's` failure when some of the 
  `handlers` produce error `event`.
* There is no simple way to set a timeout on `task` execution.
* There is no simple way to trace `branches`.
* There is no way to cancel/stop `task` processing in the middle of `pipeline`.
* There is no simple way to trace `task` execution. (correlation-id in logs 
  partially remove this disadvantages)
* Altering existing `pipelines` is extremely time consuming 

Proposition
-----------

There is 2 main principles that "make" this idea:
 * each `pipeline` must use it's own `transport` channel i.e. kafka topic
 * each `event` have it's unique identifier(type), so handler can distinguish 
   `event` it should/can handle

So all handlers for specific `pipeline` consume one specific `transport`
channel. When handler catch `event` it can/must handle, it do it's job and send
produced `events` to the `transport` channel where from it have read the 
original `event`.

The cost of this proposition is increased count of kafka topics. Now we have 
less than 10 topics. If we will follow this proposition it's count will 
increase to ~15-20... and in future each new business function will lead to the 
new `transport` channels.

Advantages:
* `handlers` still know nothing about `pipeline`.
* easy to find out all `handlers` that belong to specific `pipeline`.
* easy to find out which`pipeline` the `handler` belong to
* easy to catch and handle `handlers` failures (one `handler` in each pipeline 
  should listen for error `events` and mark the `task` as failed)
* easy to set timeout on `task` execution
* easy to cancel/stop `task` execution (post "cancel" `event` in channel and 
  all handlers should ignore events with specified `correlation id`)
* easy to trace all "branches" of `task` - special `handler` can count amount 
  of produced `branches` and trace all of them by processing future `events`.
* easy to make a tool that will monitor `tasks` execution (it should connect to
  `transport` channel collect and group `events` by correlation-id and make
  analysis about presence of "special" event types - errors, timeouts etc)
* can be used with our current tools set (storm, FL, python apps etc)

Disadvantages:
* each `handler` should read all `events` in channel and filters out `events` 
  that he can't/should not handle
* increased amount of `transport` topics (more monitoring events, more infra 
  job during deployment)

**Comment by carmine** [comment]
Is this topic still active? Meaning, it has been over 90 days, not sure whether to keep this open or not.

**Comment by surabujin** [comment]
Become obsolete because of proposed H&S approach.
