### ISSUE TITLE
Get status for non-existent flow causes logging of errors

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#717]
Northbound returns expected 404 on a GET request for non-existent flow (e.g. `/api/v1/flows/status/some-non-existent-flow`), but error messages are logged in Northbound and WFM logs.

The flow resource (`/api/v1/flows/some-non-existent-flow`) handles such case correctly and doesn't log errors.

Expected behavior:
- A client receives a response with 404 code and error message as a body.
- No error-level message is logged in Northbound and WFM logs. Instead, another log level can be used.

**Comment by abochkarev** [comment]
@sergii-iakovenko It looks like a client already gets a response with 404 code and error message as a body in case of a non-existent flow. 

Regarding "No error-level message is logged in Northbound and WFM logs. Instead, another log level can be used." - could you please add more details, which log level is more preferable?

**Comment by dpoltavets** [comment]
This bug has already been fixed.
