### ISSUE TITLE
System allows to successfully create flow for not available switch port

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#739]
When we use too big port number (which is not available on the switch) when creating the flow, our system does not show that the problem occurred and reports that the flow is in UP state, which is false.

**Steps to reproduce**
- Login to switch to see available ports by running `show config port portno all`, take number which is +1 higher than the last available port OR just take a very big portno (999)
- Create a flow through that switch (src or dst) and use a not available portno ('port-id') from previous step
**Expected:** any kind of error, warning or status, explaining the inability to create the requested flow
**Actual:** Switch has no rules installed, but the requested flow is created in Kilda and has an UP status.

Tested on a Noviflow switch.

**Comment by pzakatov** [comment]
We need to understand how to detect and store number of ports for a switch

**Comment by andriidovhan** [comment]
This issue is not actual for APIv2.
