### ISSUE TITLE
Propagate ISL properties in TE

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#757]
In original design event(wfm) proxy/send ISL properties on each incoming ISL event. Later is was disabled and ISL properties stops updating. Now ISL property updates only during ISL flapping.

In other words we do not update ISL related info in DB when such update happen on HW.

Affected properties:
- latency
- speed
- available_bandwidth (is it really required to have both - speed and available_bandwidth?)

At least link "latency" should be updated in DB in "real time".

**Comment by pzakatov** [comment]
outdated
