### ISSUE TITLE
Half-up ISL trigger reflow

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#767]
# In short

During normal ISL discovery process we have time window when reroute events 
will fails. And out event processing mechanism emits reroute events without 
taking in account of this "time window".

# In detail

Each end of ISL trigger ISL "DISCOVERY" event - so 1 ISL discovery
represented as 2 ISL DISCOVERY event. This events emits by event(wfm) topology,
cached by TE and send later in Cache topology(CacheBolt).

event => TE => cache

TE update neo4j. Now it guarantee that ISL is always represented by 2 links
between switch nodes (forward and opposite directions). It also guarantee that
ISL become `active` only when both side of it have been reported as 
"DISCOVERY".

So after first ISL DISCOVERY event (one direction) processed by TE in DB we
still have ISL marked as `inactive`. (2)

CacheBolt on ISL DISCOVERY event emit reroute request for each flow in DOWN
state and each flow that was evacuated from reported ISL. So on first of 2
mentioned ISL DISCOVERY event it(cache) emit N reroute request... but at this
moment ISL is still in `inactive` state and this reroute will fail. It is not
become an customer visible issue, because on second ISL DISCOVERY event
cache emmit same set of reroute request and at that time ISL is in `active`
state and can be used by path computation mechanism.

# Conclusion
We must not emit reroute request until ISL have been switched into `active`
state.

**Comment by pzakatov** [comment]
outdated
