### ISSUE TITLE
Event/wfm possible events lost during sync with FL

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#786]
During sync with FL event/wfm wait `sync-end-marker` in input stream. And all events that come before process as `sync events`. But on FL side (due to multithreaded nature) "real" event can be produced and posted in the middle of sync `stream`.

So it will be processed as `sync event` i.e. it not processed (only event/wfm cache update). It can lead(depends from event) to "lost" ISLs/ports.

**Comment by pzakatov** [comment]
Options: 
- requeue 'real' events
- make sync via separate stream/topic

**Comment by surabujin** [comment]
The simplest way to "fix" this - add synchronisation inside FL between parts that send messages into discovery topic. I.e. block(postpone) sending of "real" discovery events during producing "network dump".
