### ISSUE TITLE
Feature Request: provide API to return all ISL links on given a switch by id/name

### ISSUE THREAD

**Issue by andy-wang-haibo** [telstra/open-kilda#829]

**Comment by pzakatov** [comment]
we should implement support for `src_switch`, `src_port`, `dst_switch` and `dst_port` filters for `GET /links` API,

so if a user wants to get all ISLs for the switch, it can fill ether `src_switch` or `dst_switch` and get what she wants.

**Comment by Levitan** [comment]
Closed because outdated. This API already implemented
