### ISSUE TITLE
Create tests for "Stop sending ISL discovery on Port/Switch Down events"

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#85]

**Comment by surabujin** [comment]
It was implemented/fixed in https://github.com/telstra/open-kilda/pull/105

**Comment by carmine** [comment]
#105  is for external ISL DB, not for "stop sending ISL discovery on down events"

**Comment by carmine** [comment]
Assigning to NC, as he is working on the ATs for it now.

**Comment by pzakatov** [comment]
outdated
