### ISSUE TITLE
Improve FL logging

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#895]
There is a set of the error message with lack of `context` information. It makes them useless for issue analysis.

Examples:
```
Exception reading flow stats
Exception reading port stats
Could not get flow stats: null
Could not get a barrier reply: null
```
## RecordHandeler 
Log message severity levels need to be reviewed - to be able to disable debug logging.

## SwitchEventCollector
New messages regarding switch management state(activate, deactivate, disconnect, etc) must be added. Without them, we don't have a "clear" picture regarding actual(from FL point of view) network state.
Level - info.

**Comment by abochkarev** [comment]
It looks like exception messages were already fixed. Details are in revision: b374124. Need to investigate RecordHandeler/SwitchEventCollector.

**Comment by niksv** [comment]
Pull Request: https://github.com/telstra/open-kilda/pull/1331
