### ISSUE TITLE
Request times out if send link property with key that equals any key from LinkPropsPut class

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#908]
1. Create link properties request with props: `"props": { "props": "1" }`
**Expected:** Any valuable response
**Actual:** No response received, NB times out, errors for TE appear in Kibana 
`TypeError: type object got multiple values for keyword argument 'props'`

**Note:** reproducible for any of these props: props, link_props, dest, source, port-id, switch-id

**Comment by dpoltavets** [comment]
This issue solved in #1190 pull request.
