### ISSUE TITLE
Extra resource bandwidth reservation during path computation

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#919]
During flow update/reroute path computation engine search "new" one more path with requested bandwidth. And release current occupied by flow bandwidth only after flow will be deployed.

This behavior is fine until we have a flow with bandwidth closer or equal to maximum available bandwidth i.e. bandwidth near to maximum network throughput. In this case, we will be unable to update such flow, because during path computation we will fail to find one more path with such bandwidth.

Example:
We have a topology with 2 switches and 2 ISL.
```
SW_A ==( 1000M )== SW_B
 "======( 500M )==="
```
Create Flow A on 900M. 
Try to decrease flow's A bandwidth to 600M - FAIL.
Try to increase flow's A bandwidth to 1000M - FAIL

Only if we decrease flow's A bandwidth to 500M - it will success. And as second step we can increase flow's A bandwidth up to 1000M (ugly hack).

Need to change path computation logic - it should treat bandwidth of current(updating) flow as not allocated (free).

**Comment by rtretyak** [comment]
Note: Trying to reroute such flow leads to a reroute failure and flow changing status to 'Down', though flow still being active and having traffic.
