### ISSUE TITLE
Evolve Event Topology to interact with Neo4J directly (and deprecate Topology Engine in this area

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#937]
This is more of an EPIC issue. The goal is to refactor all network topology state out of Topology Engine and into a storm topology, presumably the Event Topology as an additional set of bolts.

**Comment by surabujin** [comment]
What about "flow" portion of TE functionality?

What about "get rid from Neo4j" (it is step in opposite direction from isolation/minimization usage of neo4j)?

**Comment by pzakatov** [comment]
implemented as a part of H&S.
