### ISSUE TITLE
Increase "watchdog" work verbosity in event/wfm topology

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#941]
Event/wfm topology have "watchdog" that track communication channel between event topology and FL. It notify event topology about connection lost. And this notification initiate the synchronization process with FL.

Need to add log message on "warning" level in points where "watchdog" detects connection issues (there is several check point before "connection lost" event).

**Comment by pzakatov** [comment]
@surabujin , could you please clarify where to find "watchdog" in the code. thanks.

**Comment by surabujin** [comment]
Not actual any more due to removal of `event` topology.
