### ISSUE TITLE
Investigate incoming kafka messages caching capabilities in FL

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#942]
There is a change that FL cache/queue incoming kafka requests.

Scenario:
 * make heavy load on FL(massive flows reroute)
 * wait till "big" kafka-lag on TE topic/consumer group appear
 * stop TE, to stop message flow into FL
 * observe FL - it will continue to process "some" input despite 0 kafka-lag on FL/consumer group.

For goal "FL is stateless" we must eliminate any attempt to cache/queue any significant amount of incoming messages.

**Comment by sergii-iakovenko** [comment]
The solution is described [here](https://github.com/telstra/open-kilda/blob/f15801b91044653f663ac5f1bb494a030c2b9c41/docs/design/solutions/floodlight/floodlight-guaranteed-processing.md).
