### ISSUE TITLE
Reroute may cause Flow cache inconsistency

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#955]
A series of reroute commands for a flow may lead to race condition in TE, and as a result causes inconsistency between Neo4j and Flow cache data.

**Steps to reproduce**
- Create a flow.
- Initiate a series of reroute commands (10 or more) with minimal interval for the flow.
- Try to delete the flow.

**Expected Results**
- Flow cache keeps the actual cookies for the flow.
- The flow is deleted.

**Actual Results**
- Flow cache may be updated with cookies by not the latest reroute command.
- The flow is not deleted by the FlowDeleteRequest as the cookies differ.

**Comment by pzakatov** [comment]
Outdated due to cache elimination activities
