### ISSUE TITLE
TE doesn't guarantee consistency of flow.flowpath and flow_segments

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#959]
Different operations in the system relies either on flow.flowpath (building of install OF commands, flow validation) or flow_segments (building of delete OF commands, switch validation & sync, etc.). Although these two are representations of the same entity, TE operates with them separately and in a case of uncompleted execution may lead to inconsistency between them.

Possible solutions:
- Use the only one representation of flow path.
- Utilize transactions when perform modifications of flow path.

**Comment by pzakatov** [comment]
TE has been removed
