### ISSUE TITLE
BUG: FL send TCP packets bigger than MTU

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#964]
which cause some switches to die.

They are big because contains multiple OF messages in one TCP packet.

We should limit the number of OF messages per TCP packet so they will not exceed MTU.

**Comment by jonvestal** [comment]
That sounds about right.  I've been looking a bit at the Floodlight code but can't find a quick smoking gun.  The packet_out message is being written with IOFSwitch.write(packetout) within the PathVerificationService.

**Comment by surabujin** [comment]
The goal to have one OFMessage in TCP packet... not leading to solving this issue. OpenFlow-v1.5 spec 6.3.2

```
Segmentation and reassembly: The size of an OpenFlow message can be up to 64kB, which
exceeds most link MTU sizes, and OpenFlow does not offer a mechanism to fragment most messages,
therefore the transport protocol must be able to perform fragmentation and reassembly of
OpenFlow messages as needed.
```

Even if we manage to have 1 OF message per 1 ip packet we will faced this issue again with "big" OF messages.

Is there a change that some path segment between FL and switch incorrectly report MSS? If all path report correct MSS - tcp protocol must adjust maximum produced packet size.

**Comment by jonvestal** [comment]
I agree issue is that the noviflow switch is not dealing correctly with fragments.  The only way I know to find MTU is to do try path MTU discovery by sending a reasonable sized packet to the switch with do not fragment set and keep backing off until it is received.  But even that could cause problems if the path changes.  

I have a call with noviflow in the morning but for now we need to keep the packet smaller than 1000B which will be safe on our control plane.

**Comment by surabujin** [comment]
@jonvestal the simplest solution I can imagine - is to set MTU on FL side to 1000B. It will affect all connections, but it at same time it shinks TCP MSS down to 1000B.

Not so destructive way is to use iptables(on FL side) and force TCP MSS in one(several) specific direction, the directions with problematic switches. It should provide us with same benefits(fix MTU overcome issues), but do not force small MTU value for all existing connections.

PS Do this switches respect mtu(mss) when producing big responses(rules stats, rules lists etc)?

**Comment by jonvestal** [comment]
They do not respect MSS when they send a response packet, they expect the controller to reassemble.  I’m going to raise this with them tomorrow.  I’m not sure why it only uses the large packet for only this switch, I’m thinking we are just getting lucky at the moment.  The IPTables solution is interesting in that we don’t have to restart FL and could do everything in the 198.18/16 subnet which basically fixes all switches without having to touch FL for now.  Only do it in the outbound direction such that return packets that are large don’t hit the limitation.

Question is, how do we test it?

If Noviflow agrees it is their problem then once they fix reassembly just drop IPTables rule, else we limit it at FL.

Thoughts?

**Comment by jonvestal** [comment]
Related question.  The way I read the spec it makes it sound like the switch/controller is responsible for the reassembly and that per the spect fragmentation is allowed.  Before I go off on Noviflow tomorrow, do you agree with that assessment?  Don’t won’t to yell at them for nothing…

**Comment by jonvestal** [comment]
This is interesting:





That is on a 21100 and capabilities says the OFPC_IP_REASM is disabled.  I’m trying to grab a copy of the Handshake on a 2128 to see if it does the same thing.  Basically this is going to screw us.  And I can’t yell at Noviflow as the result set is telling us that the switch doesn’t support fragmentation.  Section B.6.7 of the OF1.3 spec defines this (sorry copy/paste not working on the doc).

Jon

**Comment by jonvestal** [comment]
Sorry it didn't include the image.  All Noviflow switches respond with Feature that says OFPC_FRAG_REASM FALSE.

So we are going to have to deal with this long term, I can fight with Noviflow on it.

**Comment by jonvestal** [comment]
I'm thinking long term we are going to have to set the Do Not Fragment flag on messages sent to the switch, which should cause a message to come back if any device cannot forward the packet.  Then we will have to do "trial and error" to find the largest packet that can go through and track that per switch.  Unless anyone else has any ideas.

For now, lets hardcode it at 1000B.  In our IPVPN that will be fine.

**Comment by surabujin** [comment]
@jonvestal OFPC_IP_REASM is related to process data plane by the switch...

```
The OFPC_FRAG_* flags indicate whether IP fragments should be treated normally, dropped, or reassembled.
“Normal” handling of fragments means that an attempt should be made to pass the fragments
through the OpenFlow tables.
```

In other words this is the capability of OFSwitch to process fragmented IP packets **through the OpenFlow tables**.

Our problem are in control plane i.e. the way how switch handle TCP stream to itself. If switch OS is based on some linux(linux kernel) it must be capable to reassemble incoming IP packets. Unless this TCP stream is passed through channel that drop fragmented IP packets and there is nothing to reassemble on receiver end.

I am truing to say, that value OFPC_IP_REASM (same as OFPC_FRAG_* flags) on switch itself is unrelated to connectivity issue by control plane (unless control plane is going through data plane of this switch).

This is the regular TCP connection, so we can try to set MSS value (simplest way via iptables) to limit maximum size of produced IP packets. If this is a IP fragmentation issue - it will go away, if not - we should keep investigation.

**Comment by jonvestal** [comment]
I agree.  Sorry for the red herring.

I'm not sure MSS will help though as that is going to cause fragmentation and that is probably the problem.  But we can try provided I can reproduce in the lab which I'm hoping to test now that the lab 21100 has 20 ports UP.

**Comment by surabujin** [comment]
The problem was not on software/application level. It was caused by some combination of buggy/damaged hardware.
