### ISSUE TITLE
Safe rule application may block reactor thread in Floodlight kafka consumer

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#966]
The reactor thread of FL kafka consumer (org.openkilda.floodlight.kafka.Consumer.run())  is used by SwitchManager to process safe rule application on switches. As a part of this logic   switchManager.safeModeTick() performs several operations which may block the thread: fetching switch rules, deleting rules. As a result, FL kafka consumer stops reading messages for an undetermined time period. 

Possible solutions: 
- Run safe rule application in a dedicated thread.
- Utilize the reactive approach to avoid blocking of a thread. E.g. dumpFlowTable can return CompletableFuture and the rest of the code is executed as thenApply.

**Comment by surabujin** [comment]
I am going to use "reactive approach", I have a "plan" how to implement it in FL. I will prepare design.

**Comment by IlyaMoiseev** [comment]
Design proposal is in #967. But needs to clarify which processing guaranties needed for "safe" rule application.

**Comment by rozdy** [comment]
Safe mode was removed in #4818
