### ISSUE TITLE
Improve "ctrl" protocol

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#97]
"Ctrl" protocol is used to send control "signals" to the storm's bolts. Current implementation spread control signal across all target bolts and each of this bolt send response on this signal.

And here is the problem - client don't know how many bolts are targeted and as result it can't determine how many result records it should wait.

Solution - replace common kafka spout with custom one. This custom kafka spout must handle ack/fail calls. On this calls it must send message with "last" marker. So client should wait record with correct correlation-id and "last" marker. It will be reliable sign that request is completelly processed.

**Comment by pzakatov** [comment]
apr'22 cleanup
