### ISSUE TITLE
[Kilda-Gui] [Backend] Get flow packet ingress and egress lose data

### ISSUE THREAD

**Issue by ashishaggarwalCS** [telstra/open-kilda#970]
Create an api that returns ingress packets in forward and reverses direction from open tsdb

**For ingress packet lose :**

	metric:
		flow.ingress.packets
	tag:
		direction -> forward
		flowid -> <FLOW_ID>
	
	metric:
		flow.packets
	tag:
		direction -> forward
		flowid -> <FLOW_ID>
 
**For egress packet lose :**

	metric:
		flow.ingress.packets
	tag:
		direction -> forward
		flowid -> <FLOW_ID>
	
	metric:
		flow.packets
	tag:
		direction -> forward
		flowid -> <FLOW_ID>

**Comment by hiteshgupta1** [comment]
Fix with PR #1001
