### ISSUE TITLE
[Kilda-Gui] [Frontend] New graph in ISL detail screen to show forward and reverse packet lose for an ISL

### ISSUE THREAD

**Issue by ashishaggarwalCS** [telstra/open-kilda#971]
To get the data packet lose in forward direction for an ISL call
#972 with switch A and Switch B

	metric:
		switch.tx.packets
	tag:
		switchId -> <switch_A>
		port -> <port_A>
	
	metric:
		switch.rx.packets
	tag:
		switchId -> <switch_B>
		port -> <port_B>
		

To get the data packet lose in reverse direction for an ISL call
#972 with switch B and Switch A

	metric:
		switch.tx.packets
	tag:
		switchId -> <switch_B>
		port -> <port_B>
	
	metric:
		switch.rx.packets
	tag:
		switchId -> <switch_A>
		port -> <port_A>

**Comment by hiteshgupta1** [comment]
Fix with PR #1032
