### ISSUE TITLE
[Kilda-Gui] [Backend] Returns stats of packet lose for an ISL

### ISSUE THREAD

**Issue by ashishaggarwalCS** [telstra/open-kilda#972]
Create an api that return packet lose for an ISL from open tsdb

**To get packet lose:**

	metric:
		switch.tx.packets
	tag:
		switchId -> <switch_A>
		port -> <port_A>
	
	metric:
		switch.rx.packets
	tag:
		switchId -> <switch_B>
		port -> <port_B>

**Comment by hiteshgupta1** [comment]
Fix with PR #1001
