### ISSUE TITLE
[Kilda-Gui] [Backend] Ability to show TX/RX on a path

### ISSUE THREAD

**Issue by ashishaggarwalCS** [telstra/open-kilda#974]
Create an api to get flow raw packets stats from opentsdb in forward direction, corresponding to flowid and switchIds  :

metric:
	flow.raw.packets

	"flowid" -> <FLOW_ID>
	"switches"-> [<SWITCH_ID>,<SWITCH_ID>]

**Comment by hiteshgupta1** [comment]
Fix with PR #1001
